# fuzznet -- the shared authenticated datagram protocol.
#
# project.md sec 10 step 3 makes chain/ the first real code: sec 7a gave most
# of sec 4 to situ once the layer ladder arrived, and the capability model is
# what stayed ours, being semantics rather than layout or transport.
#
# There is deliberately NO archive rule. project.md sec 7 has consumers
# compiling these sources into their own objects, with their own flags --
# fuzzypickles cross-compiles for Android and builds sanitized, netcfgd's
# agent is an ordinary host binary, and a prebuilt .a serves neither.
# build-and-commit.md says not to add an archive step without a specific
# need, and the need this would answer is one nobody has.

BUILD_DIR ?= .
CC        ?= cc
DESTDIR   ?=
PREFIX    ?= /usr/local

# -Os because that is the workspace default and this library is aimed at
# routers and phones: it is the instruction cache that is scarce here, not
# the arithmetic. -Og when debugging, deliberately and temporarily.
CFLAGS  ?= -Os -g

# SANITIZE=1 builds everything under AddressSanitizer and UBSan.
#
# It exists because the canaries in the fuzz harnesses are a substitute for
# this, and say so: on a plain -Os build a two-byte overrun into a
# neighbouring slot corrupts somebody else's message and returns success.
# A canary catches a WRITE past the end of a buffer it brackets. It cannot
# see a read of bytes nothing wrote, an off-by-one inside the buffer, or
# signed overflow -- and those are the defects this library's arithmetic
# could plausibly have, since it computes offsets from values a stranger
# chose.
#
# NOT the default, deliberately. project.md sec 7 has each consumer
# compiling these sources with its own flags, and a library that forced a
# sanitizer on them would be choosing for fuzzypickles' Android build. It
# is a knob for this tree's own testing:
#
#   make test SANITIZE=1
#   make fuzz SANITIZE=1 CASES=200000
#
# -Og rather than -Os under it, because a sanitizer report through fully
# optimised code names the wrong line, and BUILD_DIR should be set to keep
# the objects apart from a plain build's -- they are not interchangeable
# and mixing them produces a link nobody can explain.
SANITIZE ?=
ifeq ($(SANITIZE),1)
# Replaces the optimisation and adds the instrumentation. The warning flags
# are NOT repeated here -- they are appended below for both builds, and
# listing them twice put every one of them on the command line twice.
CFLAGS  := -Og -g -fsanitize=address,undefined -fno-omit-frame-pointer \
           -fno-sanitize-recover=all
endif
# Split, because generated and vendored sources need one half and not the
# other. CFLAGS_WARN is about OUR source; everything else in CFLAGS is about
# the BUILD -- architecture, optimisation level, sanitizers, a sysroot.
CFLAGS_WARN := -std=c11 -Wall -Wextra -Wpedantic -Wshadow -Wconversion \
               -Wstrict-prototypes -Wvla
CFLAGS  += $(CFLAGS_WARN)

# WHAT GENERATED AND VENDORED SOURCES GET, and why this is derived rather than
# written out.
#
# Their rules used to hard-code `-Os -g`, on the reasoning that -Wconversion
# against a code generator's output is noise nobody reads. That reasoning is
# right and the implementation dropped far more than warnings: no
# architecture flag, no optimisation change, and no sanitizer reached them.
#
# Measured 2026-08-20. In every SANITIZE=1 run this project has cited,
# wire/generated/frame.o and situ.o carried zero __asan symbols while
# wire/seal.o carried 21 -- so situ's bounds arithmetic, which is the code an
# out-of-bounds access would live in, was the one part never instrumented. And
# `make test CFLAGS="-Os -g -m32"` failed at link with "i386:x86-64 ...
# incompatible with i386 output", because the generated objects had ignored
# the -m32.
#
# GEN_EXTRA existed to thread --coverage through the same hole, which is the
# tell: each time something needed to reach these objects, another variable
# was added instead of the rule being fixed.
GEN_CFLAGS = $(filter-out $(CFLAGS_WARN),$(CFLAGS)) $(GEN_EXTRA)
CPPFLAGS += -MMD -MP

# Generated by situ and vendored from it. Compiled with their own terms
# rather than ours -- code-style.md exempts generated and vendored sources,
# and -Wconversion against a code generator's output is noise nobody reads,
# which is how a warning that matters gets missed. They happen to be clean
# under our full set today; that is luck to enjoy, not a rule to enforce on
# somebody else's emitter.
GEN_SRCS  := wire/generated/frame.c wire/generated/frame_relate.c \
             wire/generated/situ.c
GEN_OBJS  := $(GEN_SRCS:%.c=$(BUILD_DIR)/%.o)

SRCS      := constant_time/constant_time.c session/commitment.c \
             local/peer.c local/peer_linux.c local/vocabulary.c \
             chain/chain.c chain/revocation.c frame/freshness.c \
             chunk/reassembly.c \
             chunk/split.c \
             wire/seal.c wire/relay.c \
             session/random.c session/random_linux.c \
             version/version.c \
             record/record.c record/journal.c record/sync.c \
             state/state.c trust/trust.c log/log.c sched/sched.c link/link.c
OBJS      := $(SRCS:%.c=$(BUILD_DIR)/%.o) $(GEN_OBJS)
HDRS      := constant_time/constant_time.h session/commitment.h \
             local/peer.h local/vocabulary.h \
             chain/chain.h chain/revocation.h frame/freshness.h \
             chunk/reassembly.h \
             chunk/split.h \
             wire/seal.h wire/relay.h wire/bytes.h session/aead.h \
             session/random.h session/random_system.h \
             version/version.h \
             record/record.h record/journal.h record/sync.h \
             state/state.h trust/trust.h log/log.h sched/sched.h link/link.h

TEST_SRCS := chain/test/chain_test.c chain/test/revocation_test.c \
             frame/test/freshness_test.c \
             chunk/test/reassembly_test.c chunk/test/split_test.c \
             session/test/commitment_test.c local/test/peer_test.c \
             wire/test/generated_test.c chunk/test/agreement_test.c \
             wire/test/constants_test.c wire/test/seal_test.c \
             session/test/random_test.c local/test/vocabulary_test.c \
             local/test/vocabulary_fuzz.c local/test/admit_test.c \
             local/test/peer_fuzz.c local/test/peer_linux_test.c \
             chunk/test/reassembly_fuzz.c chain/test/chain_fuzz.c \
             frame/test/freshness_fuzz.c chain/test/revocation_fuzz.c \
             frame/test/receive_fuzz.c \
             chunk/test/roundtrip_fuzz.c \
             constant_time/test/secret_flow_test.c \
             wire/test/err_str_test.c \
             version/test/version_test.c \
             chunk/test/reassembly_guided.c \
             chain/test/chain_guided.c \
             frame/test/freshness_guided.c \
             sim/test/network_test.c \
             record/test/journal_test.c \
             record/test/record_test.c \
             record/test/sync_test.c \
             state/test/state_test.c \
             trust/test/trust_test.c \
             log/test/log_test.c \
             wire/test/relay_test.c \
             sched/test/sched_test.c \
             link/test/link_test.c \
             log/test/fix_stream_test.c \
             record/test/record_guided.c \
             record/test/record_fuzz.c
TEST_OBJS := $(TEST_SRCS:%.c=$(BUILD_DIR)/%.o)
TEST_BINS := $(BUILD_DIR)/chain/test/chain_test \
             $(BUILD_DIR)/chain/test/revocation_test \
             $(BUILD_DIR)/frame/test/freshness_test \
             $(BUILD_DIR)/session/test/commitment_test \
             $(BUILD_DIR)/local/test/peer_test \
             $(BUILD_DIR)/wire/test/generated_test \
             $(BUILD_DIR)/wire/test/constants_test \
             $(BUILD_DIR)/wire/test/seal_test \
             $(BUILD_DIR)/session/test/random_test \
             $(BUILD_DIR)/local/test/vocabulary_test \
             $(BUILD_DIR)/local/test/vocabulary_fuzz \
             $(BUILD_DIR)/local/test/admit_test \
             $(BUILD_DIR)/chunk/test/agreement_test \
             $(BUILD_DIR)/local/test/peer_fuzz \
             $(BUILD_DIR)/local/test/peer_linux_test \
             $(BUILD_DIR)/chunk/test/reassembly_test \
             $(BUILD_DIR)/chunk/test/split_test \
             $(BUILD_DIR)/chunk/test/reassembly_fuzz \
             $(BUILD_DIR)/chain/test/chain_fuzz \
             $(BUILD_DIR)/frame/test/freshness_fuzz \
             $(BUILD_DIR)/frame/test/receive_fuzz \
             $(BUILD_DIR)/chain/test/revocation_fuzz \
             $(BUILD_DIR)/chunk/test/roundtrip_fuzz \
             $(BUILD_DIR)/constant_time/test/secret_flow_test \
             $(BUILD_DIR)/wire/test/err_str_test \
             $(BUILD_DIR)/version/test/version_test \
             $(BUILD_DIR)/chunk/test/reassembly_guided \
             $(BUILD_DIR)/chain/test/chain_guided \
             $(BUILD_DIR)/frame/test/freshness_guided \
             $(BUILD_DIR)/sim/test/network_test \
             $(BUILD_DIR)/record/test/journal_test \
             $(BUILD_DIR)/record/test/record_test \
             $(BUILD_DIR)/record/test/sync_test \
             $(BUILD_DIR)/state/test/state_test \
             $(BUILD_DIR)/trust/test/trust_test \
             $(BUILD_DIR)/log/test/log_test \
             $(BUILD_DIR)/wire/test/relay_test \
             $(BUILD_DIR)/sched/test/sched_test \
             $(BUILD_DIR)/link/test/link_test \
             $(BUILD_DIR)/log/test/fix_stream_test \
             $(BUILD_DIR)/record/test/record_guided \
             $(BUILD_DIR)/record/test/record_fuzz

# The Monocypher binding, built only when MONOCYPHER_DIR names a checkout.
#
# project.md sec 7 says a submodule and sec 10 has not reached that step, so
# there is nothing vendored here to build against and adding a dependency is
# not a thing to do in passing. During bring-up sec 7 blesses exactly this
# shape -- a sibling directory behind a variable, not a second build path:
#
#   make test MONOCYPHER_DIR=../fuzzypickles/monocypher
#
# Without it the library builds and every test above still runs, which is
# the property chain.h's signer vtable exists to give. With it, one more
# binary runs a real Ed25519 round trip, because a seam that has only ever
# had a stub behind it is a seam nobody has checked.
MONOCYPHER_DIR ?=

# Named OUTSIDE the conditional, because these files exist in the tree whether
# or not this build compiles them, and `make style` compares the source lists
# against what is actually there. Inside the `ifneq` they would be empty in a
# plain build and the check would report two real sources as unlisted -- a
# false finding, which is worse in a gate than no finding at all.
MONO_SRCS  := chain/sign_monocypher.c session/hash_monocypher.c \
              session/aead_monocypher.c
MONO_HDRS  := chain/sign_monocypher.h session/hash_monocypher.h \
              session/aead_monocypher.h
MONO_TSRC  := chain/test/sign_monocypher_test.c \
              session/test/hash_monocypher_test.c \
              session/test/aead_monocypher_test.c

ifneq ($(MONOCYPHER_DIR),)
MONO_OBJS  := $(BUILD_DIR)/chain/sign_monocypher.o \
              $(BUILD_DIR)/session/hash_monocypher.o \
              $(BUILD_DIR)/session/aead_monocypher.o \
              $(BUILD_DIR)/monocypher.o
MONO_TOBJ  := $(MONO_TSRC:%.c=$(BUILD_DIR)/%.o)
# Kept in TEST_SRCS as well as TEST_OBJS. Nothing was broken by its absence
# -- the objects, deps and binaries were all reached through MONO_TOBJ --
# but TEST_SRCS is the list that reads as "every test source", and one that
# is quietly incomplete is a trap for whatever asks it next. Found by asking
# it exactly that question.
TEST_SRCS  += $(MONO_TSRC)
# SRCS too, and for the same reason TEST_SRCS was fixed: it is the list that
# reads as "every library source", and `make coverage` iterates it. Without
# this the two bindings were built, linked and run by their own tests while
# the guard written to refuse an unexercised source could not see them --
# which is `GEN_SRCS` against `SRCS` a third time.
#
# It must come after OBJS is computed, which it does: OBJS took its value from
# SRCS above, and MONO_OBJS is added to it separately below, so the objects are
# named once rather than twice.
SRCS       += $(MONO_SRCS)
# What `tool/consumer_check.c` needs to exercise the bindings: the define that
# switches its optional block on, the include path, and Monocypher itself,
# since installcheck compiles sources rather than linking objects.
# Absolute, because installcheck's second arm compiles from inside
# $(BUILD_DIR)/installcheck -- which is why the SRCS beside it are put through
# $(CURDIR) as well. A relative path here builds in one arrangement and not the
# other, which is the difference the whole target exists to find.
MONO_ABS      := $(abspath $(MONOCYPHER_DIR))
MONO_CONSUMER := -DFZN_CONSUMER_MONOCYPHER -I$(MONO_ABS)/src \
                 $(MONO_ABS)/src/monocypher.c
MONO_BIN   := $(BUILD_DIR)/chain/test/sign_monocypher_test
MONO_HASH  := $(BUILD_DIR)/session/test/hash_monocypher_test
MONO_AEAD  := $(BUILD_DIR)/session/test/aead_monocypher_test
OBJS       += $(MONO_OBJS)
TEST_OBJS  += $(MONO_TOBJ)
TEST_BINS  += $(MONO_BIN) $(MONO_HASH) $(MONO_AEAD)
HDRS       += $(MONO_HDRS)
CPPFLAGS   += -I$(MONOCYPHER_DIR)/src

# Vendored, so it is compiled with its own terms rather than ours.
# code-style.md exempts vendored sources from our rules, and -Wconversion
# against somebody else's crypto is noise nobody will read, which is how a
# warning that matters gets missed.
#
# WHICH Monocypher is printed, for the reason `make schema` prints which situ:
# these tests are the only ones here whose result depends on a tree outside
# this repository, and "the AEAD round-trips" is not a claim while "it
# round-trips against Monocypher 4.0.3 at ab2b16d" is. Crypto especially --
# a patched copy at the same path is exactly the thing worth naming.
#
# Reported rather than refused, unlike situ's. Nothing is vendored FROM here,
# so a dirty tree cannot get a false provenance stamped on it; the worst case
# is a result somebody cannot reproduce, which the line below fixes.
$(BUILD_DIR)/monocypher.o: $(MONOCYPHER_DIR)/src/monocypher.c
	@mkdir -p $(dir $@)
	@if git -C "$(MONOCYPHER_DIR)" rev-parse --git-dir >/dev/null 2>&1; then \
		echo "monocypher: `git -C $(MONOCYPHER_DIR) describe --tags --always --dirty 2>/dev/null`"; \
	else \
		echo "monocypher: $(MONOCYPHER_DIR) is not a git checkout, so its version is unknown"; \
	fi
	$(CC) $(GEN_CFLAGS) -c $< -o $@

# Each names its own objects rather than linking $(MONO_OBJS) wholesale.
# Linking both bindings into both binaries would work and would hide which
# one each test actually exercises, which is the thing these tests are for.
$(MONO_BIN): $(BUILD_DIR)/chain/test/sign_monocypher_test.o \
             $(BUILD_DIR)/chain/sign_monocypher.o $(BUILD_DIR)/monocypher.o \
             $(BUILD_DIR)/chain/chain.o \
             $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The AEAD test reaches the frame path, so it links wire/seal.o and situ's
# generated objects as well -- it is the only Monocypher test that does,
# because it is the only one testing something that reads the wire.
$(BUILD_DIR)/session/test/aead_monocypher_test.o: session/test/aead_monocypher_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

# session/commitment.o for the same reason seal_test links it: wire/seal.o
# derives the commitment now instead of being handed one.
#
# AND session/hash_monocypher.o, WHICH IS THE ONE PLACE THIS FILE'S "each
# names its own objects" RULE ABOVE IS DELIBERATELY NOT FOLLOWED. That rule
# exists so a binary cannot pass on a binding it does not exercise; here the
# AEAD test genuinely exercises both, because the derivation `fzn_seal_open`
# performs is part of the frame path it is testing. A stub hash would leave
# the real AEAD running behind a fake derivation, which is the arrangement
# wire/test/seal_test.c already covers.
$(MONO_AEAD): $(BUILD_DIR)/session/test/aead_monocypher_test.o \
              $(BUILD_DIR)/session/aead_monocypher.o \
              $(BUILD_DIR)/session/hash_monocypher.o $(BUILD_DIR)/monocypher.o \
              $(BUILD_DIR)/wire/seal.o $(BUILD_DIR)/session/commitment.o \
              $(BUILD_DIR)/session/random.o \
              $(BUILD_DIR)/constant_time/constant_time.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(MONO_HASH): $(BUILD_DIR)/session/test/hash_monocypher_test.o \
              $(BUILD_DIR)/session/hash_monocypher.o $(BUILD_DIR)/monocypher.o \
              $(BUILD_DIR)/session/commitment.o \
              $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@
endif

# Every -MMD file is read back, TEST OBJECTS INCLUDED. build-and-commit.md
# names that omission specifically: a test object whose .d is never included
# does not rebuild when a header it includes changes, so a struct that gains
# a field ends up with one layout in the library and another in the binary
# linked against it -- which surfaces as a pile of nonsense assertion
# failures rather than as a build error.
DEPS := $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)

.PHONY: runtests all test fuzz guided guided-one installcheck coverage schema style codegencheck ctcheck analyze hooks clean install

# The default build does NOT build tests -- build-and-commit.md, and the
# discipline it buys is paid for by the dependency rules above being right.
all: $(OBJS)

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# GEN_EXTRA exists so `make coverage` can instrument these without their
# warning flags becoming ours. Without it the coverage target reported all
# three as exercised by nothing, which was false -- generated_test drives
# them -- and a false positive from a guard is worth no more than the false
# negative it replaced.
GEN_EXTRA ?=

$(BUILD_DIR)/wire/generated/%.o: wire/generated/%.c
	@mkdir -p $(dir $@)
	$(CC) $(GEN_CFLAGS) -Iwire/generated -MMD -MP -c $< -o $@

$(BUILD_DIR)/chain/test/chain_test: $(BUILD_DIR)/chain/test/chain_test.o \
                                     $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# record.o is here because a record is now a VIEW over its own encoding: the
# harness builds every record through fzn_record_sign and reads it back with
# fzn_record_open, so the module is linked rather than merely included.
$(BUILD_DIR)/record/test/record_guided: $(BUILD_DIR)/record/test/record_guided.o \
                                        $(BUILD_DIR)/record/record.o \
                                        $(BUILD_DIR)/record/journal.o \
                                        $(BUILD_DIR)/state/state.o \
                                        $(BUILD_DIR)/log/log.o \
                                        $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/log/test/fix_stream_test: $(BUILD_DIR)/log/test/fix_stream_test.o \
                                       $(BUILD_DIR)/log/log.o \
                                       $(BUILD_DIR)/record/record.o \
                                       $(BUILD_DIR)/record/journal.o \
                                       $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/link/test/link_test: $(BUILD_DIR)/link/test/link_test.o \
                                  $(BUILD_DIR)/link/link.o \
                                  $(BUILD_DIR)/sched/sched.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/sched/test/sched_test: $(BUILD_DIR)/sched/test/sched_test.o \
                                    $(BUILD_DIR)/sched/sched.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/wire/test/relay_test: $(BUILD_DIR)/wire/test/relay_test.o \
                                   $(BUILD_DIR)/wire/relay.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# `log/` LINKS THE JOURNAL NOW, and every binary that uses `fzn_log_get` must.
# The GONE answer is read out of `fzn_journal_next` rather than out of what the
# log still holds -- see log.h -- so a link line that lists log.o without
# journal.o does not fail to answer, it fails to link, which is the direction
# this build wants a missed dependency to fail in.
$(BUILD_DIR)/log/test/log_test: $(BUILD_DIR)/log/test/log_test.o \
                                $(BUILD_DIR)/log/log.o \
                                $(BUILD_DIR)/record/record.o \
                                $(BUILD_DIR)/record/journal.o \
                                $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/trust/test/trust_test: $(BUILD_DIR)/trust/test/trust_test.o \
                                    $(BUILD_DIR)/trust/trust.o \
                                    $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/state/test/state_test: $(BUILD_DIR)/state/test/state_test.o \
                                    $(BUILD_DIR)/state/state.o \
                                    $(BUILD_DIR)/record/record.o \
                                    $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/record/test/sync_test: $(BUILD_DIR)/record/test/sync_test.o \
                                    $(BUILD_DIR)/record/sync.o \
                                    $(BUILD_DIR)/record/journal.o \
                                    $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/record/test/record_test: $(BUILD_DIR)/record/test/record_test.o \
                                      $(BUILD_DIR)/record/record.o \
                                      $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The byte-level fuzz harness for the same module record_test.c covers with
# named cases. It links record.o alone: nothing above `record/` is on trial
# here, which is what separates it from record_guided.c next door.
$(BUILD_DIR)/record/test/record_fuzz: $(BUILD_DIR)/record/test/record_fuzz.o \
                                      $(BUILD_DIR)/record/record.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/record/test/journal_test: $(BUILD_DIR)/record/test/journal_test.o \
                                       $(BUILD_DIR)/record/journal.o \
                                       $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The whole library at once. Its own rule rather than a pattern, because it
# links nearly everything and the list is the point: a module absent here is a
# module the integration test cannot exercise.
$(BUILD_DIR)/sim/test/network_test: $(BUILD_DIR)/sim/test/network_test.o \
                                    $(BUILD_DIR)/trust/trust.o \
                                    $(BUILD_DIR)/state/state.o \
                                    $(BUILD_DIR)/record/record.o \
                                    $(BUILD_DIR)/record/journal.o \
                                    $(BUILD_DIR)/record/sync.o \
                                    $(BUILD_DIR)/chain/chain.o \
                                    $(BUILD_DIR)/chain/revocation.o \
                                    $(BUILD_DIR)/chunk/reassembly.o \
                                    $(BUILD_DIR)/chunk/split.o \
                                    $(BUILD_DIR)/frame/freshness.o \
                                    $(BUILD_DIR)/session/commitment.o \
                                    $(BUILD_DIR)/session/random.o \
                                    $(BUILD_DIR)/version/version.o \
                                    $(BUILD_DIR)/wire/seal.o \
                                    $(BUILD_DIR)/constant_time/constant_time.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/frame/test/freshness_guided: \
                     $(BUILD_DIR)/frame/test/freshness_guided.o \
                     $(BUILD_DIR)/frame/freshness.o \
                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/test/chain_guided: $(BUILD_DIR)/chain/test/chain_guided.o \
                                      $(BUILD_DIR)/chain/chain.o \
                                      $(BUILD_DIR)/chain/revocation.o \
                                      $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chunk/test/reassembly_guided: \
                     $(BUILD_DIR)/chunk/test/reassembly_guided.o \
                     $(BUILD_DIR)/chunk/reassembly.o \
                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/version/test/version_test: $(BUILD_DIR)/version/test/version_test.o \
                                        $(BUILD_DIR)/version/version.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/constant_time/test/secret_flow_test: \
                     $(BUILD_DIR)/constant_time/test/secret_flow_test.o \
                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/frame/test/freshness_test: $(BUILD_DIR)/frame/test/freshness_test.o \
                                         $(BUILD_DIR)/frame/freshness.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chunk/test/reassembly_test: $(BUILD_DIR)/chunk/test/reassembly_test.o \
                                          $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links BOTH halves on purpose: this binary is what holds the splitter and
# the reassembler to the same contract.
$(BUILD_DIR)/chunk/test/split_test: $(BUILD_DIR)/chunk/test/split_test.o \
                                     $(BUILD_DIR)/chunk/split.o \
                                     $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/test/revocation_test: $(BUILD_DIR)/chain/test/revocation_test.o \
                                          $(BUILD_DIR)/chain/revocation.o \
                                          $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The fuzz harness. It runs a FIXED number of cases from a seeded generator
# -- argv[1] or its own default -- so `make test` terminates and a failing
# case is reproducible from the source alone. `make fuzz CASES=n` runs a
# longer campaign without editing anything.
$(BUILD_DIR)/chunk/test/reassembly_fuzz: $(BUILD_DIR)/chunk/test/reassembly_fuzz.o \
                                          $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/test/chain_fuzz: $(BUILD_DIR)/chain/test/chain_fuzz.o \
                                     $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The only binary that links four modules, because it is the only one testing
# something none of them owns: the ORDER sec 4.7 puts them in.
$(BUILD_DIR)/frame/test/receive_fuzz: $(BUILD_DIR)/frame/test/receive_fuzz.o \
                                       $(BUILD_DIR)/frame/freshness.o \
                                       $(BUILD_DIR)/chain/chain.o \
                                       $(BUILD_DIR)/chain/revocation.o \
                                       $(BUILD_DIR)/chunk/reassembly.o \
                                       $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/frame/test/freshness_fuzz: $(BUILD_DIR)/frame/test/freshness_fuzz.o \
                                         $(BUILD_DIR)/frame/freshness.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/test/revocation_fuzz: $(BUILD_DIR)/chain/test/revocation_fuzz.o \
                                          $(BUILD_DIR)/chain/revocation.o \
                                          $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links both halves, like split_test: this binary is what holds the
# splitter and the reassembler to the same contract over permutations.
$(BUILD_DIR)/chunk/test/roundtrip_fuzz: $(BUILD_DIR)/chunk/test/roundtrip_fuzz.o \
                                         $(BUILD_DIR)/chunk/split.o \
                                         $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/session/test/commitment_test: \
		$(BUILD_DIR)/session/test/commitment_test.o \
		$(BUILD_DIR)/session/commitment.o \
		$(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links peer.c only. peer_linux.c is the system half and holds no
# decisions, so the suite drives every one of them without a socket.
$(BUILD_DIR)/local/test/peer_test: $(BUILD_DIR)/local/test/peer_test.o \
                                    $(BUILD_DIR)/local/peer.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/local/test/peer_fuzz: $(BUILD_DIR)/local/test/peer_fuzz.o \
                                    $(BUILD_DIR)/local/peer.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The one test that links the system half. It needs no cooperating
# process: a socketpair has both ends here, so SO_PEERCRED reports us.
$(BUILD_DIR)/local/test/peer_linux_test: $(BUILD_DIR)/local/test/peer_linux_test.o \
                                          $(BUILD_DIR)/local/peer.o \
                                          $(BUILD_DIR)/local/peer_linux.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Three tests read situ's output and need the generated include path, so each
# has its own compile rule rather than the pattern's. This comment said "the
# only test" until there were three of them.
$(BUILD_DIR)/wire/test/generated_test.o: wire/test/generated_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/wire/test/constants_test.o: wire/test/constants_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

# Links peer and vocabulary, which is the seam it tests. It linked four
# modules until local/line.c and local/socket.c moved to raidcfgd.
$(BUILD_DIR)/local/test/admit_test: $(BUILD_DIR)/local/test/admit_test.o \
                                     $(BUILD_DIR)/local/peer.o \
                                     $(BUILD_DIR)/local/peer_linux.o \
                                     $(BUILD_DIR)/local/vocabulary.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/local/test/vocabulary_fuzz: $(BUILD_DIR)/local/test/vocabulary_fuzz.o \
                                          $(BUILD_DIR)/local/vocabulary.o \
                                          $(BUILD_DIR)/local/peer.o \
                                          $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/local/test/vocabulary_test: $(BUILD_DIR)/local/test/vocabulary_test.o \
                                          $(BUILD_DIR)/local/vocabulary.o \
                                          $(BUILD_DIR)/local/peer.o \
                                          $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/session/test/random_test: $(BUILD_DIR)/session/test/random_test.o \
                                        $(BUILD_DIR)/session/random.o \
                                        $(BUILD_DIR)/session/random_linux.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/wire/seal.o: wire/seal.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

# Same reason as seal.o: it reads the hop header through the generated
# accessors, so it needs the generated headers on its include path.
$(BUILD_DIR)/wire/relay.o: wire/relay.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/wire/test/relay_test.o: wire/test/relay_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -MMD -MP -c $< -o $@

$(BUILD_DIR)/wire/test/seal_test.o: wire/test/seal_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/wire/test/err_str_test: $(BUILD_DIR)/wire/test/err_str_test.o \
                                      $(BUILD_DIR)/record/record.o \
                                      $(BUILD_DIR)/record/journal.o \
                                      $(BUILD_DIR)/record/sync.o \
                                      $(BUILD_DIR)/state/state.o \
                                      $(BUILD_DIR)/trust/trust.o \
                                      $(BUILD_DIR)/log/log.o \
                                      $(BUILD_DIR)/wire/relay.o \
                                      $(BUILD_DIR)/sched/sched.o \
                                      $(BUILD_DIR)/link/link.o \
                                      $(BUILD_DIR)/chain/chain.o \
                                      $(BUILD_DIR)/chunk/reassembly.o \
                                      $(BUILD_DIR)/chunk/split.o \
                                      $(BUILD_DIR)/frame/freshness.o \
                                      $(BUILD_DIR)/local/peer.o \
                                      $(BUILD_DIR)/session/commitment.o \
                                      $(BUILD_DIR)/session/random.o \
                                      $(BUILD_DIR)/wire/seal.o \
                                      $(BUILD_DIR)/constant_time/constant_time.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# LINKS relay.o, WHICH IT DID NOT UNTIL THE ROUND TRIP EXISTED. Sealing and
# relaying were tested in separate binaries, so nothing anywhere asserted that a
# frame survives being relayed -- the one property `wire/relay.h` is built on.
# seal_test now spends the whole hop budget between build and open, which needs
# both halves in one process.
# AND commitment.o, WHICH IT DID NOT NEED WHILE THE COMMITMENT WAS AN
# ARGUMENT. `fzn_seal_open` and `fzn_seal_build` derive the frame's commitment
# themselves now -- it depends on the nonce, which the build path draws and the
# open path reads out of the frame, so no caller can hand one in -- and that
# makes session/commitment.o a link-time dependency of wire/seal.o rather than
# of its callers.
$(BUILD_DIR)/wire/test/seal_test: $(BUILD_DIR)/wire/test/seal_test.o \
                                   $(BUILD_DIR)/wire/seal.o $(BUILD_DIR)/wire/relay.o \
                                   $(BUILD_DIR)/session/commitment.o \
                                   $(BUILD_DIR)/session/random.o \
                                   $(BUILD_DIR)/constant_time/constant_time.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links the generated runtime for the frame views its runtime half needs;
# every other check in it is a static assert and needs no object at all.
$(BUILD_DIR)/wire/test/constants_test: $(BUILD_DIR)/wire/test/constants_test.o \
                                        $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/wire/test/generated_test: $(BUILD_DIR)/wire/test/generated_test.o \
                                        $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links situ's output AND our reassembler, which is the only binary that
# does. It exists to compare the two implementations of one rule.
$(BUILD_DIR)/chunk/test/agreement_test.o: chunk/test/agreement_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/chunk/test/agreement_test: $(BUILD_DIR)/chunk/test/agreement_test.o \
                                         $(BUILD_DIR)/chunk/reassembly.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Tests are built by this target and only by it, so a claim that a test
# passes or fails always goes through a rebuild. Re-running a stale binary
# after a plain build appears to pass either way.
# ctcheck runs first because it is about the library rather than the tests, and
# because a failure there is more interesting than any assertion below it.
test: codegencheck runtests

# The suite without the codegen gate, which exists for ONE caller.
#
# `coverage` builds this tree with `--coverage`, and that instrumentation
# adds counters to every basic block -- so `codegen_gate.py`, which reads a
# disassembly and pins the shape of the constant-time primitives and the
# wipe, cannot pass and never could. `make coverage` has therefore been
# failing for as long as the gate has existed, with the tripwire's own
# "read the disassembly and decide" message on the way out. Nobody could
# re-measure a coverage figure, which is why several in `project.md` named
# a total from before the binary grew.
#
# THE GATE IS NOT WEAKENED, and skipping it here is not a relaxation: its
# subject is the code this library SHIPS, and an instrumented build is not
# that code. Making it pass under `--coverage` would mean teaching it to
# accept a shape we never ship, which is the direction `evidence.md` warns
# about -- bending the world around a check rather than asking what the
# check can be right about. `test` still runs it first, which is where it
# belongs.
runtests: $(TEST_BINS)
	@for t in $(TEST_BINS); do echo "running $$t"; $$t || exit 1; done
	@# SAY WHEN THE MONOCYPHER BINDINGS WERE NOT BUILT, rather than leaving
	@# their absence to look like their success. Without MONOCYPHER_DIR the
	@# three bindings are not compiled at all, and a run that never mentions
	@# them reads exactly like a run in which they passed. Same discipline
	@# as `analyze` and `ctcheck`, which skip loudly for the same reason.
	@#
	@# NO CHECK COUNT HERE, DELIBERATELY, AND IT USED TO SAY 43. The
	@# bindings carried 70 by then and carry more now; nobody noticed
	@# because a number in a comment is maintained by whoever remembers it
	@# exists. It was corrected once and would have drifted again -- the
	@# only figure that cannot is one taken at run time, and this target
	@# cannot take one for binaries it did not build. So the notice states
	@# what it can know: three bindings, not compiled. The count belongs to
	@# the gated run, which prints its own.
	@#
	@# The same trap then caught a REPORT about this comment, one commit
	@# later: a total measured correctly and quoted three commits after it
	@# was true. project.md sec 11 carries that incident, under the rule it
	@# produced -- a number is measured at the moment it is quoted, or it is
	@# not measured.
	@#
	@# Found by mutation: FZN_SECRET_KEY_LEN could be changed in either
	@# direction with the whole suite still green, because the module
	@# declaring it is dark in a default build.
	@if [ -z "$(MONOCYPHER_DIR)" ]; then \
		echo "test: the Monocypher bindings were NOT built, so their tests did"; \
		echo "test: not run. Pass MONOCYPHER_DIR=<checkout> to include them."; \
	fi

CASES ?= 200000

FUZZ_BINS := $(BUILD_DIR)/chunk/test/reassembly_fuzz \
             $(BUILD_DIR)/chain/test/chain_fuzz \
             $(BUILD_DIR)/frame/test/freshness_fuzz \
             $(BUILD_DIR)/frame/test/receive_fuzz \
             $(BUILD_DIR)/chain/test/revocation_fuzz \
             $(BUILD_DIR)/chunk/test/roundtrip_fuzz \
             $(BUILD_DIR)/local/test/peer_fuzz \
             $(BUILD_DIR)/local/test/vocabulary_fuzz \
             $(BUILD_DIR)/record/test/record_fuzz

fuzz: $(FUZZ_BINS)
	@for f in $(FUZZ_BINS); do echo "== $$f $(CASES)"; $$f $(CASES) || exit 1; done

# Not bare. A bare `.SECONDARY:` applies to every target matched by any
# pattern rule, silently including the object pattern above, and make does
# not rebuild a MISSING secondary when the thing depending on it already
# exists -- so adding a source would leave the build unchanged and every
# symbol in it undefined at link time. It exists to stop test objects being
# deleted as intermediates, so it names exactly those.
.SECONDARY: $(TEST_OBJS)

# The indentation, whitespace and ASCII gate. One tool, spread verbatim from
# ~/.claude/tool/style_gate.py; .style-gate.toml says which files here it
# applies to.
# TWO SECURITY PROPERTIES THE OPTIMISER COULD TAKE AWAY, each measured once by
# hand and then left in a comment. See tool/codegen_gate.py for what it does
# and does not claim -- it pins the shape each function compiles to so that a
# change stops the build, which is a tripwire rather than a proof. Skips loudly
# off x86-64 and without objdump; refuses if it cannot find a function, since
# that is indistinguishable from checking nothing.
#
# Named one per line rather than looped, because the pair is the point: a
# check added here should be a deliberate line somebody wrote.
codegencheck: $(BUILD_DIR)/constant_time/constant_time.o \
              $(BUILD_DIR)/session/commitment.o
	python3 tool/codegen_gate.py ct $(BUILD_DIR)/constant_time/constant_time.o
	python3 tool/codegen_gate.py wipe $(BUILD_DIR)/session/commitment.o

# COVERAGE-GUIDED FUZZING, which is a different instrument from `fuzz`.
#
# `fuzz` runs the model-based harnesses: a PRNG generates chunk sequences and
# a model says what should have happened. That finds what the generator was
# written to reach. libFuzzer keeps inputs that reach new edges and mutates
# those, so it walks into states nobody described in advance.
#
# GUIDED_TIME is per harness and defaults low enough to be worth running
# before a commit. A real campaign is `make guided GUIDED_TIME=600`.
#
# The corpus is NOT committed. It is tens of thousands of bytes of machine-
# generated input whose value is local and perishable, and a crash worth
# keeping goes into the harness as a named byte string instead -- where it is
# reviewable and runs under plain `make test`.
#
# Skips loudly without a clang that has libFuzzer, on the same reasoning as
# `analyze` and `ctcheck`: an absent tool and a clean run are otherwise the
# same silence.
#
# First campaign 2026-08-26: 1.5M executions over chunk/reassembly.c under the
# address and undefined sanitizers, 209 of 400 edges, 292 corpus units, no
# crash. The local/ parsers were run the same way from a scratch harness:
# 15.3M executions, coverage 2 -> 82, no crash.
GUIDED_TIME ?= 60
GUIDED_DIR  ?= $(BUILD_DIR)/guided

guided:
	@if ! echo 'int LLVMFuzzerTestOneInput(const unsigned char*d,unsigned long s){(void)d;(void)s;return 0;}' \
	      | clang -fsanitize=fuzzer -x c - -o /dev/null 2>/dev/null; then \
		echo "guided: no clang with libFuzzer, so it was SKIPPED"; exit 0; \
	fi
	@# Named one per line rather than discovered, so that adding a harness
	@# here is a deliberate act and the sources each one needs are visible.
	@$(MAKE) --no-print-directory guided-one GUIDED_NAME=reassembly \
	        GUIDED_SRC="chunk/test/reassembly_guided.c chunk/reassembly.c \
	                    constant_time/constant_time.c"
	@$(MAKE) --no-print-directory guided-one GUIDED_NAME=chain \
	        GUIDED_SRC="chain/test/chain_guided.c chain/chain.c chain/revocation.c \
	                    constant_time/constant_time.c"
	@$(MAKE) --no-print-directory guided-one GUIDED_NAME=record \
	        GUIDED_SRC="record/test/record_guided.c record/record.c record/journal.c \
	                    state/state.c log/log.c constant_time/constant_time.c"
	@$(MAKE) --no-print-directory guided-one GUIDED_NAME=freshness \
	        GUIDED_SRC="frame/test/freshness_guided.c frame/freshness.c \
	                    constant_time/constant_time.c"

# The least coverage a guided run may report and still be believed. A harness
# that returns on its first line reports 1; the real ones report 112 to 209
# after ten seconds. Twenty is far below every real harness and far above the
# vacuous case, which is what a tripwire wants to be.
GUIDED_COV_MIN ?= 20

guided-one:
	@mkdir -p $(GUIDED_DIR)/$(GUIDED_NAME)
	@clang -O1 -g -fsanitize=fuzzer,address,undefined -DFZN_LIBFUZZER \
	       -o $(GUIDED_DIR)/$(GUIDED_NAME)/fuzz $(GUIDED_SRC)
	@echo "guided: $(GUIDED_NAME) for $(GUIDED_TIME)s"
	@# THE FUZZER'S EXIT STATUS IS READ, and until now it was thrown away.
	@#
	@# This line used to pipe the run into `grep -E "INITED|DONE|ERROR|SUMMARY"`,
	@# so the recipe's status was GREP's. libFuzzer exits non-zero when it finds
	@# a crash and prints "ERROR: libFuzzer: deadly signal" -- which grep matched,
	@# and so reported success. Measured: a harness that traps on the input "AB"
	@# produced a crash artifact, printed the error, and `make guided` exited 0.
	@#
	@# A coverage-guided fuzzer that cannot report a crash is the one instrument
	@# here whose entire purpose is finding them. The old comment on the line
	@# above -- "read the coverage, not the exit code" -- was an instruction to
	@# the person watching, standing in for a check nobody had written.
	@#
	@# Redirected to a file rather than piped, because `pipefail` is not in
	@# POSIX sh and make's shell is not guaranteed to have it.
	@# Paths below are relative BECAUSE OF THE `cd`. The first version of this
	@# kept the $(GUIDED_DIR)/$(GUIDED_NAME) prefix after changing into that
	@# directory, so every path resolved one level too deep, `cat` found no
	@# status file, and the exit-status test silently did nothing. A crashing
	@# harness was still caught -- by the coverage check below, which is a
	@# different check answering a different question. The check written for
	@# crashes had to be watched failing to fire to be found.
	@cd $(GUIDED_DIR)/$(GUIDED_NAME) && \
	    { ./fuzz . -max_total_time=$(GUIDED_TIME) -rss_limit_mb=2048 -max_len=4096 \
	        > run.log 2>&1; echo $$? > run.status; }; \
	    grep -E "INITED|DONE|ERROR|SUMMARY" run.log || true; \
	    rc=`cat run.status`; \
	    if [ "$$rc" -ne 0 ]; then \
	        echo "guided: $(GUIDED_NAME) FAILED -- the fuzzer exited $$rc."; \
	        echo "guided: a crash artifact is in $(GUIDED_DIR)/$(GUIDED_NAME)/."; \
	        exit 1; \
	    fi
	@# AND THE COVERAGE IS READ, not merely printed.
	@#
	@# libFuzzer reports `cov: N` on its INITED and DONE lines. The check is
	@# an ABSOLUTE FLOOR rather than growth, and the distinction matters: the
	@# corpus directory persists between runs, so a saturated corpus
	@# legitimately finds nothing new and a growth test would fail an honest
	@# re-run. What must never pass is a harness that reached NOTHING, and
	@# that is what a floor detects. Measured: a harness whose body is
	@# `return 0` reports cov 1; the four real harnesses report 112 to 209.
	@#
	@# A missing number is a failure too. A grep that matches nothing is not a
	@# check that passed -- which is the same mistake the piped `grep` above
	@# was making with the exit status.
	@d=`grep -o 'DONE *cov: [0-9]*' $(GUIDED_DIR)/$(GUIDED_NAME)/run.log | \
	     tail -1 | tr -dc '0-9'`; \
	if [ -z "$$d" ]; then \
		echo "guided: $(GUIDED_NAME) -- no DONE coverage line, so nothing was checked."; \
		echo "guided: the run did not finish, or libFuzzer changed its output."; \
		exit 1; \
	fi; \
	if [ "$$d" -lt "$(GUIDED_COV_MIN)" ]; then \
		echo "guided: $(GUIDED_NAME) reached cov $$d, below the floor of $(GUIDED_COV_MIN)."; \
		echo "guided: the harness is not reaching the code it is meant to drive."; \
		exit 1; \
	fi; \
	echo "guided: $(GUIDED_NAME) reached cov $$d"
	@# A CORPUS THAT DID NOT GROW MEANS THE HARNESS RETURNED EARLY, which is
	@# how the first version of this reported 61 million clean executions
	@# while every one of them bailed on its first line. The check is that
	@# the run kept more than the one unit libFuzzer starts with.
	@n=`ls $(GUIDED_DIR)/$(GUIDED_NAME) | grep -c '^[0-9a-f]\{40\}$$' || true`; \
	if [ "$$n" -lt 2 ]; then \
		echo "guided: $(GUIDED_NAME) kept $$n corpus unit(s) -- it is not reaching the code"; \
		echo "guided: a run that grows no corpus is not evidence of anything."; \
		exit 1; \
	fi; \
	echo "guided: $(GUIDED_NAME) kept $$n corpus units, so the search was real"

# IS THE CONSTANT-TIME COMPARISON ACTUALLY CONSTANT-TIME?
#
# `codegencheck` above counts branches in an object file, and
# tool/codegen_gate.py is explicit that this is "a tripwire rather than a
# proof". This asks the question directly: memcheck tracks definedness per
# bit and reports any conditional jump or memory address computed from data
# it considers undefined, so marking the two buffers undefined turns valgrind
# into a secret-dependence detector. Langley's ctgrind.
#
# IT RUNS THE BINARY TWICE ON PURPOSE. A memcheck that reports nothing and a
# memcheck that was never able to report anything look identical -- the build
# lost -DFZN_HAVE_VALGRIND, the binary was stale, valgrind ran something
# else. So the second run swaps in memcmp over the same poisoned buffers and
# this target FAILS IF THAT IS NOT REPORTED. The clean run means something
# only because the dirty one was seen.
#
# Not in `test`: valgrind is not on every machine, and it skips loudly rather
# than passing, since an absent tool and a clean one are otherwise the same
# silence.
CT_VG_BIN := $(BUILD_DIR)/constant_time/test/secret_flow_valgrind

ctcheck:
	@if ! command -v valgrind >/dev/null 2>&1; then \
		echo "ctcheck: no valgrind on PATH, so it was SKIPPED"; exit 0; \
	elif [ ! -f /usr/include/valgrind/memcheck.h ]; then \
		echo "ctcheck: valgrind headers absent, so it was SKIPPED"; exit 0; \
	else \
		mkdir -p $(dir $(CT_VG_BIN)) && \
		$(CC) $(CFLAGS) -DFZN_HAVE_VALGRIND -o $(CT_VG_BIN) \
		      constant_time/test/secret_flow_test.c constant_time/constant_time.c && \
		echo "ctcheck: fzn_ct_memeq, with both inputs marked secret" && \
		valgrind -q --error-exitcode=9 --track-origins=yes $(CT_VG_BIN) || \
			{ echo "ctcheck: FAILED -- control flow depended on secret data"; exit 1; }; \
		echo "ctcheck: positive control -- memcmp over the same secrets" && \
		if valgrind -q --error-exitcode=9 $(CT_VG_BIN) --leaky >/dev/null 2>&1; then \
			echo "ctcheck: FAILED -- memcmp over secret data was NOT reported."; \
			echo "ctcheck: the clean run above therefore proves nothing."; exit 1; \
		fi; \
		echo "ctcheck: reported, so the clean run above is evidence and not silence"; \
	fi

# STATIC ANALYSIS, from two tools that disagree about what to look for.
#
# Neither is in `test`, because both are slow and neither is a gate this
# project owns -- a new compiler release inventing a finding would break a
# build that changed nothing, which is the argument that keeps -Werror out
# too. Run deliberately, and read.
#
# Both skip loudly when absent rather than passing, since a missing analyser
# and a clean one produce the same silence otherwise.
#
# First run 2026-08-20: zero findings from either, over the library and the
# tests. Recorded in project.md as a result rather than a habit -- what makes
# it worth anything is that it had never been run at all.
analyze:
	@if $(CC) -fanalyzer -x c /dev/null -o /dev/null -c 2>/dev/null; then \
		echo "analyze: gcc -fanalyzer over the library and the tests"; \
		$(MAKE) --no-print-directory test BUILD_DIR=$(BUILD_DIR)-analyze \
		        CFLAGS="-Os -g -fanalyzer" 2>&1 | grep -E "Wanalyzer" || true; \
		rm -rf $(BUILD_DIR)-analyze; \
	else \
		echo "analyze: this compiler has no -fanalyzer, so it was SKIPPED"; \
	fi
	@if command -v cppcheck >/dev/null 2>&1; then \
		echo "analyze: cppcheck --check-level=exhaustive over the library"; \
		cppcheck --enable=warning,performance,portability \
		         --check-level=exhaustive --inline-suppr \
		         --suppress=missingIncludeSystem --quiet -I. $(SRCS) 2>&1 \
		         | grep -vE "normalCheckLevel" || true; \
	else \
		echo "analyze: no cppcheck on PATH, so it was SKIPPED"; \
	fi
	@echo "analyze: done -- read the output above; this target reports and does not gate"

style:
	python3 tool/style_gate.py check
	@# EVERY .c IN THE TREE MUST BE IN A LIST -- the fourth instance of one
	@# pattern and the last that was not mechanically checked. HDRS against
	@# `install`, GEN_SRCS against `coverage`, TEST_BINS against .gitignore,
	@# and SRCS against the tree: each is a list kept by hand, and each guard
	@# is only as wide as the list it iterates. The first three are compared
	@# against another list. This one has no second list, so it is compared
	@# against the filesystem.
	@#
	@# It is what would have caught the Monocypher bindings, which were in the
	@# tree, built, linked and run, and in no list `make coverage` reads.
	@# `.claude/` IS PRUNED FROM EVERY SWEEP BELOW, along with the build
	@# directories. It holds tooling configuration rather than project
	@# content -- and, when more than one agent is working in this tree, git
	@# worktrees under `.claude/worktrees/`, each a full checkout. Without
	@# the prune every sweep here reports several hundred copies of the same
	@# files as unlisted, which is a gate that has stopped saying anything.
	@known=" $(SRCS) $(TEST_SRCS) $(GEN_SRCS) $(MONO_SRCS) $(MONO_TSRC) tool/consumer_check.c "; \
	unlisted=; n=0; \
	for c in `find . -name '*.c' -not -path './build/*' -not -path './san/*' \
	                 -not -path './*-coverage/*' -not -path './.claude/*' \
	                 | sed 's|^\./||' | sort`; do \
		n=$$((n + 1)); \
		case "$$known" in *" $$c "*) ;; *) unlisted="$$unlisted $$c" ;; esac; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no C sources found, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$unlisted" ]; then \
		echo "style: C sources in the tree and in no list:$$unlisted"; \
		echo "style: nothing reading SRCS -- coverage, installcheck -- can see them."; \
		exit 1; \
	fi; \
	echo "style: $$n C sources, all named in a list"
	@# AND EVERY FUZZ HARNESS MUST BE IN FUZZ_BINS, a fifth hand-maintained
	@# list and the one still unchecked.
	@#
	@# vocabulary_fuzz.c was in TEST_SRCS and TEST_BINS, so `make test` ran
	@# it at the default case count, and absent from FUZZ_BINS, so `make
	@# fuzz CASES=2000000` never touched it. The deep campaign is the one
	@# place that omission costs anything, and nothing said so: the suite
	@# was green either way.
	@#
	@# `*_fuzz.c` is the convention every harness here follows, so the
	@# filesystem is asked directly rather than compared against another
	@# list somebody also maintains.
	@missing=; n=0; \
	listed=; \
	for b in $(FUZZ_BINS); do listed="$$listed $${b#$(BUILD_DIR)/}"; done; \
	for f in `find . -name '*_fuzz.c' -not -path './build/*' -not -path './san/*' \
	                 -not -path './*-coverage/*' -not -path './.claude/*' \
	                 | sed 's|^\./||' | sort`; do \
		n=$$((n + 1)); \
		bin=`echo "$$f" | sed 's/\.c$$//'`; \
		case " $$listed " in *" $$bin "*) ;; *) missing="$$missing $$bin" ;; esac; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no fuzz harnesses found, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$missing" ]; then \
		echo "style: fuzz harnesses not in FUZZ_BINS:$$missing"; \
		echo "style: 'make fuzz' would never run them, whatever CASES said."; \
		exit 1; \
	fi; \
	echo "style: $$n fuzz harnesses, all in FUZZ_BINS"
	@# THE THIRD HAND-MAINTAINED LIST, and the third time one has drifted.
	@# .gitignore names each test binary rather than globbing them, for a
	@# stated reason: a pattern would also hide a source file added under
	@# that name by mistake. The cost is a line per test, and forgetting it
	@# leaves a build product in `git status` -- which matters here because
	@# the rule against blanket `git add` depends on that output being
	@# trustworthy. Noise trains people to stop reading it.
	@#
	@# HDRS versus `install` and GEN_SRCS versus `coverage` were the first
	@# two, and both were found by something breaking rather than by
	@# anybody comparing the lists. So this compares them.
	@#
	@# BUILD_DIR IS STRIPPED RATHER THAN SKIPPED ON. Both this check and the
	@# FUZZ_BINS one above used to refuse to run unless BUILD_DIR was the
	@# in-place default, on the reasoning that the paths would not match --
	@# but the prefix is incidental to what they compare, which is list
	@# membership. Stripping it makes them answer in every configuration,
	@# and a check that skips for anybody who habitually builds out of tree
	@# is a check those people do not have.
	@missing=; n=0; \
	for b in $(TEST_BINS); do \
		n=$$((n + 1)); \
		p=$${b#$(BUILD_DIR)/}; \
		grep -qx -- "/$$p" .gitignore || missing="$$missing $$p"; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no test binaries to check, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$missing" ]; then \
		echo "style: test binaries missing from .gitignore:$$missing"; exit 1; \
	fi; \
	echo "style: $$n test binaries all named in .gitignore"
	@# AND EVERY HEADER MUST BE IN HDRS, which is the sixth pairing and the
	@# one still open. installcheck already refuses when an HDRS entry is
	@# not exercised by the consumer check; nothing looked the other way,
	@# and a header in the tree that HDRS does not name is one `make
	@# install` never ships -- which surfaces as a consumer's include
	@# failing on a machine that is not this one.
	@#
	@# MONO_HDRS is unioned in because HDRS gains it only when
	@# MONOCYPHER_DIR is set, exactly as MONO_SRCS is unioned into the C
	@# source check above. Generated headers are situ's and tool/ is not
	@# installed, so both are excluded rather than listed.
	@known=" $(HDRS) $(MONO_HDRS) "; missing=; n=0; \
	for h in `find . -name '*.h' -not -path './.git/*' -not -path './.claude/*' \
	                 -not -path './wire/generated/*' -not -path './tool/*' \
	                 -not -path './build/*' -not -path './san/*' \
	                 -not -path './*-coverage/*' | sed 's|^\./||' | sort`; do \
		n=$$((n + 1)); \
		case "$$known" in *" $$h "*) ;; *) missing="$$missing $$h" ;; esac; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no headers found, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$missing" ]; then \
		echo "style: headers in the tree and not in HDRS:$$missing"; \
		echo "style: 'make install' would not ship them."; \
		exit 1; \
	fi; \
	echo "style: $$n headers, all named in HDRS"
	@# AND EVERY TEST SOURCE MUST PRODUCE A BINARY `make test` RUNS.
	@#
	@# TEST_SRCS is what gets compiled and dependency-tracked; TEST_BINS is
	@# what `test:` iterates. A source in the first and not the second
	@# builds cleanly and never runs -- and that is not hypothetical, it is
	@# what happened to local/test/vocabulary_fuzz.c one list over, which
	@# sat in TEST_SRCS and TEST_BINS but not FUZZ_BINS and so was never
	@# reached by the deep campaign. The same slip here costs a test that
	@# never runs at all, which is worse and just as quiet.
	@#
	@# The SRCS-against-the-tree check above does not cover it: a source in
	@# TEST_SRCS is in a list, which is all that one asks.
	@srcs=`for f in $(TEST_SRCS); do echo "$${f%.c}"; done | sort -u`; \
	bins=`for b in $(TEST_BINS); do echo "$${b#$(BUILD_DIR)/}"; done | sort -u`; \
	n=`echo "$$srcs" | grep -c .`; \
	missing=; \
	for t in $$srcs; do \
		case " `echo $$bins` " in *" $$t "*) ;; *) missing="$$missing $$t" ;; esac; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no test sources found, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$missing" ]; then \
		echo "style: test sources that build but never run:$$missing"; \
		echo "style: they are in TEST_SRCS and not in TEST_BINS."; \
		exit 1; \
	fi; \
	echo "style: $$n test sources, all reached by 'make test'"
	@# AND version/version.h MUST STILL SPELL WHAT VERSION SAYS, an eighth
	@# hand-maintained agreement. The header is a copy on purpose --
	@# version.h says why, and it is the reason constants_test.c gives about
	@# the field lengths: a generated header would put a build step between a
	@# consumer and a constant. What was missing there and here is anything
	@# to notice when a copy stops being one.
	@#
	@# The packing bound is checked too. At a minor or patch of 100 the
	@# arithmetic carries and 0.1.100 compares equal to 0.2.0 -- two releases
	@# indistinguishable, which is worse than either being wrong.
	@test -s VERSION || { echo "style: VERSION is missing or empty"; exit 1; }
	@v=`tr -d ' \t\n' < VERSION`; \
	h=version/version.h; \
	maj=`sed -n 's/^#define FZN_VERSION_MAJOR \([0-9][0-9]*\).*/\1/p' $$h`; \
	min=`sed -n 's/^#define FZN_VERSION_MINOR \([0-9][0-9]*\).*/\1/p' $$h`; \
	pat=`sed -n 's/^#define FZN_VERSION_PATCH \([0-9][0-9]*\).*/\1/p' $$h`; \
	str=`sed -n 's/^#define FZN_VERSION_STRING "\([^"]*\)".*/\1/p' $$h`; \
	if [ -z "$$maj" ] || [ -z "$$min" ] || [ -z "$$pat" ] || [ -z "$$str" ]; then \
		echo "style: could not read the version macros out of $$h."; \
		echo "style: a macro this could not find is not one it checked."; \
		exit 1; \
	fi; \
	if [ "$$maj.$$min.$$pat" != "$$v" ]; then \
		echo "style: $$h says $$maj.$$min.$$pat and VERSION says $$v"; \
		exit 1; \
	fi; \
	if [ "$$str" != "$$v" ]; then \
		echo "style: FZN_VERSION_STRING is \"$$str\" and VERSION says $$v"; \
		exit 1; \
	fi; \
	if [ "$$min" -gt 99 ] || [ "$$pat" -gt 99 ]; then \
		echo "style: $$v does not pack -- a minor or patch above 99 carries"; \
		echo "style: into the next field, so 0.1.100 would equal 0.2.0."; \
		exit 1; \
	fi; \
	echo "style: version/version.h and VERSION agree at $$v"

# Installs the commit-msg hook from tool/hooks/ into .git/hooks/. In the tree
# rather than only in .git so that it is reviewable, survives a clone, and can
# be diffed against its siblings in the other projects.
hooks:
	@install -m 0755 tool/hooks/commit-msg .git/hooks/commit-msg
	@echo "installed .git/hooks/commit-msg"

# Headers only. project.md sec 7 is explicit that this is not a system
# package and not a shared library -- a .so would put wire compatibility in
# the hands of whatever the distribution shipped, which is the failure a
# pinned submodule commit exists to prevent. DESTDIR is honoured because
# dh_auto_install calls it, and every private project honours it.
install: $(HDRS)
	@for h in $(HDRS); do \
		install -d $(DESTDIR)$(PREFIX)/include/fuzznet/`dirname $$h`; \
		install -m 0644 $$h $(DESTDIR)$(PREFIX)/include/fuzznet/$$h; \
	done
	@echo "installed `echo $(HDRS) | wc -w` header(s) under $(DESTDIR)$(PREFIX)/include/fuzznet"

# What do the suites never execute? Measured rather than assumed.
#
# Reports lines AND branches taken both ways, because the second is the
# honest number: 100% of lines is compatible with every decision in the
# library having only ever gone one way. It found two real gaps -- the
# malformed-argument guards of fzn_revocation_merge and fzn_split_at, each
# untested while its sibling function's was -- and one behaviour nobody had
# exercised, delegating a grant SHORTER than the chain allows.
#
# Instrumented objects go in their own BUILD_DIR: --coverage changes the
# objects, and mixing them with a plain build's is how a stale profile
# produces a number nobody can reproduce.
coverage:
	@test -n "$(BUILD_DIR)" || { echo "BUILD_DIR is empty; refusing"; exit 1; }
	@case "$(BUILD_DIR)" in /*) echo "BUILD_DIR must be relative; refusing"; exit 1 ;; esac
	@rm -rf $(BUILD_DIR)-coverage *.gcov
	@$(MAKE) --no-print-directory runtests BUILD_DIR=$(BUILD_DIR)-coverage \
	         CFLAGS="-Og -g --coverage" GEN_EXTRA="--coverage" >/dev/null
	@printf '%-30s %-14s %s\n' file lines "branches both ways"
	@unexercised=; \
	for c in $(SRCS); do \
		d=`dirname $$c`; \
		out=`gcov -b -o $(BUILD_DIR)-coverage/$$d $$c 2>/dev/null`; \
		l=`echo "$$out" | grep -m1 'Lines executed' | sed 's/.*://'`; \
		b=`echo "$$out" | grep -m1 'Taken at least once' | sed 's/.*://'`; \
		printf '%-30s %-14s %s\n' $$c "$$l" "$$b"; \
		case "$$l" in ""|0.00%*) unexercised="$$unexercised $$c" ;; esac; \
	done; \
	for c in $(GEN_SRCS); do \
		d=`dirname $$c`; \
		out=`gcov -b -o $(BUILD_DIR)-coverage/$$d $$c 2>/dev/null`; \
		l=`echo "$$out" | grep -m1 'Lines executed' | sed 's/.*://'`; \
		printf '%-30s %-14s %s\n' $$c "$$l" "(generated)"; \
		case "$$l" in ""|0.00%*) unexercised="$$unexercised $$c" ;; esac; \
	done; \
	rm -rf $(BUILD_DIR)-coverage *.gcov; \
	if [ -n "$$unexercised" ]; then \
		echo; \
		echo "coverage: NO TEST EXERCISES:$$unexercised"; \
		echo "coverage: a source linked into no test binary reports a blank"; \
		echo "coverage: line and exits 0, which is why this refuses instead."; \
		exit 1; \
	fi

# Refusing there rather than printing a blank is the point of the target
# beyond the numbers. Twice in one session a file reached the tree with
# nothing exercising it -- `fzn_peer_is_member`, added to answer a
# colleague's question rather than to fix a failing case, and
# `local/peer_linux.c`, believed untestable and not -- and both were found
# by a human reading the coverage table rather than by anything failing. A
# table nobody reads is a gate over an empty file list.

# Is the committed byte contract still what the schema says?
#
# project.md sec 7's reason for pinning a dependency is that this is a
# PROTOCOL: two hosts must agree about bytes, and a floating one is how they
# come to disagree silently. That reason applies hardest to the contract
# itself, so `wire/frame.situ.wire` and `.map` are committed and this target
# refuses when the schema has moved without them.
#
# SITU IS NOT A SUBMODULE, deliberately, and the distinction is what decides
# it: Monocypher is a submodule because it is LINKED -- its bytes end up in
# the binary. situ is a build-time tool. Vendoring it would make every clone
# carry a Python compiler and, worse, would push situc onto every consumer,
# since sec 7 has them compiling these sources into their own objects.
# fuzzypickles cross-compiles for Android; requiring situc there buys nothing
# at run time. Submodule what you link, not what you run at build time.
#
# So the schema's artifacts are committed and consumers need nothing extra.
# Checking them needs situc, which is why this is behind a variable and out
# of `make test`:
#
#   make schema SITU_DIR=../situ
#
# Without SITU_DIR it says what it would have checked rather than passing
# silently -- a target that no-ops when its tool is absent is a gate over an
# empty file list.
SITU_DIR ?=

schema:
	@if [ -z "$(SITU_DIR)" ]; then \
		echo "schema: SITU_DIR unset, so the committed contract was NOT checked."; \
		echo "schema: run 'make schema SITU_DIR=../situ' to verify it."; \
		exit 1; \
	fi
	@test -x "$(SITU_DIR)/bin/situc" || { echo "schema: no situc at $(SITU_DIR)/bin"; exit 1; }
	@# CHECKED AGAINST A COMMIT, NOT AGAINST A WORKING TREE.
	@#
	@# Everything below compares this repository's committed artifacts with
	@# what situ produces. Comparing against $(SITU_DIR) as it sits on disk
	@# makes that answer depend on whether anybody is mid-edit over there --
	@# and a session usually is.
	@#
	@# Both failure directions happened here within a minute. The target
	@# refused, naming our vendored runtime as drifted; our copy turned out
	@# identical to situ's HEAD, and the difference was an uncommitted
	@# change in their working tree. Re-vendoring "to fix the drift" then
	@# took that work in progress and stamped it with a commit hash that
	@# does not contain it -- a provenance banner that was a lie, and a
	@# check that would afterwards have passed. The dangerous direction is
	@# the pass, not the failure.
	@#
	@# So HEAD is extracted read-only with `git archive`, which touches
	@# nothing in their tree -- no worktree, no stash, no checkout, all of
	@# which would disturb a session working there. The commit is printed,
	@# because "matches situ" is not a claim and "matches situ at cd0cb01"
	@# is.
	@rm -rf $(BUILD_DIR)/.situ-head && mkdir -p $(BUILD_DIR)/.situ-head
	@if git -C "$(SITU_DIR)" rev-parse --git-dir >/dev/null 2>&1; then \
		git -C "$(SITU_DIR)" archive HEAD | tar -x -C $(BUILD_DIR)/.situ-head; \
		echo "schema: against situ `git -C $(SITU_DIR) rev-parse --short HEAD`"; \
	else \
		echo "schema: $(SITU_DIR) is not a git checkout, so nothing can be pinned"; \
		rm -rf $(BUILD_DIR)/.situ-head; exit 1; \
	fi
	@$(BUILD_DIR)/.situ-head/bin/situc wire --check wire/frame.situ
	@$(BUILD_DIR)/.situ-head/bin/situc map wire/frame.situ > $(BUILD_DIR)/.frame.map.new
	@if ! cmp -s $(BUILD_DIR)/.frame.map.new wire/frame.situ.map; then \
		echo "schema: wire/frame.situ.map is stale -- the schema moved without it"; \
		rm -f $(BUILD_DIR)/.frame.map.new; exit 1; \
	fi
	@rm -f $(BUILD_DIR)/.frame.map.new
	@# The generated C and the vendored runtime, same argument as the
	@# contract: committed so consumers need no situc, checked so they
	@# cannot quietly diverge from the schema that produced them.
	@rm -rf $(BUILD_DIR)/.gen.new && mkdir -p $(BUILD_DIR)/.gen.new
	@$(BUILD_DIR)/.situ-head/bin/situc build --target c --layer relate \
	         --out $(BUILD_DIR)/.gen.new wire/frame.situ >/dev/null 2>&1
	@for f in frame.c frame.h frame_relate.c frame_relate.h; do \
		cmp -s $(BUILD_DIR)/.gen.new/$$f wire/generated/$$f || { \
			echo "schema: wire/generated/$$f is stale"; \
			rm -rf $(BUILD_DIR)/.gen.new $(BUILD_DIR)/.situ-head; exit 1; }; \
	done
	@for f in situ.h situ.c; do \
		tail -n +2 wire/generated/$$f | sed '1,/^ \*\//d' > $(BUILD_DIR)/.gen.new/$$f.body; \
		cmp -s $(BUILD_DIR)/.gen.new/$$f.body $(BUILD_DIR)/.situ-head/runtime/c/$$f || { \
			echo "schema: wire/generated/$$f has drifted from situ's runtime"; \
			rm -rf $(BUILD_DIR)/.gen.new $(BUILD_DIR)/.situ-head; exit 1; }; \
	done
	@rm -rf $(BUILD_DIR)/.gen.new
	@rm -rf $(BUILD_DIR)/.situ-head
	@echo "schema: contract, map, generated C and vendored runtime all match"

# Does a consumer outside this tree still work? Nothing else asks.
#
# project.md sec 10 step 5 makes netcfgd's agent the first real consumer and
# sec 7 says how it takes this library: a submodule, sources compiled into
# its own objects, no archive. Every suite here builds from inside the tree,
# which is the one arrangement a consumer never has. Two silent failures
# follow from that and this target is what catches them -- a header added to
# a module and not to HDRS, which is hand-maintained and read back by
# nothing; and a relative include between modules that resolves in the
# source layout and not in the installed one.
#
# The staging directory is created here and removed here. It is guarded
# rather than trusted: an unset BUILD_DIR would make the rm below something
# else entirely, which is the failure `build-and-commit.md` names.
installcheck: $(HDRS) $(SRCS) tool/consumer_check.c
	@test -n "$(BUILD_DIR)" || { echo "BUILD_DIR is empty; refusing"; exit 1; }
	@# Every installed header must be one the consumer actually includes.
	@# Without this the target's guarantee narrows silently as modules are
	@# added: it can only catch a break in a header somebody remembered to
	@# include, and `session/commitment.h` and `local/peer.h` were both
	@# installed and unchecked for several commits.
	@missing=; \
	for h in $(HDRS); do \
		grep -q "$$h" tool/consumer_check.c || missing="$$missing $$h"; \
	done; \
	if [ -n "$$missing" ]; then \
		echo "installcheck: installed but not included by the consumer:$$missing"; \
		echo "installcheck: the check would pass whatever those headers did."; \
		exit 1; \
	fi
	@case "$(BUILD_DIR)" in /*) echo "BUILD_DIR must be relative; refusing"; exit 1 ;; esac
	@rm -rf $(BUILD_DIR)/installcheck
	@$(MAKE) --no-print-directory install DESTDIR=$(BUILD_DIR)/installcheck PREFIX=/usr >/dev/null
	@echo "installcheck: against the installed headers"
	@$(CC) $(CFLAGS) -DFZN_CONSUMER_INSTALLED \
	       -I$(BUILD_DIR)/installcheck/usr/include \
	       -o $(BUILD_DIR)/installcheck/consumer_installed \
	       -Iwire/generated $(MONO_CONSUMER) tool/consumer_check.c $(SRCS) $(GEN_SRCS)
	@$(BUILD_DIR)/installcheck/consumer_installed
	@echo "installcheck: against the source tree, from another directory"
	@cd $(BUILD_DIR)/installcheck && $(CC) $(CFLAGS) -I$(CURDIR) \
	       -I$(CURDIR)/wire/generated \
	       -o consumer_source $(CURDIR)/tool/consumer_check.c \
	       $(patsubst %,$(CURDIR)/%,$(SRCS)) \
	       $(patsubst %,$(CURDIR)/%,$(GEN_SRCS)) $(MONO_CONSUMER)
	@$(BUILD_DIR)/installcheck/consumer_source
	@rm -rf $(BUILD_DIR)/installcheck
	@echo "installcheck: both arrangements build and run"

# Named targets only, and it lists them. No rm -rf of a directory and no
# wildcard sweep: a clean target is the one thing everybody runs without
# reading, and an unset variable in an `rm -rf $(VAR)` is how one eats
# something it should not.
# WHAT MONOCYPHER_DIR BUILT IS NAMED UNCONDITIONALLY, because clean is
# usually run without it.
#
# OBJS, TEST_OBJS and TEST_BINS gain the Monocypher half only inside the
# `ifneq` above, so `make test MONOCYPHER_DIR=...` followed by a plain `make
# clean` left thirteen objects and three binaries in the tree and printed
# "fuzznet: clean". That is build-and-commit.md's warning in its other
# direction: a clean target that removes LESS than was built, and says so as
# loudly as one that removed everything.
#
# Named rather than globbed, per the same rule. MONO_SRCS and MONO_TSRC are
# already outside the conditional for the style check, so the names are here
# to be had; monocypher.o is the vendored upstream source and is spelled out.
MONO_CLEAN := $(MONO_SRCS:%.c=$(BUILD_DIR)/%.o) $(MONO_SRCS:%.c=$(BUILD_DIR)/%.d) \
              $(MONO_TSRC:%.c=$(BUILD_DIR)/%.o) $(MONO_TSRC:%.c=$(BUILD_DIR)/%.d) \
              $(MONO_TSRC:%.c=$(BUILD_DIR)/%) \
              $(BUILD_DIR)/monocypher.o $(BUILD_DIR)/monocypher.d

clean:
	@for f in $(OBJS) $(TEST_OBJS) $(DEPS) $(TEST_BINS) $(MONO_CLEAN); do \
		if [ -e "$$f" ]; then echo "removing $$f"; rm -f "$$f"; fi; \
	done
	@# CLEAN CHECKS ITS OWN WORK, which is the only way "quietly removed
	@# nothing" and "removed everything" stop looking alike. Only for the
	@# in-place default: an out-of-tree BUILD_DIR leaves the tree with no
	@# artifacts to find whether it worked or not.
	@if [ "$(BUILD_DIR)" = "." ]; then \
		left=`find . \( -name '*.o' -o -name '*.d' -o -name '*.gcno' \
		                 -o -name '*.gcda' \) -not -path './.git/*' \
		                 -not -path './.claude/*' | sort`; \
		if [ -n "$$left" ]; then \
			echo "clean: build artifacts survived:"; \
			echo "$$left" | sed 's/^/  /'; \
			echo "clean: something the build produces is in no list clean reads."; \
			exit 1; \
		fi; \
	fi
	@echo "fuzznet: clean"

-include $(DEPS)
