# fuzznet -- the shared authenticated datagram protocol.
#
# project.md sec 10 step 3 makes chain/ the first real code: sec 7a gave most
# of sec 4 to situ once the layer ladder arrived, and the capability model is
# what stayed ours, being semantics rather than layout or transport.
#
# There is deliberately NO archive rule. project.md sec 7 has consumers
# compiling these sources into their own objects, with their own flags --
# fuzzypickles cross-compiles for Android and builds sanitized, netcfgd's
# agent is an ordinary host binary, and a prebuilt .a serves neither.
# build-and-commit.md says not to add an archive step without a specific
# need, and the need this would answer is one nobody has.

BUILD_DIR ?= .
CC        ?= cc
DESTDIR   ?=
PREFIX    ?= /usr/local

# -Os because that is the workspace default and this library is aimed at
# routers and phones: it is the instruction cache that is scarce here, not
# the arithmetic. -Og when debugging, deliberately and temporarily.
CFLAGS  ?= -Os -g

# SANITIZE=1 builds everything under AddressSanitizer and UBSan.
#
# It exists because the canaries in the fuzz harnesses are a substitute for
# this, and say so: on a plain -Os build a two-byte overrun into a
# neighbouring slot corrupts somebody else's message and returns success.
# A canary catches a WRITE past the end of a buffer it brackets. It cannot
# see a read of bytes nothing wrote, an off-by-one inside the buffer, or
# signed overflow -- and those are the defects this library's arithmetic
# could plausibly have, since it computes offsets from values a stranger
# chose.
#
# NOT the default, deliberately. project.md sec 7 has each consumer
# compiling these sources with its own flags, and a library that forced a
# sanitizer on them would be choosing for fuzzypickles' Android build. It
# is a knob for this tree's own testing:
#
#   make test SANITIZE=1
#   make fuzz SANITIZE=1 CASES=200000
#
# -Og rather than -Os under it, because a sanitizer report through fully
# optimised code names the wrong line, and BUILD_DIR should be set to keep
# the objects apart from a plain build's -- they are not interchangeable
# and mixing them produces a link nobody can explain.
SANITIZE ?=
ifeq ($(SANITIZE),1)
# Replaces the optimisation and adds the instrumentation. The warning flags
# are NOT repeated here -- they are appended below for both builds, and
# listing them twice put every one of them on the command line twice.
CFLAGS  := -Og -g -fsanitize=address,undefined -fno-omit-frame-pointer \
           -fno-sanitize-recover=all
endif
CFLAGS  += -std=c11 -Wall -Wextra -Wpedantic -Wshadow -Wconversion \
           -Wstrict-prototypes -Wvla
CPPFLAGS += -MMD -MP

# Generated by situ and vendored from it. Compiled with their own terms
# rather than ours -- code-style.md exempts generated and vendored sources,
# and -Wconversion against a code generator's output is noise nobody reads,
# which is how a warning that matters gets missed. They happen to be clean
# under our full set today; that is luck to enjoy, not a rule to enforce on
# somebody else's emitter.
GEN_SRCS  := wire/generated/frame.c wire/generated/frame_relate.c \
             wire/generated/situ.c
GEN_OBJS  := $(GEN_SRCS:%.c=$(BUILD_DIR)/%.o)

SRCS      := constant_time/constant_time.c session/commitment.c \
             local/peer.c local/peer_linux.c \
             chain/chain.c chain/revocation.c frame/freshness.c \
             chunk/reassembly.c \
             chunk/split.c
OBJS      := $(SRCS:%.c=$(BUILD_DIR)/%.o) $(GEN_OBJS)
HDRS      := constant_time/constant_time.h session/commitment.h \
             local/peer.h \
             chain/chain.h chain/revocation.h frame/freshness.h \
             chunk/reassembly.h \
             chunk/split.h

TEST_SRCS := chain/tests/chain_test.c chain/tests/revocation_test.c \
             frame/tests/freshness_test.c \
             chunk/tests/reassembly_test.c chunk/tests/split_test.c \
             session/tests/commitment_test.c local/tests/peer_test.c \
             wire/tests/generated_test.c chunk/tests/agreement_test.c \
             wire/tests/constants_test.c \
             local/tests/peer_fuzz.c local/tests/peer_linux_test.c \
             chunk/tests/reassembly_fuzz.c chain/tests/chain_fuzz.c \
             frame/tests/freshness_fuzz.c chain/tests/revocation_fuzz.c \
             chunk/tests/roundtrip_fuzz.c
TEST_OBJS := $(TEST_SRCS:%.c=$(BUILD_DIR)/%.o)
TEST_BINS := $(BUILD_DIR)/chain/tests/chain_test \
             $(BUILD_DIR)/chain/tests/revocation_test \
             $(BUILD_DIR)/frame/tests/freshness_test \
             $(BUILD_DIR)/session/tests/commitment_test \
             $(BUILD_DIR)/local/tests/peer_test \
             $(BUILD_DIR)/wire/tests/generated_test \
             $(BUILD_DIR)/wire/tests/constants_test \
             $(BUILD_DIR)/chunk/tests/agreement_test \
             $(BUILD_DIR)/local/tests/peer_fuzz \
             $(BUILD_DIR)/local/tests/peer_linux_test \
             $(BUILD_DIR)/chunk/tests/reassembly_test \
             $(BUILD_DIR)/chunk/tests/split_test \
             $(BUILD_DIR)/chunk/tests/reassembly_fuzz \
             $(BUILD_DIR)/chain/tests/chain_fuzz \
             $(BUILD_DIR)/frame/tests/freshness_fuzz \
             $(BUILD_DIR)/chain/tests/revocation_fuzz \
             $(BUILD_DIR)/chunk/tests/roundtrip_fuzz

# The Monocypher binding, built only when MONOCYPHER_DIR names a checkout.
#
# project.md sec 7 says a submodule and sec 10 has not reached that step, so
# there is nothing vendored here to build against and adding a dependency is
# not a thing to do in passing. During bring-up sec 7 blesses exactly this
# shape -- a sibling directory behind a variable, not a second build path:
#
#   make test MONOCYPHER_DIR=../fuzzypickles/monocypher
#
# Without it the library builds and every test above still runs, which is
# the property chain.h's signer vtable exists to give. With it, one more
# binary runs a real Ed25519 round trip, because a seam that has only ever
# had a stub behind it is a seam nobody has checked.
MONOCYPHER_DIR ?=

# Named OUTSIDE the conditional, because these files exist in the tree whether
# or not this build compiles them, and `make style` compares the source lists
# against what is actually there. Inside the `ifneq` they would be empty in a
# plain build and the check would report two real sources as unlisted -- a
# false finding, which is worse in a gate than no finding at all.
MONO_SRCS  := chain/sign_monocypher.c session/hash_monocypher.c
MONO_TSRC  := chain/tests/sign_monocypher_test.c \
              session/tests/hash_monocypher_test.c

ifneq ($(MONOCYPHER_DIR),)
MONO_OBJS  := $(BUILD_DIR)/chain/sign_monocypher.o \
              $(BUILD_DIR)/session/hash_monocypher.o \
              $(BUILD_DIR)/monocypher.o
MONO_TOBJ  := $(MONO_TSRC:%.c=$(BUILD_DIR)/%.o)
# Kept in TEST_SRCS as well as TEST_OBJS. Nothing was broken by its absence
# -- the objects, deps and binaries were all reached through MONO_TOBJ --
# but TEST_SRCS is the list that reads as "every test source", and one that
# is quietly incomplete is a trap for whatever asks it next. Found by asking
# it exactly that question.
TEST_SRCS  += $(MONO_TSRC)
# SRCS too, and for the same reason TEST_SRCS was fixed: it is the list that
# reads as "every library source", and `make coverage` iterates it. Without
# this the two bindings were built, linked and run by their own tests while
# the guard written to refuse an unexercised source could not see them --
# which is `GEN_SRCS` against `SRCS` a third time.
#
# It must come after OBJS is computed, which it does: OBJS took its value from
# SRCS above, and MONO_OBJS is added to it separately below, so the objects are
# named once rather than twice.
SRCS       += $(MONO_SRCS)
# What `tools/consumer_check.c` needs to exercise the bindings: the define that
# switches its optional block on, the include path, and Monocypher itself,
# since installcheck compiles sources rather than linking objects.
# Absolute, because installcheck's second arm compiles from inside
# $(BUILD_DIR)/installcheck -- which is why the SRCS beside it are put through
# $(CURDIR) as well. A relative path here builds in one arrangement and not the
# other, which is the difference the whole target exists to find.
MONO_ABS      := $(abspath $(MONOCYPHER_DIR))
MONO_CONSUMER := -DFZN_CONSUMER_MONOCYPHER -I$(MONO_ABS)/src \
                 $(MONO_ABS)/src/monocypher.c
MONO_BIN   := $(BUILD_DIR)/chain/tests/sign_monocypher_test
MONO_HASH  := $(BUILD_DIR)/session/tests/hash_monocypher_test
OBJS       += $(MONO_OBJS)
TEST_OBJS  += $(MONO_TOBJ)
TEST_BINS  += $(MONO_BIN) $(MONO_HASH)
HDRS       += chain/sign_monocypher.h session/hash_monocypher.h
CPPFLAGS   += -I$(MONOCYPHER_DIR)/src

# Vendored, so it is compiled with its own terms rather than ours.
# code-style.md exempts vendored sources from our rules, and -Wconversion
# against somebody else's crypto is noise nobody will read, which is how a
# warning that matters gets missed.
$(BUILD_DIR)/monocypher.o: $(MONOCYPHER_DIR)/src/monocypher.c
	@mkdir -p $(dir $@)
	$(CC) -Os -g -c $< -o $@

# Each names its own objects rather than linking $(MONO_OBJS) wholesale.
# Linking both bindings into both binaries would work and would hide which
# one each test actually exercises, which is the thing these tests are for.
$(MONO_BIN): $(BUILD_DIR)/chain/tests/sign_monocypher_test.o \
             $(BUILD_DIR)/chain/sign_monocypher.o $(BUILD_DIR)/monocypher.o \
             $(BUILD_DIR)/chain/chain.o \
             $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(MONO_HASH): $(BUILD_DIR)/session/tests/hash_monocypher_test.o \
              $(BUILD_DIR)/session/hash_monocypher.o $(BUILD_DIR)/monocypher.o \
              $(BUILD_DIR)/session/commitment.o \
              $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@
endif

# Every -MMD file is read back, TEST OBJECTS INCLUDED. build-and-commit.md
# names that omission specifically: a test object whose .d is never included
# does not rebuild when a header it includes changes, so a struct that gains
# a field ends up with one layout in the library and another in the binary
# linked against it -- which surfaces as a pile of nonsense assertion
# failures rather than as a build error.
DEPS := $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)

.PHONY: all test fuzz installcheck coverage schema style codegencheck hooks clean install

# The default build does NOT build tests -- build-and-commit.md, and the
# discipline it buys is paid for by the dependency rules above being right.
all: $(OBJS)

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# GEN_EXTRA exists so `make coverage` can instrument these without their
# warning flags becoming ours. Without it the coverage target reported all
# three as exercised by nothing, which was false -- generated_test drives
# them -- and a false positive from a guard is worth no more than the false
# negative it replaced.
GEN_EXTRA ?=

$(BUILD_DIR)/wire/generated/%.o: wire/generated/%.c
	@mkdir -p $(dir $@)
	$(CC) -Os -g $(GEN_EXTRA) -Iwire/generated -MMD -MP -c $< -o $@

$(BUILD_DIR)/chain/tests/chain_test: $(BUILD_DIR)/chain/tests/chain_test.o \
                                     $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/frame/tests/freshness_test: $(BUILD_DIR)/frame/tests/freshness_test.o \
                                         $(BUILD_DIR)/frame/freshness.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chunk/tests/reassembly_test: $(BUILD_DIR)/chunk/tests/reassembly_test.o \
                                          $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links BOTH halves on purpose: this binary is what holds the splitter and
# the reassembler to the same contract.
$(BUILD_DIR)/chunk/tests/split_test: $(BUILD_DIR)/chunk/tests/split_test.o \
                                     $(BUILD_DIR)/chunk/split.o \
                                     $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/tests/revocation_test: $(BUILD_DIR)/chain/tests/revocation_test.o \
                                          $(BUILD_DIR)/chain/revocation.o \
                                          $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The fuzz harness. It runs a FIXED number of cases from a seeded generator
# -- argv[1] or its own default -- so `make test` terminates and a failing
# case is reproducible from the source alone. `make fuzz CASES=n` runs a
# longer campaign without editing anything.
$(BUILD_DIR)/chunk/tests/reassembly_fuzz: $(BUILD_DIR)/chunk/tests/reassembly_fuzz.o \
                                          $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/tests/chain_fuzz: $(BUILD_DIR)/chain/tests/chain_fuzz.o \
                                     $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/frame/tests/freshness_fuzz: $(BUILD_DIR)/frame/tests/freshness_fuzz.o \
                                         $(BUILD_DIR)/frame/freshness.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/chain/tests/revocation_fuzz: $(BUILD_DIR)/chain/tests/revocation_fuzz.o \
                                          $(BUILD_DIR)/chain/revocation.o \
                                          $(BUILD_DIR)/chain/chain.o \
                                     $(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links both halves, like split_test: this binary is what holds the
# splitter and the reassembler to the same contract over permutations.
$(BUILD_DIR)/chunk/tests/roundtrip_fuzz: $(BUILD_DIR)/chunk/tests/roundtrip_fuzz.o \
                                         $(BUILD_DIR)/chunk/split.o \
                                         $(BUILD_DIR)/chunk/reassembly.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/session/tests/commitment_test: \
		$(BUILD_DIR)/session/tests/commitment_test.o \
		$(BUILD_DIR)/session/commitment.o \
		$(BUILD_DIR)/constant_time/constant_time.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links peer.c only. peer_linux.c is the system half and holds no
# decisions, so the suite drives every one of them without a socket.
$(BUILD_DIR)/local/tests/peer_test: $(BUILD_DIR)/local/tests/peer_test.o \
                                    $(BUILD_DIR)/local/peer.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/local/tests/peer_fuzz: $(BUILD_DIR)/local/tests/peer_fuzz.o \
                                    $(BUILD_DIR)/local/peer.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# The one test that links the system half. It needs no cooperating
# process: a socketpair has both ends here, so SO_PEERCRED reports us.
$(BUILD_DIR)/local/tests/peer_linux_test: $(BUILD_DIR)/local/tests/peer_linux_test.o \
                                          $(BUILD_DIR)/local/peer.o \
                                          $(BUILD_DIR)/local/peer_linux.o
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Three tests read situ's output and need the generated include path, so each
# has its own compile rule rather than the pattern's. This comment said "the
# only test" until there were three of them.
$(BUILD_DIR)/wire/tests/generated_test.o: wire/tests/generated_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/wire/tests/constants_test.o: wire/tests/constants_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

# Links the generated runtime for the frame views its runtime half needs;
# every other check in it is a static assert and needs no object at all.
$(BUILD_DIR)/wire/tests/constants_test: $(BUILD_DIR)/wire/tests/constants_test.o \
                                        $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

$(BUILD_DIR)/wire/tests/generated_test: $(BUILD_DIR)/wire/tests/generated_test.o \
                                        $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Links situ's output AND our reassembler, which is the only binary that
# does. It exists to compare the two implementations of one rule.
$(BUILD_DIR)/chunk/tests/agreement_test.o: chunk/tests/agreement_test.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -Iwire/generated -c $< -o $@

$(BUILD_DIR)/chunk/tests/agreement_test: $(BUILD_DIR)/chunk/tests/agreement_test.o \
                                         $(BUILD_DIR)/chunk/reassembly.o $(GEN_OBJS)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $^ -o $@

# Tests are built by this target and only by it, so a claim that a test
# passes or fails always goes through a rebuild. Re-running a stale binary
# after a plain build appears to pass either way.
# ctcheck runs first because it is about the library rather than the tests, and
# because a failure there is more interesting than any assertion below it.
test: codegencheck $(TEST_BINS)
	@for t in $(TEST_BINS); do echo "running $$t"; $$t || exit 1; done

CASES ?= 200000

FUZZ_BINS := $(BUILD_DIR)/chunk/tests/reassembly_fuzz \
             $(BUILD_DIR)/chain/tests/chain_fuzz \
             $(BUILD_DIR)/frame/tests/freshness_fuzz \
             $(BUILD_DIR)/chain/tests/revocation_fuzz \
             $(BUILD_DIR)/chunk/tests/roundtrip_fuzz \
             $(BUILD_DIR)/local/tests/peer_fuzz

fuzz: $(FUZZ_BINS)
	@for f in $(FUZZ_BINS); do echo "== $$f $(CASES)"; $$f $(CASES) || exit 1; done

# Not bare. A bare `.SECONDARY:` applies to every target matched by any
# pattern rule, silently including the object pattern above, and make does
# not rebuild a MISSING secondary when the thing depending on it already
# exists -- so adding a source would leave the build unchanged and every
# symbol in it undefined at link time. It exists to stop test objects being
# deleted as intermediates, so it names exactly those.
.SECONDARY: $(TEST_OBJS)

# The indentation, whitespace and ASCII gate. One tool, spread verbatim from
# ~/.claude/tools/style_gate.py; .style-gate.toml says which files here it
# applies to.
# TWO SECURITY PROPERTIES THE OPTIMISER COULD TAKE AWAY, each measured once by
# hand and then left in a comment. See tools/codegen_gate.py for what it does
# and does not claim -- it pins the shape each function compiles to so that a
# change stops the build, which is a tripwire rather than a proof. Skips loudly
# off x86-64 and without objdump; refuses if it cannot find a function, since
# that is indistinguishable from checking nothing.
#
# Named one per line rather than looped, because the pair is the point: a
# check added here should be a deliberate line somebody wrote.
codegencheck: $(BUILD_DIR)/constant_time/constant_time.o \
              $(BUILD_DIR)/session/commitment.o
	python3 tools/codegen_gate.py ct $(BUILD_DIR)/constant_time/constant_time.o
	python3 tools/codegen_gate.py wipe $(BUILD_DIR)/session/commitment.o

style:
	python3 tools/style_gate.py check
	@# EVERY .c IN THE TREE MUST BE IN A LIST -- the fourth instance of one
	@# pattern and the last that was not mechanically checked. HDRS against
	@# `install`, GEN_SRCS against `coverage`, TEST_BINS against .gitignore,
	@# and SRCS against the tree: each is a list kept by hand, and each guard
	@# is only as wide as the list it iterates. The first three are compared
	@# against another list. This one has no second list, so it is compared
	@# against the filesystem.
	@#
	@# It is what would have caught the Monocypher bindings, which were in the
	@# tree, built, linked and run, and in no list `make coverage` reads.
	@known=" $(SRCS) $(TEST_SRCS) $(GEN_SRCS) $(MONO_SRCS) $(MONO_TSRC) tools/consumer_check.c "; \
	unlisted=; n=0; \
	for c in `find . -name '*.c' -not -path './build/*' -not -path './san/*' \
	                 -not -path './*-coverage/*' | sed 's|^\./||' | sort`; do \
		n=$$((n + 1)); \
		case "$$known" in *" $$c "*) ;; *) unlisted="$$unlisted $$c" ;; esac; \
	done; \
	if [ "$$n" -eq 0 ]; then \
		echo "style: no C sources found, which cannot be right"; exit 1; \
	fi; \
	if [ -n "$$unlisted" ]; then \
		echo "style: C sources in the tree and in no list:$$unlisted"; \
		echo "style: nothing reading SRCS -- coverage, installcheck -- can see them."; \
		exit 1; \
	fi; \
	echo "style: $$n C sources, all named in a list"
	@# THE THIRD HAND-MAINTAINED LIST, and the third time one has drifted.
	@# .gitignore names each test binary rather than globbing them, for a
	@# stated reason: a pattern would also hide a source file added under
	@# that name by mistake. The cost is a line per test, and forgetting it
	@# leaves a build product in `git status` -- which matters here because
	@# the rule against blanket `git add` depends on that output being
	@# trustworthy. Noise trains people to stop reading it.
	@#
	@# HDRS versus `install` and GEN_SRCS versus `coverage` were the first
	@# two, and both were found by something breaking rather than by
	@# anybody comparing the lists. So this compares them.
	@#
	@# Only meaningful for the in-place default: an out-of-tree BUILD_DIR is
	@# covered by /build/ and the paths below would not be in .gitignore at
	@# all. Skipped loudly rather than passing vacuously.
	@if [ "$(BUILD_DIR)" != "." ]; then \
		echo "style: BUILD_DIR is '$(BUILD_DIR)', so the .gitignore check was SKIPPED"; \
	else \
		missing=; n=0; \
		for b in $(TEST_BINS); do \
			n=$$((n + 1)); \
			grep -qx -- "$${b#.}" .gitignore || missing="$$missing $${b#./}"; \
		done; \
		if [ "$$n" -eq 0 ]; then \
			echo "style: no test binaries to check, which cannot be right"; exit 1; \
		fi; \
		if [ -n "$$missing" ]; then \
			echo "style: test binaries missing from .gitignore:$$missing"; exit 1; \
		fi; \
		echo "style: $$n test binaries all named in .gitignore"; \
	fi

# Installs the commit-msg hook from tools/hooks/ into .git/hooks/. In the tree
# rather than only in .git so that it is reviewable, survives a clone, and can
# be diffed against its siblings in the other projects.
hooks:
	@install -m 0755 tools/hooks/commit-msg .git/hooks/commit-msg
	@echo "installed .git/hooks/commit-msg"

# Headers only. project.md sec 7 is explicit that this is not a system
# package and not a shared library -- a .so would put wire compatibility in
# the hands of whatever the distribution shipped, which is the failure a
# pinned submodule commit exists to prevent. DESTDIR is honoured because
# dh_auto_install calls it, and every private project honours it.
install: $(HDRS)
	@for h in $(HDRS); do \
		install -d $(DESTDIR)$(PREFIX)/include/fuzznet/`dirname $$h`; \
		install -m 0644 $$h $(DESTDIR)$(PREFIX)/include/fuzznet/$$h; \
	done
	@echo "installed `echo $(HDRS) | wc -w` header(s) under $(DESTDIR)$(PREFIX)/include/fuzznet"

# What do the suites never execute? Measured rather than assumed.
#
# Reports lines AND branches taken both ways, because the second is the
# honest number: 100% of lines is compatible with every decision in the
# library having only ever gone one way. It found two real gaps -- the
# malformed-argument guards of fzn_revocation_merge and fzn_split_at, each
# untested while its sibling function's was -- and one behaviour nobody had
# exercised, delegating a grant SHORTER than the chain allows.
#
# Instrumented objects go in their own BUILD_DIR: --coverage changes the
# objects, and mixing them with a plain build's is how a stale profile
# produces a number nobody can reproduce.
coverage:
	@test -n "$(BUILD_DIR)" || { echo "BUILD_DIR is empty; refusing"; exit 1; }
	@case "$(BUILD_DIR)" in /*) echo "BUILD_DIR must be relative; refusing"; exit 1 ;; esac
	@rm -rf $(BUILD_DIR)-coverage *.gcov
	@$(MAKE) --no-print-directory test BUILD_DIR=$(BUILD_DIR)-coverage \
	         CFLAGS="-Og -g --coverage" GEN_EXTRA="--coverage" >/dev/null
	@printf '%-30s %-14s %s\n' file lines "branches both ways"
	@unexercised=; \
	for c in $(SRCS); do \
		d=`dirname $$c`; \
		out=`gcov -b -o $(BUILD_DIR)-coverage/$$d $$c 2>/dev/null`; \
		l=`echo "$$out" | grep -m1 'Lines executed' | sed 's/.*://'`; \
		b=`echo "$$out" | grep -m1 'Taken at least once' | sed 's/.*://'`; \
		printf '%-30s %-14s %s\n' $$c "$$l" "$$b"; \
		case "$$l" in ""|0.00%*) unexercised="$$unexercised $$c" ;; esac; \
	done; \
	for c in $(GEN_SRCS); do \
		d=`dirname $$c`; \
		out=`gcov -b -o $(BUILD_DIR)-coverage/$$d $$c 2>/dev/null`; \
		l=`echo "$$out" | grep -m1 'Lines executed' | sed 's/.*://'`; \
		printf '%-30s %-14s %s\n' $$c "$$l" "(generated)"; \
		case "$$l" in ""|0.00%*) unexercised="$$unexercised $$c" ;; esac; \
	done; \
	rm -rf $(BUILD_DIR)-coverage *.gcov; \
	if [ -n "$$unexercised" ]; then \
		echo; \
		echo "coverage: NO TEST EXERCISES:$$unexercised"; \
		echo "coverage: a source linked into no test binary reports a blank"; \
		echo "coverage: line and exits 0, which is why this refuses instead."; \
		exit 1; \
	fi

# Refusing there rather than printing a blank is the point of the target
# beyond the numbers. Twice in one session a file reached the tree with
# nothing exercising it -- `fzn_peer_is_member`, added to answer a
# colleague's question rather than to fix a failing case, and
# `local/peer_linux.c`, believed untestable and not -- and both were found
# by a human reading the coverage table rather than by anything failing. A
# table nobody reads is a gate over an empty file list.

# Is the committed byte contract still what the schema says?
#
# project.md sec 7's reason for pinning a dependency is that this is a
# PROTOCOL: two hosts must agree about bytes, and a floating one is how they
# come to disagree silently. That reason applies hardest to the contract
# itself, so `wire/frame.situ.wire` and `.map` are committed and this target
# refuses when the schema has moved without them.
#
# SITU IS NOT A SUBMODULE, deliberately, and the distinction is what decides
# it: Monocypher is a submodule because it is LINKED -- its bytes end up in
# the binary. situ is a build-time tool. Vendoring it would make every clone
# carry a Python compiler and, worse, would push situc onto every consumer,
# since sec 7 has them compiling these sources into their own objects.
# fuzzypickles cross-compiles for Android; requiring situc there buys nothing
# at run time. Submodule what you link, not what you run at build time.
#
# So the schema's artifacts are committed and consumers need nothing extra.
# Checking them needs situc, which is why this is behind a variable and out
# of `make test`:
#
#   make schema SITU_DIR=../situ
#
# Without SITU_DIR it says what it would have checked rather than passing
# silently -- a target that no-ops when its tool is absent is a gate over an
# empty file list.
SITU_DIR ?=

schema:
	@if [ -z "$(SITU_DIR)" ]; then \
		echo "schema: SITU_DIR unset, so the committed contract was NOT checked."; \
		echo "schema: run 'make schema SITU_DIR=../situ' to verify it."; \
		exit 1; \
	fi
	@test -x "$(SITU_DIR)/bin/situc" || { echo "schema: no situc at $(SITU_DIR)/bin"; exit 1; }
	@$(SITU_DIR)/bin/situc wire --check wire/frame.situ
	@$(SITU_DIR)/bin/situc map wire/frame.situ > $(BUILD_DIR)/.frame.map.new
	@if ! cmp -s $(BUILD_DIR)/.frame.map.new wire/frame.situ.map; then \
		echo "schema: wire/frame.situ.map is stale -- the schema moved without it"; \
		rm -f $(BUILD_DIR)/.frame.map.new; exit 1; \
	fi
	@rm -f $(BUILD_DIR)/.frame.map.new
	@# The generated C and the vendored runtime, same argument as the
	@# contract: committed so consumers need no situc, checked so they
	@# cannot quietly diverge from the schema that produced them.
	@rm -rf $(BUILD_DIR)/.gen.new && mkdir -p $(BUILD_DIR)/.gen.new
	@$(SITU_DIR)/bin/situc build --target c --layer relate \
	         --out $(BUILD_DIR)/.gen.new wire/frame.situ >/dev/null 2>&1
	@for f in frame.c frame.h frame_relate.c frame_relate.h; do \
		cmp -s $(BUILD_DIR)/.gen.new/$$f wire/generated/$$f || { \
			echo "schema: wire/generated/$$f is stale"; \
			rm -rf $(BUILD_DIR)/.gen.new; exit 1; }; \
	done
	@for f in situ.h situ.c; do \
		tail -n +2 wire/generated/$$f | sed '1,/^ \*\//d' > $(BUILD_DIR)/.gen.new/$$f.body; \
		cmp -s $(BUILD_DIR)/.gen.new/$$f.body $(SITU_DIR)/runtime/c/$$f || { \
			echo "schema: wire/generated/$$f has drifted from situ's runtime"; \
			rm -rf $(BUILD_DIR)/.gen.new; exit 1; }; \
	done
	@rm -rf $(BUILD_DIR)/.gen.new
	@echo "schema: contract, map, generated C and vendored runtime all match"

# Does a consumer outside this tree still work? Nothing else asks.
#
# project.md sec 10 step 5 makes netcfgd's agent the first real consumer and
# sec 7 says how it takes this library: a submodule, sources compiled into
# its own objects, no archive. Every suite here builds from inside the tree,
# which is the one arrangement a consumer never has. Two silent failures
# follow from that and this target is what catches them -- a header added to
# a module and not to HDRS, which is hand-maintained and read back by
# nothing; and a relative include between modules that resolves in the
# source layout and not in the installed one.
#
# The staging directory is created here and removed here. It is guarded
# rather than trusted: an unset BUILD_DIR would make the rm below something
# else entirely, which is the failure `build-and-commit.md` names.
installcheck: $(HDRS) $(SRCS) tools/consumer_check.c
	@test -n "$(BUILD_DIR)" || { echo "BUILD_DIR is empty; refusing"; exit 1; }
	@# Every installed header must be one the consumer actually includes.
	@# Without this the target's guarantee narrows silently as modules are
	@# added: it can only catch a break in a header somebody remembered to
	@# include, and `session/commitment.h` and `local/peer.h` were both
	@# installed and unchecked for several commits.
	@missing=; \
	for h in $(HDRS); do \
		grep -q "$$h" tools/consumer_check.c || missing="$$missing $$h"; \
	done; \
	if [ -n "$$missing" ]; then \
		echo "installcheck: installed but not included by the consumer:$$missing"; \
		echo "installcheck: the check would pass whatever those headers did."; \
		exit 1; \
	fi
	@case "$(BUILD_DIR)" in /*) echo "BUILD_DIR must be relative; refusing"; exit 1 ;; esac
	@rm -rf $(BUILD_DIR)/installcheck
	@$(MAKE) --no-print-directory install DESTDIR=$(BUILD_DIR)/installcheck PREFIX=/usr >/dev/null
	@echo "installcheck: against the installed headers"
	@$(CC) $(CFLAGS) -DFZN_CONSUMER_INSTALLED \
	       -I$(BUILD_DIR)/installcheck/usr/include \
	       -o $(BUILD_DIR)/installcheck/consumer_installed \
	       $(MONO_CONSUMER) tools/consumer_check.c $(SRCS)
	@$(BUILD_DIR)/installcheck/consumer_installed
	@echo "installcheck: against the source tree, from another directory"
	@cd $(BUILD_DIR)/installcheck && $(CC) $(CFLAGS) -I$(CURDIR) \
	       -o consumer_source $(CURDIR)/tools/consumer_check.c \
	       $(patsubst %,$(CURDIR)/%,$(SRCS)) $(MONO_CONSUMER)
	@$(BUILD_DIR)/installcheck/consumer_source
	@rm -rf $(BUILD_DIR)/installcheck
	@echo "installcheck: both arrangements build and run"

# Named targets only, and it lists them. No rm -rf of a directory and no
# wildcard sweep: a clean target is the one thing everybody runs without
# reading, and an unset variable in an `rm -rf $(VAR)` is how one eats
# something it should not.
clean:
	@for f in $(OBJS) $(TEST_OBJS) $(DEPS) $(TEST_BINS); do \
		if [ -e "$$f" ]; then echo "removing $$f"; rm -f "$$f"; fi; \
	done
	@echo "fuzznet: clean"

-include $(DEPS)
