/* Reassembly, and the hard bound on what a half-finished message may hold.
 *
 * project.md sec 4.4 calls this the largest and riskiest piece, and sec 4.4a
 * says why the bound is not hygiene: "the reassembly path must bound the
 * memory a half-finished response may hold or a stranger can exhaust it".
 * A netcfgd `status` is an entire observation -- every link, address, route,
 * backend and DNS scope -- so it is past any UDP MTU on a router with a
 * dozen interfaces, and chunking is the reason this is hard rather than a
 * feature demo.
 *
 * WHAT THIS IS NOT: a retransmission state machine. sec 10 names that as
 * deliberately absent, because situ generates one at rung 6 and building a
 * second by hand is the exact duplication both projects exist to remove.
 * Nothing here asks for a chunk, times anything out, or sends. It answers
 * one question per datagram -- may this chunk be held, and is the message
 * now complete -- and refuses when holding it would cost more than the
 * caller agreed to spend.
 *
 * WHY IT IS OURS AT ALL, since sec 7a assigns 4.4 to situ: measured against
 * situc 1.0 on 2026-08-14, no rung emits datagram reassembly. Rung 4
 * `frame` is STREAM framing -- a byte stream in, whole messages out, which
 * is a different problem with the same word attached. Rung 5 `converse`
 * keeps a pending table keyed by a relation, which matches a reply to a
 * request rather than a piece to a whole. Holding chunks of one message
 * that arrive out of order, from a self-contained datagram carrying `msg`,
 * `index` and `chunks`, is not generated by anything. sec 7a's table row is
 * optimistic and project.md records that.
 */

#ifndef FZN_REASSEMBLY_H
#define FZN_REASSEMBLY_H

#include <stddef.h>
#include <stdint.h>

#define FZN_SENDER_LEN 32

/* The most chunks one message may claim, and therefore the size of the
 * arrived-set below.
 *
 * A COMPILE-TIME CEILING ON PURPOSE. wire/frame.situ makes `chunks` a u16,
 * so a first chunk could claim 65535 pieces and ask a receiver to track
 * them; bounding it here means the arrived-set is 32 bytes inside the slot
 * rather than another caller allocation whose size depends on what a
 * stranger said. 256 chunks against frame.situ's placeholder 1024-byte
 * payload is 256 KiB, which is generous for a `status` and small enough
 * that a router can afford several. */
#define FZN_REASM_MAX_CHUNKS 256u

typedef enum fzn_reasm_err {
	FZN_REASM_OK = 0,
	FZN_REASM_ERR_MALFORMED = -1,
	/* No slot is free. See fzn_reasm_accept -- refusing is deliberate.
	 *
	 * IT NO LONGER MEANS "live, unexpired", which this said until slots
	 * grew two other reasons to be held. A slot may be HANDED -- completed
	 * and waiting on the caller to release it, which the sweep must not
	 * take -- and a slot's deadline is now bounded by `max_hold` rather
	 * than by the chunk's claim alone. Both are live and neither is
	 * reclaimable by waiting, so a consumer reading the old wording would
	 * conclude that time alone fixes a full table. Releasing what it holds
	 * is the other half. */
	FZN_REASM_ERR_FULL = -2,
	/* This sender already holds its quota of slots. */
	FZN_REASM_ERR_QUOTA = -3,
	/* A later chunk disagrees with the first about `chunks` or `sender`,
	 * or its index is out of range, or its payload would overrun what the
	 * first chunk implied. Each is an attack rather than an accident --
	 * see the comment on fzn_reasm_accept. */
	FZN_REASM_ERR_MISMATCH = -4,
	/* This index has already arrived, with different bytes. A byte-
	 * identical repeat is accepted silently, because that is exactly what
	 * a retransmission looks like. */
	FZN_REASM_ERR_CONFLICT = -5,
	/* The message claims more chunks than FZN_REASM_MAX_CHUNKS, or more
	 * bytes than the slot's buffer holds. Refused on the FIRST chunk,
	 * which is the whole point of carrying a total. */
	FZN_REASM_ERR_TOO_LARGE = -6,
	/* The chunk's expiry has passed. */
	FZN_REASM_ERR_EXPIRED = -7,
	/* This table holds no live message for that sender and id. Its own
	 * code because it is not a fault: a caller asking what it still needs
	 * must be able to tell "nothing outstanding" from "I could not look",
	 * and a completed message is released, so an absent one is ordinary. */
	FZN_REASM_ERR_ABSENT = -8,
} fzn_reasm_err_t;

/* One half-finished message. The buffer is the caller's; nothing here
 * allocates, which is sec 4.4's bound expressed as a type rather than as a
 * promise. */
typedef struct fzn_partial {
	uint8_t sender[FZN_SENDER_LEN];
	uint32_t msg;
	uint16_t chunks;   /* the total, taken from the first chunk seen */
	uint16_t arrived;  /* how many distinct indices have landed */
	uint64_t expires_at;
	uint8_t *buf;
	size_t buf_capacity;
	size_t chunk_size; /* every chunk but the last is exactly this */
	size_t bytes;      /* held so far */
	uint8_t seen[FZN_REASM_MAX_CHUNKS / 8u];
	int live;
	/* Set when the message completed and this slot was handed to a caller
	 * through `*out`, cleared by `fzn_reasm_release`.
	 *
	 * WITHOUT IT THE OWNERSHIP PROMISE ABOVE IS FALSE. Completion only set
	 * `*out`; the slot stayed live with its original expiry, so the next
	 * `fzn_reasm_accept` from anybody swept it, released it, and handed the
	 * same slot and the same buffer to the next message. Measured: alice
	 * completes an eight-byte message of 0xAA and the caller queues the
	 * pointer without releasing; bob sends one chunk later; the pointer the
	 * caller still holds reads 0xBB with bob's sender. No overrun, so a
	 * sanitizer is quiet -- the consumer simply attributes bob's bytes to
	 * alice, and neither side gets an error.
	 *
	 * A caller that never releases now exhausts the table and sees FULL.
	 * That is the honest failure and it is the smaller harm: exhaustion is
	 * visible and attributable, silent takeover is neither. It is also the
	 * shape this module already takes everywhere else -- refuse rather than
	 * recycle something somebody may still be reading. */
	int handed;
} fzn_partial_t;

/* A bounded set of half-finished messages. */
typedef struct fzn_reasm {
	fzn_partial_t *slots;
	size_t capacity;
	/* How many slots one sender may hold at once.
	 *
	 * WITHOUT THIS THE OTHER BOUNDS DO NOT HELP. A table that refuses when
	 * full is a table one sender can fill, and then nobody else is served
	 * -- the denial of service moves rather than going away. sec 3 puts an
	 * authenticated frame in front of this path, so a sender is a verified
	 * identity rather than an address, which is what makes a per-sender
	 * quota meaningful instead of a thing to spoof around. */
	size_t per_sender_max;
	/* The longest a half-finished message may occupy a slot, whatever
	 * expiry its chunks claim.
	 *
	 * WITHOUT IT, `expires_at == 0` MEANT NEVER. That value is legitimate
	 * on the wire -- `frame/freshness.h` gives it to a grant, where it
	 * means "no expiry" -- and this module simply held such a slot for
	 * ever. Measured: four partials with `expires_at = 0`, then
	 * `fzn_reasm_expire(UINT64_MAX)` dropped none of them, and a new
	 * sender a century later was refused because every slot was live.
	 *
	 * The two modules read the same wire field and disagreed about its
	 * sentinel: freshness declines to RECORD a zero-expiry frame, so
	 * nothing accumulates; reassembly held one for ever. Only one of them
	 * had noticed the field could be zero.
	 *
	 * So a slot's deadline is `min(expires_at, now + max_hold)`, and a
	 * zero expiry means `now + max_hold` rather than never. It is the same
	 * shape as the replay window's horizon and answers a different
	 * question: not "how long is this command meaningful" but "how long
	 * will I hold half a message", which is properly seconds where the
	 * horizon is minutes.
	 *
	 * Zero is REFUSED at init rather than meaning unlimited, for the
	 * reason `per_sender_max` gives above: an unlimited default is the one
	 * a caller gets by forgetting the field. */
	uint64_t max_hold;
} fzn_reasm_t;

/* Point a table at caller-owned slots. Each slot must already have its
 * buffer set (fzn_reasm_slot_init). `per_sender_max` of 0 is refused rather
 * than meaning unlimited: an unlimited default is the one a caller gets by
 * forgetting the field. */
fzn_reasm_err_t fzn_reasm_init(fzn_reasm_t *table, fzn_partial_t *slots, size_t capacity,
                                size_t per_sender_max, uint64_t max_hold);

/* Give one slot its buffer. Separate from the above because the buffers are
 * usually one block the caller carves up, and threading that through
 * fzn_reasm_init would mean this module deciding the carve. */
fzn_reasm_err_t fzn_reasm_slot_init(fzn_partial_t *slot, uint8_t *buf, size_t capacity);

/* Reclaim slots whose expiry has passed, and report how many. Same argument
 * as frame/freshness.h: expiry is what makes the memory bound survive a
 * quiet period, and a receiver that has gone silent should be able to hand
 * memory back without waiting for a datagram to arrive. */
size_t fzn_reasm_expire(fzn_reasm_t *table, uint64_t now);

/* Offer one chunk.
 *
 * On the FIRST chunk of a message the slot is sized from what that chunk
 * claims -- `chunks` and the payload length -- and refused outright if the
 * total would not fit. wire/frame.situ says why in as many words: sizing
 * from the first piece "is what lets sec 4.4's memory bound be enforced up
 * front instead of after the fact". Discovering the extent as pieces arrive
 * means a stranger chooses how much is held before anyone can object.
 *
 * Every LATER chunk must agree with the first, and each clause is an attack
 * if unchecked -- these are wire/frame.situ's `same_message` relation,
 * enforced here because at rung 3 a relation says whether a pairing is
 * well-formed and does not remember pairings:
 *
 *   - `chunks` differing is an attempt to resize a buffer already allocated
 *     against the first claim;
 *   - `sender` differing splices two senders' chunks into one message that
 *     then authenticates as neither;
 *   - an `index` at or past `chunks` writes outside what was sized.
 *
 * A byte-identical repeat of an index already held is accepted and changes
 * nothing, because that is what a retransmission looks like and refusing it
 * would make loss recovery fail. A DIFFERING repeat is refused: it is an
 * attempt to rewrite part of a message after the rest was accepted.
 *
 * When the message completes, *out is pointed at the slot and the caller
 * owns its bytes until it calls fzn_reasm_release. Until then *out is left
 * NULL, so "did this finish something" needs no second call.
 */
fzn_reasm_err_t fzn_reasm_accept(fzn_reasm_t *table, const uint8_t sender[FZN_SENDER_LEN],
                                  uint32_t msg, uint16_t index, uint16_t chunks,
                                  const uint8_t *payload, size_t payload_len,
                                  uint64_t expires_at, uint64_t now, fzn_partial_t **out);

/* Hand a slot back. Safe on a slot that is already free. */
void fzn_reasm_release(fzn_partial_t *slot);

/* A run of consecutive chunk indices. `count` is never zero in anything this
 * file produces -- an empty range is a second spelling of "nothing", which
 * every caller would then have to test for. */
typedef struct fzn_reasm_range {
	uint16_t first;
	uint16_t count;
} fzn_reasm_range_t;

/*
 * WHICH CHUNKS OF A MESSAGE ARE STILL MISSING, so a receiver can ask for them
 * again.
 *
 * THE STATE WAS ALREADY HERE AND UNREACHABLE. `fzn_partial_t` has carried a
 * `seen` bitmap since reassembly existed, `seen_get` and `seen_set` are
 * static, and `fzn_reasm_accept` points `*out` at a slot only when a message
 * COMPLETES. So a receiver has always known exactly which chunks it lacked
 * and had no way to say so, which is why loss recovery on this path could
 * only ever be "wait and hope the sender repeats itself".
 *
 * netcfgd's shared-protocol brief asks for chunking "with retransmission of
 * missing pieces" and calls it the largest single piece of new work and the
 * highest-risk part. Almost all of it was already built; this is the missing
 * accessor.
 *
 * THE SENDER SIDE NEEDS NOTHING. `fzn_split_at` already yields the bytes for
 * any index and refuses one at or past the total, so a peer answering this
 * walks the ranges and refuses a fabricated index without help.
 *
 * NO `from` ARGUMENT, DELIBERATELY, and the omission is worth stating because
 * `spool/plan.h` has one and the symmetry is tempting. That argument exists
 * there for playback order and to de-correlate a thousand peers fetching one
 * blob. Neither applies to one message from one sender: there is no playhead
 * and there is only ever one peer to ask. Copying an API's shape where its
 * reason does not transfer is how a parameter nobody can explain gets added.
 *
 * `max_per_range` splits a long run, and ZERO IS REFUSED rather than meaning
 * unlimited -- `record/sync.h` refuses a zero bound for the same reason and
 * `spool/plan.c` inherits it rather than re-deciding. Stops at `cap` ranges
 * and reports how many were written.
 *
 * FZN_REASM_ERR_ABSENT when this table holds no live message for that sender
 * and id, which is ordinary rather than a fault -- a completed message has
 * been released.
 */
fzn_reasm_err_t fzn_reasm_plan_want(const fzn_reasm_t *table,
                                     const uint8_t sender[FZN_SENDER_LEN], uint32_t msg,
                                     uint16_t max_per_range, fzn_reasm_range_t *out, size_t cap,
                                     size_t *count);

/* A short name for `fzn_reasm_err_t`, for a log line or a message to a user.
 *
 * NEVER NULL, including for a value that is not one of the enumerators, so
 * that a caller may pass the result straight to a printf without a check.
 * An unrecognised value renders as "unknown", which is deliberately not any
 * real code's text -- a caller that cannot tell "we do not know" from a
 * genuine answer is the failure this whole library is careful about
 * elsewhere.
 *
 * The strings are lowercase, carry no trailing punctuation and name the
 * condition rather than restating the constant, on the same reasoning as
 * strerror: the caller supplies the sentence, this supplies the noun. */
const char *fzn_reasm_err_str(fzn_reasm_err_t err);

#endif /* FZN_REASSEMBLY_H */
