/* Tests for blob/blob.c: leaf key derivation, sealing, the streaming tree
 * and inclusion proofs.
 *
 * THE TREE'S SHAPE IS CHECKED AGAINST A SECOND IMPLEMENTATION, not against
 * a frozen vector. A vector generated by running this library would be one
 * witness wearing two hats -- evidence.md's rule about corroboration -- and
 * there is no published vector to cite, because the tree is over this
 * library's own sealed leaves. So the reference below is written from RFC
 * 6962's recursive definition directly: split at the largest power of two
 * strictly less than n, hash the halves. The implementation is a streaming
 * binary counter and looks nothing like it, which is what makes agreement
 * mean something.
 *
 * THE STUB HASH IS NOT A HASH and does not need to be. What every case here
 * asks is whether the right bytes reached the right call in the right order,
 * and for that a mixing function that depends on every input byte and on the
 * requested length is enough. Two cases need more and say so where they are.
 */

#include "../blob.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

static int failures;
static int checks;

#if defined(__GNUC__)
#define FZN_CHECK_PRINTF __attribute__((format(printf, 3, 4)))
#else
#define FZN_CHECK_PRINTF
#endif

static void check_at(int ok, int line, const char *fmt, ...) FZN_CHECK_PRINTF;

static void check_at(int ok, int line, const char *fmt, ...)
{
	va_list ap;

	checks++;
	if (ok)
		return;

	failures++;
	fprintf(stderr, "  FAIL blob_test.c:%d: ", line);
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fprintf(stderr, "\n");
}

#define CHECK(cond, ...) check_at((cond) ? 1 : 0, __LINE__, __VA_ARGS__)

/* ---- the stubs -------------------------------------------------------- */

/* A mixing function over every input byte, the requested length and the
 * output position. Not a hash: it is trivially invertible and has no
 * collision resistance worth the name. What it must do is DEPEND ON
 * EVERYTHING -- a stub that ignored a byte would make "this field is in the
 * transcript" a question with no observable answer, which is the failure
 * these suites keep finding in each other. */
static int stub_hash(void *ctx, uint8_t *out, size_t out_len, const uint8_t *in, size_t in_len)
{
	uint64_t h = 0xcbf29ce484222325ull;
	size_t i;

	(void)ctx;
	if (!out || !in)
		return 0;

	h ^= (uint64_t)out_len;
	h *= 0x100000001b3ull;
	for (i = 0; i < in_len; i++) {
		h ^= in[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < out_len; i++) {
		h ^= (uint64_t)i + 0x9e3779b97f4a7c15ull;
		h *= 0x100000001b3ull;
		out[i] = (uint8_t)(h >> 32);
	}
	return 1;
}

/* A hash that refuses, for the paths that must carry a refusal out rather
 * than proceed with a buffer nobody filled. */
static int refusing_hash(void *ctx, uint8_t *out, size_t out_len, const uint8_t *in,
                         size_t in_len)
{
	(void)ctx;
	(void)out;
	(void)out_len;
	(void)in;
	(void)in_len;
	return 0;
}

/* A toy AEAD: a keystream from the key and nonce, and a tag over key, nonce,
 * aad and ciphertext. Real enough that a changed byte anywhere changes the
 * tag, which is all any case here asks of it. */
static void stream(const uint8_t *key, const uint8_t *nonce, uint8_t *text, size_t len)
{
	uint64_t h = 0x243f6a8885a308d3ull;
	size_t i;

	for (i = 0; i < FZN_AEAD_KEY_LEN; i++) {
		h ^= key[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_NONCE_LEN; i++) {
		h ^= nonce[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < len; i++) {
		h ^= (uint64_t)i;
		h *= 0x100000001b3ull;
		text[i] ^= (uint8_t)(h >> 24);
	}
}

static void tag_over(const uint8_t *key, const uint8_t *nonce, const uint8_t *aad,
                     size_t aad_len, const uint8_t *text, size_t text_len,
                     uint8_t tag[FZN_AEAD_TAG_LEN])
{
	uint64_t h = 0xff51afd7ed558ccdull;
	size_t i;

	for (i = 0; i < FZN_AEAD_KEY_LEN; i++) {
		h ^= key[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_NONCE_LEN; i++) {
		h ^= nonce[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < aad_len; i++) {
		h ^= aad[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < text_len; i++) {
		h ^= text[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_TAG_LEN; i++) {
		h ^= (uint64_t)i + 0x2545f4914f6cdd1dull;
		h *= 0x100000001b3ull;
		tag[i] = (uint8_t)(h >> 40);
	}
}

static int stub_seal(void *ctx, const uint8_t key[FZN_AEAD_KEY_LEN],
                     const uint8_t nonce[FZN_AEAD_NONCE_LEN], const uint8_t *aad,
                     size_t aad_len, uint8_t *text, size_t text_len,
                     uint8_t tag[FZN_AEAD_TAG_LEN])
{
	(void)ctx;
	stream(key, nonce, text, text_len);
	tag_over(key, nonce, aad, aad_len, text, text_len, tag);
	return 1;
}

static int stub_open(void *ctx, const uint8_t key[FZN_AEAD_KEY_LEN],
                     const uint8_t nonce[FZN_AEAD_NONCE_LEN], const uint8_t *aad,
                     size_t aad_len, uint8_t *text, size_t text_len,
                     const uint8_t tag[FZN_AEAD_TAG_LEN])
{
	uint8_t want[FZN_AEAD_TAG_LEN];

	(void)ctx;
	tag_over(key, nonce, aad, aad_len, text, text_len, want);
	if (memcmp(want, tag, FZN_AEAD_TAG_LEN) != 0)
		return 0;
	stream(key, nonce, text, text_len);
	return 1;
}

static const fzn_hash_ops_t HASH = { stub_hash, NULL };
static const fzn_hash_ops_t REFUSER = { refusing_hash, NULL };
static const fzn_aead_ops_t AEAD = { stub_seal, stub_open, NULL };

/* ---- the reference tree ----------------------------------------------- */

/* RFC 6962's Merkle Tree Hash, written recursively and directly from the
 * definition, over an array of leaf hashes.
 *
 * IT IS NOT THE IMPLEMENTATION WITH THE NAMES CHANGED. blob.c pushes leaves
 * into a binary-counter stack and folds the remainder right-to-left at the
 * end; this splits at the largest power of two below n and recurses. The two
 * arrive at the same tree for every n or one of them is wrong, and that is
 * the assertion.
 *
 * Recursion is fine here and not in the library: this is a test over at most
 * a few hundred leaves, and the library's rule about bounded stacks exists
 * for bytes that arrive from strangers. */
static void reference_apex(const uint8_t *leaves, uint64_t n, uint8_t out[FZN_BLOB_HASH_LEN])
{
	uint8_t left[FZN_BLOB_HASH_LEN];
	uint8_t right[FZN_BLOB_HASH_LEN];
	uint64_t k = 1u;

	if (n == 1u) {
		memcpy(out, leaves, FZN_BLOB_HASH_LEN);
		return;
	}
	while ((k << 1) < n)
		k <<= 1;

	reference_apex(leaves, k, left);
	reference_apex(leaves + ((size_t)k * FZN_BLOB_HASH_LEN), n - k, right);
	(void)fzn_blob_node_hash(&HASH, left, right, out);
}

/* The finaliser, written out here rather than called, because the library's
 * is `static` and because a reference that called it would agree with it by
 * construction. The label is spelled again for the same reason -- if the two
 * copies ever disagree the tests fail, which is the point of having two. */
#define REQUIRE_BLOB(call, what)                             \
	do {                                                 \
		fzn_blob_err_t require_err = (call);         \
		CHECK(require_err == FZN_BLOB_OK, "%s: %d",  \
		      (what), (int)require_err);             \
		if (require_err != FZN_BLOB_OK)              \
			return;                              \
	} while (0)

/* The bare apex over `n` leaves: what an interior node of the tree holds,
 * with none of the root's label or leaf-count binding. `reference_root`
 * finalises; a span is not a blob and must not be finalised. */
static void apex_of(const uint8_t *leaves, uint64_t n, uint8_t out[FZN_BLOB_HASH_LEN])
{
	fzn_blob_tree_t tree;
	uint64_t i;

	fzn_blob_tree_init(&tree);
	for (i = 0; i < n; i++)
		(void)fzn_blob_tree_push(&HASH, &tree,
		                         leaves + ((size_t)i * FZN_BLOB_HASH_LEN));
	/* Fold the stack the way the builder does, right to left. */
	memcpy(out, tree.stack[tree.depth - 1u], FZN_BLOB_HASH_LEN);
	for (i = (uint64_t)tree.depth - 1u; i > 0u; i--)
		(void)fzn_blob_node_hash(&HASH, tree.stack[i - 1u], out, out);
}

static void reference_root(const uint8_t *leaves, uint64_t n, uint8_t out[FZN_BLOB_HASH_LEN])
{
	uint8_t apex[FZN_BLOB_HASH_LEN];
	uint8_t input[16u + 8u + FZN_BLOB_HASH_LEN];
	static const char label[16] = "fuzznet-root-v1\0";
	size_t i;

	reference_apex(leaves, n, apex);
	memcpy(input, label, sizeof(label));
	for (i = 0; i < 8u; i++)
		input[16u + i] = (uint8_t)(n >> ((7u - i) * 8u));
	memcpy(input + 24u, apex, FZN_BLOB_HASH_LEN);
	(void)stub_hash(NULL, out, FZN_BLOB_HASH_LEN, input, sizeof(input));
}

/* Fills `out` with `n` distinct leaf hashes, derived so that no two agree
 * and none is a constant a bug could match by accident. */
static void make_leaves(uint8_t *out, uint64_t n)
{
	uint64_t i;
	size_t j;

	for (i = 0; i < n; i++)
		for (j = 0; j < FZN_BLOB_HASH_LEN; j++)
			out[((size_t)i * FZN_BLOB_HASH_LEN) + j] =
			        (uint8_t)((i * 131u) + (j * 7u) + 1u);
}

static fzn_blob_err_t streamed_root(const uint8_t *leaves, uint64_t n,
                                     uint8_t out[FZN_BLOB_HASH_LEN])
{
	fzn_blob_tree_t tree;
	uint64_t i;
	fzn_blob_err_t err;

	fzn_blob_tree_init(&tree);
	for (i = 0; i < n; i++) {
		err = fzn_blob_tree_push(&HASH, &tree,
		                         leaves + ((size_t)i * FZN_BLOB_HASH_LEN));
		if (err != FZN_BLOB_OK)
			return err;
	}
	return fzn_blob_tree_root(&HASH, &tree, out);
}

/* ---- the cases -------------------------------------------------------- */

#define MAX_TEST_LEAVES 130u

static void test_the_streaming_tree_agrees_with_the_definition(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t want[FZN_BLOB_HASH_LEN];
	uint8_t got[FZN_BLOB_HASH_LEN];
	uint64_t n;

	make_leaves(leaves, MAX_TEST_LEAVES);

	/* EVERY n UP TO 130, not a sample. The shapes that differ are the
	 * ones that are not powers of two, and the ones that catch a
	 * fold-direction error are the ones just past a power of two -- so a
	 * sample chosen by hand is a sample chosen to pass. 130 covers two
	 * powers of two, both their successors, and 129, where the stack has
	 * two entries whose heights differ by seven. */
	for (n = 1u; n <= MAX_TEST_LEAVES; n++) {
		reference_root(leaves, n, want);
		CHECK(streamed_root(leaves, n, got) == FZN_BLOB_OK,
		      "the streaming tree refused %llu leaves", (unsigned long long)n);
		CHECK(memcmp(want, got, FZN_BLOB_HASH_LEN) == 0,
		      "the streaming tree and the definition disagree at %llu leaves",
		      (unsigned long long)n);
	}
}

static void test_a_tree_with_no_leaves_has_no_root(void)
{
	fzn_blob_tree_t tree;
	uint8_t root[FZN_BLOB_HASH_LEN];

	fzn_blob_tree_init(&tree);
	CHECK(fzn_blob_tree_root(&HASH, &tree, root) == FZN_BLOB_ERR_MALFORMED,
	      "an empty tree produced a root, so every empty file shares an id");
}

static void test_the_leaf_and_node_prefixes_stop_a_forgery(void)
{
	uint8_t leaves[2u * FZN_BLOB_HASH_LEN];
	uint8_t node[FZN_BLOB_HASH_LEN];
	uint8_t as_leaf[FZN_BLOB_HASH_LEN];
	uint8_t forged[2u * FZN_BLOB_HASH_LEN];

	/* THE TEXTBOOK SECOND-PREIMAGE ATTACK, built rather than described.
	 * An interior node hashes 64 bytes of children. Those same 64 bytes
	 * are a perfectly good sealed leaf, so a tree whose leaf is "the
	 * concatenation of a and b" would have the same root as a tree whose
	 * two leaves are a and b -- and the KEYLESS verifier, which is what a
	 * relay uses, cannot tell them apart.
	 *
	 * The prefixes are what separates them, and this case is the only
	 * thing standing between them and being deleted as decoration.
	 * Measured: with FZN_BLOB_NODE_PREFIX set equal to
	 * FZN_BLOB_LEAF_PREFIX, the two hashes below are identical. */
	make_leaves(leaves, 2u);
	CHECK(fzn_blob_node_hash(&HASH, leaves, leaves + FZN_BLOB_HASH_LEN, node) == FZN_BLOB_OK,
	      "the node hash refused");

	memcpy(forged, leaves, sizeof(forged));
	CHECK(fzn_blob_leaf_hash(&HASH, forged, sizeof(forged), as_leaf) == FZN_BLOB_OK,
	      "hashing 64 bytes as a leaf refused");

	CHECK(memcmp(node, as_leaf, FZN_BLOB_HASH_LEN) != 0,
	      "an interior node and a leaf over the same bytes hash alike, so the tree "
	      "is second-preimage weak and a relay would serve the forgery");
}

static void test_distinct_leaf_counts_give_distinct_roots(void)
{
	static uint8_t leaves[16u * FZN_BLOB_HASH_LEN];
	uint8_t roots[9][FZN_BLOB_HASH_LEN];
	uint8_t dup[4u * FZN_BLOB_HASH_LEN];
	uint8_t dup_root[FZN_BLOB_HASH_LEN];
	uint64_t a;
	uint64_t b;

	/* ONE SHARED LEAF ARRAY, walked from 1 to 8, so every pair of trees
	 * AGREES ON A PREFIX and differs only in how far it runs -- the
	 * truncation shape exactly, and a construction that does not happen
	 * by accident. Taken from fuzzypickles'
	 * test_distinct_leaf_counts_give_distinct_roots.
	 *
	 * AND IT DOES NOT PROVE WHAT THEIRS PROVES, WHICH IS THE POINT OF
	 * SAYING SO. Measured, by removing the count from the finaliser AND
	 * from the reference together: this case still passes. It has to.
	 * This tree does not pad, so a tree over three leaves and one over
	 * four have different APEXES whatever the finaliser does, and no
	 * amount of shared prefix changes that. In fuzzypickles the same
	 * assertion is load-bearing because they DO pad, and padding is
	 * exactly what can make two counts fold to one apex.
	 *
	 * The case that discriminates here is the proof verified against a
	 * different leaf count, in test_a_proof_that_is_wrong_is_refused, and
	 * under that mutation it is the ONLY case in this file that fails.
	 * Kept anyway, because "we do not pad" is a property somebody can
	 * change and this is what would notice.
	 *
	 * The general form is worth more than the instance: adopting a
	 * sibling's test brings its rationale with it, and a rationale is
	 * true of the construction it was written for. */
	make_leaves(leaves, 16u);
	for (a = 1u; a <= 8u; a++)
		CHECK(streamed_root(leaves, a, roots[a]) == FZN_BLOB_OK,
		      "the tree over %llu leaves refused", (unsigned long long)a);

	for (a = 1u; a <= 8u; a++)
		for (b = a + 1u; b <= 8u; b++)
			CHECK(memcmp(roots[a], roots[b], FZN_BLOB_HASH_LEN) != 0,
			      "trees over %llu and %llu leaves share a root, so a blob id "
			      "does not commit to its length",
			      (unsigned long long)a, (unsigned long long)b);

	/* CVE-2012-2459, BY NAME. Bitcoin's Merkle tree duplicated a final
	 * odd leaf, so a tree over three leaves and one over four whose
	 * fourth repeats the third had the same root -- two different blocks
	 * with one id. This tree does not pad and so does not have that bug
	 * by construction; the case is here anyway, because "we do not pad"
	 * is a property somebody can change and this is what would notice. */
	memcpy(dup, leaves, 3u * FZN_BLOB_HASH_LEN);
	memcpy(dup + (3u * FZN_BLOB_HASH_LEN), leaves + (2u * FZN_BLOB_HASH_LEN),
	       FZN_BLOB_HASH_LEN);
	CHECK(streamed_root(dup, 4u, dup_root) == FZN_BLOB_OK, "the duplicate tree refused");
	CHECK(memcmp(roots[3], dup_root, FZN_BLOB_HASH_LEN) != 0,
	      "a three-leaf tree and a four-leaf tree repeating its last leaf share a "
	      "root -- CVE-2012-2459");
}


/* EVERY CANONICAL SPAN OF EVERY TREE UP TO 33, verified against the same
 * root the per-leaf proofs verify against.
 *
 * The property is the one the whole addressing decision rests on: a span
 * proof and a leaf proof must agree about the tree. If they can disagree,
 * a propagation layer verifying batches accepts what a receiver verifying
 * leaves rejects, or the reverse, and the two halves of this library would
 * be describing different trees.
 *
 * Exhaustive rather than sampled because canonicity is where the subtlety
 * is: the tree splits at the largest power of two strictly below n, so for
 * a non-power-of-two blob the right-hand subtrees are NOT power-of-two
 * sized, and "aligned range" is the wrong test. The cases that matter are
 * the ones an aligned-range test would get wrong, and they only appear at
 * particular n.
 */
static void test_every_canonical_span_reaches_the_root(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN];
	uint8_t span_root[FZN_BLOB_HASH_LEN];
	unsigned count;
	uint64_t n, first, len;
	unsigned canonical_seen = 0u;
	unsigned whole_blob_seen = 0u;
	unsigned single_leaf_seen = 0u;

	make_leaves(leaves, MAX_TEST_LEAVES);

	for (n = 1u; n <= 33u; n++) {
		reference_root(leaves, n, root);
		for (first = 0u; first < n; first++) {
			for (len = 1u; first + len <= n; len++) {
				int canon = fzn_blob_span_is_canonical(n, first, len);
				fzn_blob_err_t built = fzn_blob_span_proof_build(
				        &HASH, leaves, n, first, len, siblings,
				        sizeof(siblings), &count);

				/* THE PREDICATE AND THE BUILDER ARE ONE
				 * DEFINITION. If they could disagree, a server
				 * would accept a request it cannot prove. */
				CHECK((built == FZN_BLOB_OK) == (canon != 0),
				      "is_canonical and proof_build disagree about "
				      "[%llu,%llu) of %llu",
				      (unsigned long long)first,
				      (unsigned long long)(first + len),
				      (unsigned long long)n);
				if (!canon)
					continue;
				canonical_seen++;
				if (len == n)
					whole_blob_seen++;
				if (len == 1u)
					single_leaf_seen++;

				/* The receiver computes the span's root from
				 * the leaves it holds -- it never takes it
				 * from the prover. */
				/* THE SPAN'S ROOT IS THE BARE APEX over its own
				 * leaves -- an interior node, with no root
				 * label and no leaf-count binding, because
				 * those belong to the whole blob. `apex_of`
				 * is the test's own so that this case does
				 * not depend on which of the two a public
				 * call happens to return. */
				apex_of(leaves + ((size_t)first * FZN_BLOB_HASH_LEN), len,
				        span_root);
				CHECK(fzn_blob_span_proof_verify(&HASH, span_root, first, len, n,
				                                 siblings, count, root)
				      == FZN_BLOB_OK,
				      "canonical span [%llu,%llu) of %llu does not verify",
				      (unsigned long long)first,
				      (unsigned long long)(first + len),
				      (unsigned long long)n);
			}
		}
	}

	/* THE POPULATION IS ASSERTED, not just the cases. A predicate that
	 * answered "no" to everything would satisfy every check above by
	 * making the loop body unreachable. */
	CHECK(canonical_seen > 100u, "only %u canonical spans found, so the sweep is empty",
	      canonical_seen);
	CHECK(whole_blob_seen == 33u, "the whole blob is not canonical at every size");
	CHECK(single_leaf_seen == 561u,
	      "every single leaf must be a canonical span: expected 561, saw %u",
	      single_leaf_seen);
}

/* A SPAN THAT STRADDLES THE SPLIT HAS NO PROOF, and the refusal is the point:
 * "leaves 1 and 2 of a four-leaf tree" is a perfectly sensible request and is
 * not a node of the tree, so no single proof covers it. A server that built
 * one anyway would be proving a different set. */

/* A PROOF OF THE WRONG LENGTH IS REFUSED, and nothing above reached this
 * because every case passes back the count the builder returned.
 *
 * The depth is a function of the claim -- leaf_count, first and count -- so a
 * prover sending more or fewer siblings is describing a different tree. A
 * verifier that used as many as it was given would climb a different number
 * of levels and could be steered by the framing, which is the thing the
 * "descent computed from the claim, never read from the proof" rule exists to
 * prevent. */
static void test_a_span_proof_of_the_wrong_length_is_refused(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN], span_root[FZN_BLOB_HASH_LEN];
	unsigned count;

	make_leaves(leaves, MAX_TEST_LEAVES);
	reference_root(leaves, 16u, root);
	apex_of(leaves, 4u, span_root);

	REQUIRE_BLOB(fzn_blob_span_proof_build(&HASH, leaves, 16u, 0u, 4u, siblings,
	                                       sizeof(siblings), &count),
	             "building the span proof");
	CHECK(count == 2u, "a 4-leaf span of a 16-leaf blob should be 2 siblings, saw %u",
	      count);
	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 4u, 16u, siblings, count, root)
	      == FZN_BLOB_OK, "the honest proof does not verify");

	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 4u, 16u, siblings, count - 1u,
	                                 root) == FZN_BLOB_ERR_SHAPE,
	      "a proof one sibling short was accepted");
	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 4u, 16u, siblings, count + 1u,
	                                 root) == FZN_BLOB_ERR_SHAPE,
	      "a proof one sibling long was accepted");
	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 4u, 16u, siblings, 0u, root)
	      == FZN_BLOB_ERR_SHAPE, "an empty proof was accepted for a span that needs two");

	/* AND THE WHOLE BLOB IS THE ZERO-SIBLING CASE, which must still be
	 * accepted -- so the check above is about the length matching the
	 * claim rather than about zero being suspicious. */
	apex_of(leaves, 16u, span_root);
	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 16u, 16u, siblings, 0u, root)
	      == FZN_BLOB_OK, "the whole blob as a span needs no siblings and was refused");

	/* A DIFFERENT LEAF COUNT IS A DIFFERENT TREE. Same span, same proof,
	 * a count the prover chose: refused, because the descent is recomputed
	 * from the claim. */
	REQUIRE_BLOB(fzn_blob_span_proof_build(&HASH, leaves, 16u, 0u, 4u, siblings,
	                                       sizeof(siblings), &count),
	             "rebuilding the span proof");
	apex_of(leaves, 4u, span_root);
	CHECK(fzn_blob_span_proof_verify(&HASH, span_root, 0u, 4u, 17u, siblings, count, root)
	      != FZN_BLOB_OK, "a span verified against a blob of a different size");
}


/* THE GREEDY COVER TERMINATES AND EVERY PIECE IS PROVABLE.
 *
 * `fzn_blob_span_largest_at` is what turns a bitmap's arbitrary run into
 * requests a single proof can cover, so two things have to hold for every
 * position of every tree: what it returns is canonical, and it is never zero
 * for a leaf that exists -- because a planner that got zero would either stall
 * or fall back to per-leaf requests, which is the 62% it exists to avoid.
 *
 * A single leaf is always a canonical span, so the floor is 1 and the walk
 * cannot fail to make progress. That is the termination argument and it is
 * checked rather than asserted. */
static void test_the_largest_span_at_every_position_is_canonical(void)
{
	uint64_t n, first, cap, got;
	unsigned took_more_than_one = 0u;

	for (n = 1u; n <= 33u; n++) {
		for (first = 0u; first < n; first++) {
			for (cap = 1u; cap <= 8u; cap++) {
				got = fzn_blob_span_largest_at(n, first, cap);
				CHECK(got >= 1u,
				      "no span at leaf %llu of %llu under cap %llu, so a "
				      "planner would stall",
				      (unsigned long long)first, (unsigned long long)n,
				      (unsigned long long)cap);
				CHECK(got <= cap, "span %llu exceeds the cap %llu",
				      (unsigned long long)got, (unsigned long long)cap);
				CHECK(fzn_blob_span_is_canonical(n, first, got),
				      "the largest span at %llu of %llu under %llu is not "
				      "canonical",
				      (unsigned long long)first, (unsigned long long)n,
				      (unsigned long long)cap);
				if (got > 1u)
					took_more_than_one++;
			}
		}
	}

	/* THE POPULATION AGAIN. A function that always returned 1 would pass
	 * every check above and buy nothing -- the whole point is that it
	 * takes big bites where it can. */
	CHECK(took_more_than_one > 200u,
	      "only %u positions took a span longer than one leaf, so the cover is "
	      "per-leaf in all but name", took_more_than_one);

	/* AND A GREEDY WALK COVERS A WHOLE BLOB EXACTLY. */
	{
		uint64_t at = 0u, pieces = 0u;

		while (at < 33u) {
			got = fzn_blob_span_largest_at(33u, at, 64u);
			REQUIRE_BLOB(got >= 1u ? FZN_BLOB_OK : FZN_BLOB_ERR_SHAPE,
			             "the greedy walk stalled");
			at += got;
			pieces++;
			CHECK(pieces <= 33u, "the walk is not terminating");
		}
		CHECK(at == 33u, "the greedy cover overshot: %llu", (unsigned long long)at);
		CHECK(pieces < 33u, "the cover took %llu pieces for 33 leaves, so it is "
		      "per-leaf", (unsigned long long)pieces);
	}
}

static void test_a_straddling_span_is_refused(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	unsigned count;

	make_leaves(leaves, MAX_TEST_LEAVES);

	CHECK(!fzn_blob_span_is_canonical(4u, 1u, 2u),
	      "[1,3) of 4 straddles the split and was called canonical");
	CHECK(fzn_blob_span_proof_build(&HASH, leaves, 4u, 1u, 2u, siblings, sizeof(siblings),
	                                &count) == FZN_BLOB_ERR_SHAPE,
	      "a straddling span was given a proof");
	/* And the halves either side of it are canonical, so the refusal is
	 * about the straddle rather than about the size. */
	CHECK(fzn_blob_span_is_canonical(4u, 0u, 2u), "[0,2) of 4 should be canonical");
	CHECK(fzn_blob_span_is_canonical(4u, 2u, 2u), "[2,4) of 4 should be canonical");

	/* AN UNBALANCED TREE IS WHERE "ALIGNED" WOULD BE WRONG. Five leaves
	 * split 4 + 1, so [4,5) is canonical and [2,4) -- aligned, and a node
	 * of a BALANCED tree of that size -- is too, while [1,3) is not. */
	CHECK(fzn_blob_span_is_canonical(5u, 4u, 1u), "[4,5) of 5 should be canonical");
	CHECK(fzn_blob_span_is_canonical(5u, 0u, 4u), "[0,4) of 5 should be canonical");
	CHECK(!fzn_blob_span_is_canonical(5u, 3u, 2u),
	      "[3,5) of 5 straddles 5's split at 4 and was called canonical");
}

static void test_a_proof_reaches_the_root(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN];
	unsigned count;
	uint64_t n;
	uint64_t i;

	make_leaves(leaves, MAX_TEST_LEAVES);

	/* EVERY LEAF OF EVERY TREE up to 33, because a proof that works for
	 * the first leaf and the last is the one a hand-written case would
	 * check, and the interesting index is the one whose path crosses an
	 * incomplete subtree. */
	for (n = 1u; n <= 33u; n++) {
		reference_root(leaves, n, root);
		for (i = 0; i < n; i++) {
			CHECK(fzn_blob_proof_build(&HASH, leaves, n, i, siblings,
			                           sizeof(siblings), &count) == FZN_BLOB_OK,
			      "building a proof for leaf %llu of %llu refused",
			      (unsigned long long)i, (unsigned long long)n);
			CHECK(fzn_blob_proof_verify(&HASH,
			                            leaves + ((size_t)i * FZN_BLOB_HASH_LEN), i,
			                            n, siblings, count, root) == FZN_BLOB_OK,
			      "leaf %llu of %llu does not verify against its own root",
			      (unsigned long long)i, (unsigned long long)n);
		}
	}
}

static void test_a_proof_that_is_wrong_is_refused(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN];
	unsigned count;
	const uint64_t n = 11u;
	const uint64_t index = 4u;

	make_leaves(leaves, MAX_TEST_LEAVES);
	reference_root(leaves, n, root);
	CHECK(fzn_blob_proof_build(&HASH, leaves, n, index, siblings, sizeof(siblings),
	                           &count) == FZN_BLOB_OK,
	      "the positive control did not build, so every refusal below proves nothing");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count, root) == FZN_BLOB_OK,
	      "the positive control does not verify, so every refusal below proves nothing");

	/* A DIFFERENT LEAF, same proof. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves, index, n, siblings, count, root)
	              == FZN_BLOB_ERR_PROOF,
	      "another leaf verified at index %llu", (unsigned long long)index);

	/* THE SAME LEAF AT A DIFFERENT INDEX, which is the reordering a
	 * content-addressed store must refuse: index decides the shape of the
	 * climb, so a leaf that moved cannot reach the same root. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index + 1u, n,
	                            siblings, count, root) == FZN_BLOB_ERR_PROOF,
	      "a leaf verified at an index it does not occupy");

	/* A DIFFERENT LEAF COUNT, AND THE HISTORY IS WORTH THE PARAGRAPH.
	 *
	 * This case was written asserting flatly that a proof does not verify
	 * against a tree of another size. It FAILED, correctly: leaf 4 sits
	 * inside the complete left subtree of eight, identical in a tree of
	 * 11 and one of 12, so path, siblings and apex all matched and the
	 * proof was genuinely valid for both. The assertion was relaxed and
	 * the caveat written into blob.h -- whatever carries a blob id must
	 * carry its length under the same signature.
	 *
	 * fuzzypickles read that and answered with their finaliser, which
	 * binds the leaf count into the root. The caveat is gone and this
	 * assertion is true again, unconditionally and without a rule anybody
	 * has to remember. Kept in this shape as the case that discriminates:
	 * it passes only because the count is bound, and it is what fails if
	 * the finaliser ever stops binding it.
	 */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n + 1u,
	                            siblings, count, root) == FZN_BLOB_ERR_PROOF,
	      "a proof verified against a tree of a different size, so the root does not "
	      "commit to the leaf count and a receiver can be walked to a truncation");

	{
		uint8_t edge_sib[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
		unsigned edge_count;
		const uint64_t edge = 10u;

		CHECK(fzn_blob_proof_build(&HASH, leaves, n, edge, edge_sib, sizeof(edge_sib),
		                           &edge_count) == FZN_BLOB_OK,
		      "building the edge proof refused");
		CHECK(fzn_blob_proof_verify(&HASH, leaves + (edge * FZN_BLOB_HASH_LEN), edge, n,
		                            edge_sib, edge_count, root) == FZN_BLOB_OK,
		      "the edge control does not verify against its own tree");
		CHECK(fzn_blob_proof_verify(&HASH, leaves + (edge * FZN_BLOB_HASH_LEN), edge,
		                            n + 1u, edge_sib, edge_count, root)
		              == FZN_BLOB_ERR_PROOF,
		      "a proof for the last leaf of an 11-leaf tree verified against a "
		      "12-leaf one");
	}

	/* ONE SIBLING CORRUPTED, at every position in turn: a verifier that
	 * only consulted the first or the last would pass most of these. */
	{
		unsigned i;

		for (i = 0; i < count; i++) {
			uint8_t bent[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];

			memcpy(bent, siblings, sizeof(bent));
			bent[i * FZN_BLOB_HASH_LEN] = (uint8_t)(bent[i * FZN_BLOB_HASH_LEN] ^ 1u);
			CHECK(fzn_blob_proof_verify(&HASH,
			                            leaves + (index * FZN_BLOB_HASH_LEN), index,
			                            n, bent, count, root) == FZN_BLOB_ERR_PROOF,
			      "a proof with sibling %u bent by one bit still verified", i);
		}
	}

	/* TOO FEW AND TOO MANY SIBLINGS. Short of the root and past it are
	 * different mistakes and both are refusals. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count - 1u, root) == FZN_BLOB_ERR_PROOF,
	      "a proof one sibling short verified");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count + 1u, root) == FZN_BLOB_ERR_PROOF,
	      "a proof with a sibling too many verified");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, FZN_BLOB_MAX_DEPTH + 1u, root)
	              == FZN_BLOB_ERR_SHAPE,
	      "a proof deeper than the bound was not refused as a shape");
}

static void test_sealing_is_deterministic_and_reversible(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[FZN_BLOB_LEAF_SIZE];
	uint8_t first[FZN_BLOB_SEALED_MAX];
	uint8_t second[FZN_BLOB_SEALED_MAX];
	uint8_t back[FZN_BLOB_LEAF_SIZE];
	size_t first_len = 0;
	size_t second_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 3u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i * 17u);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), first,
	                         sizeof(first), &first_len) == FZN_BLOB_OK,
	      "sealing a full leaf refused");
	CHECK(first_len == sizeof(plain) + FZN_BLOB_LEAF_OVERHEAD,
	      "a sealed leaf is %zu bytes, wanted %zu", first_len,
	      sizeof(plain) + FZN_BLOB_LEAF_OVERHEAD);

	/* DETERMINISTIC, which is the property dedup rests on: two people
	 * holding the same file must produce the same bytes and therefore the
	 * same id, or they seed two swarms. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), second,
	                         sizeof(second), &second_len) == FZN_BLOB_OK,
	      "sealing the same leaf twice refused the second time");
	CHECK(first_len == second_len && memcmp(first, second, first_len) == 0,
	      "sealing the same content under the same key twice gave different bytes");

	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 7u, first, first_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_OK,
	      "a leaf this library sealed does not open");
	CHECK(back_len == sizeof(plain) && memcmp(back, plain, sizeof(plain)) == 0,
	      "the opened leaf is not the plaintext");
}

static void test_a_leaf_is_bound_to_its_index(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[64];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t elsewhere[FZN_BLOB_SEALED_MAX];
	uint8_t back[64];
	size_t sealed_len = 0;
	size_t other_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 11u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i + 1u);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 3u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing at index 3 refused");

	/* THE INDEX IS INSIDE THE DERIVATION, not only in the nonce. So a
	 * leaf lifted from position 3 and replayed at 7 does not derive the
	 * same key at all, and is refused at the COMMITMENT -- before the
	 * AEAD, and without depending on the Merkle root having been checked,
	 * which a peer serving from a partial cache may not have done. */
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 7u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_COMMITMENT,
	      "a leaf lifted from index 3 opened at index 7");

	/* And the same content at two indices seals to different bytes, which
	 * is the same fact from the writing side. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), elsewhere,
	                         sizeof(elsewhere), &other_len) == FZN_BLOB_OK,
	      "sealing at index 7 refused");
	CHECK(sealed_len == other_len && memcmp(sealed, elsewhere, sealed_len) != 0,
	      "the same content sealed identically at two indices");
}

static void test_the_commitment_is_checked_before_the_aead(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[100];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t back[100];
	size_t sealed_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 5u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i ^ 0x5au);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing refused");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_OK,
	      "the positive control does not open, so the refusals below prove nothing");

	/* A BENT COMMITMENT IS ITS OWN ERROR, distinct from the AEAD's. The
	 * two codes are what says the check happened first: if the commitment
	 * were checked after -- or not at all -- this would come back as
	 * AUTH, because the commitment is also the AEAD's aad. */
	sealed[0] = (uint8_t)(sealed[0] ^ 0x80u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_COMMITMENT,
	      "a bent commitment did not come back as a commitment failure, so the "
	      "non-committing AEAD is not being fenced");
	sealed[0] = (uint8_t)(sealed[0] ^ 0x80u);

	/* A BENT CIPHERTEXT IS THE AEAD's, which is the other half of the
	 * same claim: the two errors are reachable independently, so neither
	 * is standing in for the other. */
	sealed[FZN_COMMITMENT_LEN] = (uint8_t)(sealed[FZN_COMMITMENT_LEN] ^ 1u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_AUTH,
	      "a bent ciphertext was not refused by the aead");
}

static void test_a_refused_open_leaves_nothing_usable(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[48];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t back[48];
	size_t sealed_len = 0;
	size_t back_len = 0;
	size_t i;
	int all_zero = 1;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 9u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = 0xa5u;

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 2u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing refused");

	memset(back, 0x11, sizeof(back));
	sealed[sealed_len - 1u] = (uint8_t)(sealed[sealed_len - 1u] ^ 1u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 2u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_AUTH,
	      "a bent tag was accepted");

	/* THE CALLER'S BUFFER HELD CIPHERTEXT WHEN THE AEAD REFUSED, and a
	 * caller who ignores a return value must not find plausible bytes in
	 * it. Wiped rather than left, which is cheap and is the difference
	 * between a bug and a disclosure. */
	for (i = 0; i < sizeof(back); i++)
		if (back[i] != 0u)
			all_zero = 0;
	CHECK(all_zero, "a refused open left bytes in the caller's buffer");
}

static void test_an_empty_leaf_is_refused(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t plain[1] = { 0 };
	size_t sealed_len = 0;

	memset(key, 0x22, sizeof(key));

	/* AN EMPTY FINAL LEAF WOULD GIVE ONE FILE TWO IDS -- with the empty
	 * leaf and without it -- and a content-addressed store may have
	 * exactly one. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, 0, sealed, sizeof(sealed),
	                         &sealed_len) == FZN_BLOB_ERR_MALFORMED,
	      "an empty leaf was sealed, so a file has two encodings");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, FZN_BLOB_LEAF_SIZE + 1u, sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_ERR_MALFORMED,
	      "a leaf larger than the canonical size was sealed");
}

static void test_a_strangers_lengths_are_refused_as_shape(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t sealed[FZN_BLOB_SEALED_MAX + 1u];
	uint8_t back[FZN_BLOB_LEAF_SIZE];
	size_t back_len = 0;

	memset(key, 0x33, sizeof(key));
	memset(sealed, 0x44, sizeof(sealed));

	/* SHAPE, NOT MALFORMED. These are a peer's bytes and arriving wrong
	 * is expected; MALFORMED is reserved for the caller's own bug, and a
	 * caller that logs one and drops the other needs them apart. */
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD, back,
	                         sizeof(back), &back_len) == FZN_BLOB_ERR_SHAPE,
	      "a sealed leaf with no ciphertext at all was not refused as a shape");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sizeof(sealed), back,
	                         sizeof(back), &back_len) == FZN_BLOB_ERR_SHAPE,
	      "a sealed leaf past the canonical size was not refused as a shape");
	CHECK(fzn_blob_leaf_hash(&HASH, sealed, sizeof(sealed), back) == FZN_BLOB_ERR_SHAPE,
	      "hashing an oversized leaf was not refused");
	CHECK(fzn_blob_leaf_hash(&HASH, sealed, 0, back) == FZN_BLOB_ERR_SHAPE,
	      "hashing an empty leaf was not refused");
}

static void test_a_refusing_hash_carries_its_refusal_out(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t aead_key[FZN_AEAD_KEY_LEN];
	uint8_t commitment[FZN_COMMITMENT_LEN];
	uint8_t out[FZN_BLOB_HASH_LEN];
	uint8_t leaves[2u * FZN_BLOB_HASH_LEN];
	fzn_blob_tree_t tree;

	memset(key, 0x55, sizeof(key));
	make_leaves(leaves, 2u);

	/* A vtable that refuses must not be mistaken for one that worked. The
	 * outputs are never written, so the caller cannot proceed with half a
	 * key -- which is the failure this shape exists to prevent. */
	CHECK(fzn_blob_derive_leaf(&REFUSER, key, 0u, aead_key, commitment)
	              == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the derivation");
	CHECK(fzn_blob_leaf_hash(&REFUSER, leaves, FZN_BLOB_HASH_LEN, out) == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the leaf hash");
	CHECK(fzn_blob_node_hash(&REFUSER, leaves, leaves + FZN_BLOB_HASH_LEN, out)
	              == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the node hash");

	fzn_blob_tree_init(&tree);
	CHECK(fzn_blob_tree_push(&REFUSER, &tree, leaves) == FZN_BLOB_OK,
	      "the first push does not hash, so it should not have refused");
	CHECK(fzn_blob_tree_push(&REFUSER, &tree, leaves + FZN_BLOB_HASH_LEN)
	              == FZN_BLOB_ERR_HASH,
	      "the fold did not carry the hash's refusal out");
}

/* THE STREAMING TREE'S TWO CAPACITY REFUSALS, WHICH NO TEST NAMED.
 *
 * `FZN_BLOB_ERR_FULL` is produced at two places in `fzn_blob_tree_push` and
 * was named by nothing in this tree -- the only one of 117 error constants in
 * that state. project.md sec 61 has the sweep.
 *
 * REACHED BY CONSTRUCTING THE STATE RATHER THAN BY ARRIVING AT IT, and the
 * header's sentence is what licenses that: the leaf bound "needs
 * FZN_BLOB_MAX_LEAVES leaves and therefore cannot happen to a caller who is
 * not trying". That is true and it is not a claim that the guard cannot be
 * tested -- 2^40 pushes is not a test, a tree is caller-owned memory whose
 * fields this header publishes, and a test is exactly the caller who is
 * trying.
 *
 * EACH BOUND WITH THE OTHER SLACK, or one of the two guards could be deleted
 * and this would still pass on the survivor. And each with its own just-under
 * case, so a `>=` quietly becoming a `>` is caught as well as a guard going
 * missing. */
static void test_the_tree_refuses_when_it_is_full(void)
{
	uint8_t leaf[FZN_BLOB_HASH_LEN];
	fzn_blob_tree_t tree;
	unsigned i;

	memset(leaf, 0x5c, sizeof(leaf));

	/* THE LEAF BOUND, with the stack empty so nothing else can refuse. */
	fzn_blob_tree_init(&tree);
	tree.leaves = FZN_BLOB_MAX_LEAVES - 1u;
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_OK,
	      "a tree one leaf below the bound refused, so the bound is off by one");
	CHECK(tree.leaves == FZN_BLOB_MAX_LEAVES,
	      "the accepted push did not count, so the refusal below is not about a "
	      "full tree");
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_ERR_FULL,
	      "a tree holding FZN_BLOB_MAX_LEAVES accepted another leaf");

	/* THE DEPTH BOUND, with the leaf count nowhere near its own. The levels
	 * are strictly decreasing, which is the invariant the header states for
	 * this stack, so no fold runs and the depth is what refuses rather than
	 * the binary counter unwinding it. */
	fzn_blob_tree_init(&tree);
	for (i = 0; i < FZN_BLOB_MAX_DEPTH; i++)
		tree.level[i] = (uint8_t)(FZN_BLOB_MAX_DEPTH - i);
	tree.depth = FZN_BLOB_MAX_DEPTH - 1u;
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_OK,
	      "a stack one level below the bound refused, so the bound is off by one");
	CHECK(tree.depth == FZN_BLOB_MAX_DEPTH,
	      "the accepted push folded instead of growing the stack, so the refusal "
	      "below is not about a full one");
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_ERR_FULL,
	      "a stack at FZN_BLOB_MAX_DEPTH accepted another leaf, so the write "
	      "would land past the end of the array");

	/* And it renders, which is the half `fzn_blob_err_str` owes a log. */
	CHECK(strcmp(fzn_blob_err_str(FZN_BLOB_ERR_FULL), "unknown") != 0,
	      "the only error code no test named also has no string");
}

/*
 * THE DEEPEST TREE THIS LIBRARY WILL ACCEPT, walked to the bottom.
 *
 * Added 2026-09-04 from a coverage measurement. `blob.c` had 27 lines whose
 * branches never went both ways, and three of them were the depth bounds --
 * the guards that stop a crafted proof making a verifier iterate without end,
 * on the KEYLESS verifier, which `blob.h` says is the one strangers use.
 *
 * WHY THEY ARE UNREACHABLE, WHICH IS THE POINT RATHER THAN AN EXCUSE.
 * `FZN_BLOB_MAX_LEAVES` is DEFINED as `1 << FZN_BLOB_MAX_DEPTH`, so a tree at
 * the maximum leaf count has exactly `FZN_BLOB_MAX_DEPTH` levels and the
 * descent writes `path[0 .. 39]` -- the last slot, and not one past it. The
 * guard cannot fire, by construction and not by luck, because
 * `fzn_blob_proof_verify` refuses `leaf_count > FZN_BLOB_MAX_LEAVES` before
 * the loop begins.
 *
 * SO WHAT THIS TESTS IS THE TIGHTNESS, not the guard. The two constants agree
 * exactly, `path[]` is exactly full at the maximum, and nothing tries the
 * boundary anywhere else: `blob_fuzz` generates at most 40 LEAVES, which is a
 * tree six levels deep, so the descent it exercises is nowhere near forty.
 * Under `make test SANITIZE=1` this is a real bound check on a
 * stranger-facing function, and it is the only case that puts one there.
 *
 * The proof cannot be a genuine one -- building it needs 2^40 leaf hashes --
 * so the assertion is about WHICH refusal comes back. Reaching the climb and
 * failing at the root is the answer that says the descent ran; a SHAPE or a
 * MALFORMED would mean it was refused before ever walking.
 */
/* An AEAD that refuses and writes nothing -- a token that is absent, a key
 * handle that has expired. Impossible to express before 2026-09-04, when
 * `fzn_aead_ops.seal` returned void. project.md sec 85. */
static int refusing_seal(void *ctx, const uint8_t key[FZN_AEAD_KEY_LEN],
                         const uint8_t nonce[FZN_AEAD_NONCE_LEN], const uint8_t *aad,
                         size_t aad_len, uint8_t *text, size_t text_len,
                         uint8_t tag[FZN_AEAD_TAG_LEN])
{
	(void)ctx;
	(void)key;
	(void)nonce;
	(void)aad;
	(void)aad_len;
	(void)text;
	(void)text_len;
	(void)tag;
	return 0;
}

/*
 * A REFUSED SEAL MUST NOT LEAVE THE LEAF IN THE CALLER'S BUFFER.
 *
 * `fzn_blob_leaf_seal` copies the plaintext into `out` and encrypts it in
 * place, so until the seam could report a refusal a backend that failed left
 * the leaf's contents sitting there with `*out_len` set and FZN_BLOB_OK
 * returned. **A sealed leaf is what a seeder hands to strangers by design**,
 * which makes this the worse of the library's two seal call sites -- a frame
 * at least goes to one peer who refuses it on the tag.
 *
 * The wipe is this function's to do because the copy was: `out` held nothing
 * of the caller's before the call. `wire/seal.c`'s `fzn_seal_close`
 * deliberately does not wipe on the same refusal, because there the plaintext
 * is the caller's own and was already in the caller's buffer.
 */
static void test_a_refused_seal_leaves_no_leaf_behind(void)
{
	fzn_aead_ops_t refusing = { refusing_seal, stub_open, NULL };
	uint8_t content_key[FZN_BLOB_KEY_LEN];
	uint8_t plain[FZN_BLOB_LEAF_SIZE];
	uint8_t out[FZN_BLOB_SEALED_MAX];
	size_t out_len = 0xa5a5u;
	size_t i;
	int found;

	memset(content_key, 0x4d, sizeof(content_key));
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(0xC0u + (i % 7u));
	memset(out, 0xee, sizeof(out));

	CHECK(fzn_blob_leaf_seal(&HASH, &refusing, content_key, 0, plain, sizeof(plain), out,
	                         sizeof(out), &out_len) == FZN_BLOB_ERR_HASH,
	      "a refusing aead was not reported by fzn_blob_leaf_seal");

	found = 0;
	for (i = 0; i + sizeof(plain) <= sizeof(out); i++) {
		if (memcmp(out + i, plain, sizeof(plain)) == 0)
			found = 1;
	}
	CHECK(!found,
	      "a refused seal left the leaf's plaintext in the caller's buffer -- and a "
	      "sealed leaf is what a seeder hands to strangers");

	/* THE CONTROL. Both checks above are refusals, and a fixture that had
	 * stopped sealing would satisfy them: an untouched buffer contains no
	 * plaintext either. With a working AEAD the same call must succeed AND
	 * the plaintext must be gone from `out`, because it was encrypted. */
	memset(out, 0xee, sizeof(out));
	out_len = 0;
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, content_key, 0, plain, sizeof(plain), out,
	                         sizeof(out), &out_len) == FZN_BLOB_OK,
	      "the same call with a working aead did not seal, so the refusals above "
	      "pass for the wrong reason");
	CHECK(out_len == sizeof(plain) + FZN_BLOB_LEAF_OVERHEAD,
	      "a sealed leaf is the wrong length");
}

static void test_the_deepest_legal_proof_is_walked(void)
{
	uint8_t leaf[FZN_BLOB_HASH_LEN], root[FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];

	memset(leaf, 0xa1, sizeof(leaf));
	memset(root, 0xb2, sizeof(root));
	memset(siblings, 0xc3, sizeof(siblings));

	/* THE MAXIMUM LEAF COUNT NEEDS EXACTLY MAX_DEPTH SIBLINGS. That is the
	 * two constants agreeing, stated as a behaviour: `sibling_count !=
	 * depth` is a refusal, so this passing means the descent counted
	 * exactly FZN_BLOB_MAX_DEPTH levels. */
	CHECK(fzn_blob_proof_verify(&HASH, leaf, 0, FZN_BLOB_MAX_LEAVES, siblings,
	                            FZN_BLOB_MAX_DEPTH, root) == FZN_BLOB_ERR_PROOF,
	      "the deepest legal tree was refused before its climb");

	/* One fewer and one more must both be refused, which pins the depth to
	 * exactly forty rather than merely at-most-forty. */
	CHECK(fzn_blob_proof_verify(&HASH, leaf, 0, FZN_BLOB_MAX_LEAVES, siblings,
	                            FZN_BLOB_MAX_DEPTH - 1u, root) == FZN_BLOB_ERR_PROOF,
	      "a proof one sibling short of the deepest tree was not refused");
	CHECK(fzn_blob_proof_verify(&HASH, leaf, 0, FZN_BLOB_MAX_LEAVES / 2u, siblings,
	                            FZN_BLOB_MAX_DEPTH, root) == FZN_BLOB_ERR_PROOF,
	      "a proof one level too long for its tree was not refused");

	/* And one leaf past the maximum is refused before anything is walked
	 * at all, which is what makes the depth guard unreachable. */
	CHECK(fzn_blob_proof_verify(&HASH, leaf, 0, FZN_BLOB_MAX_LEAVES + 1u, siblings,
	                            FZN_BLOB_MAX_DEPTH, root) == FZN_BLOB_ERR_MALFORMED,
	      "a tree larger than the maximum was not refused outright");

	/* THE CONTROL: a small tree with a correct sibling count still reaches
	 * its climb, so the refusals above are about the sizes rather than
	 * about this fixture never working. */
	CHECK(fzn_blob_proof_verify(&HASH, leaf, 0, 2u, siblings, 1u, root)
	              == FZN_BLOB_ERR_PROOF,
	      "an ordinary two-leaf proof did not reach its climb");
}

static void test_every_guard_refuses_its_own_argument(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t buf[FZN_BLOB_SEALED_MAX];
	uint8_t hash_out[FZN_BLOB_HASH_LEN];
	uint8_t aead_key[FZN_AEAD_KEY_LEN];
	uint8_t commitment[FZN_COMMITMENT_LEN];
	fzn_blob_tree_t tree;
	size_t len = 0;
	unsigned count = 0;

	memset(key, 0x66, sizeof(key));
	memset(buf, 0x77, sizeof(buf));
	fzn_blob_tree_init(&tree);

	CHECK(fzn_blob_derive_leaf(NULL, key, 0, aead_key, commitment) == FZN_BLOB_ERR_MALFORMED,
	      "null hash ops");
	CHECK(fzn_blob_derive_leaf(&HASH, NULL, 0, aead_key, commitment)
	              == FZN_BLOB_ERR_MALFORMED, "null content key");
	CHECK(fzn_blob_derive_leaf(&HASH, key, 0, NULL, commitment) == FZN_BLOB_ERR_MALFORMED,
	      "null key out");
	CHECK(fzn_blob_derive_leaf(&HASH, key, 0, aead_key, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "null commitment out");

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0, buf, 8u, buf, 8u, &len)
	              == FZN_BLOB_ERR_MALFORMED, "a buffer too small for the overhead");
	CHECK(fzn_blob_leaf_seal(&HASH, NULL, key, 0, buf, 8u, buf, sizeof(buf), &len)
	              == FZN_BLOB_ERR_MALFORMED, "null aead ops");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0, NULL, 64u, buf, sizeof(buf), &len)
	              == FZN_BLOB_ERR_MALFORMED, "null sealed");

	CHECK(fzn_blob_tree_push(&HASH, NULL, hash_out) == FZN_BLOB_ERR_MALFORMED, "null tree");
	CHECK(fzn_blob_tree_push(&HASH, &tree, NULL) == FZN_BLOB_ERR_MALFORMED, "null leaf");
	CHECK(fzn_blob_tree_root(&HASH, &tree, NULL) == FZN_BLOB_ERR_MALFORMED, "null root out");

	CHECK(fzn_blob_proof_build(&HASH, buf, 0, 0, buf, sizeof(buf), &count)
	              == FZN_BLOB_ERR_MALFORMED, "a proof in a tree with no leaves");
	CHECK(fzn_blob_proof_build(&HASH, buf, 4u, 4u, buf, sizeof(buf), &count)
	              == FZN_BLOB_ERR_MALFORMED, "a proof for a leaf past the end");
	CHECK(fzn_blob_proof_verify(&HASH, hash_out, 4u, 4u, buf, 2u, hash_out)
	              == FZN_BLOB_ERR_MALFORMED, "verifying a leaf past the end");

	/* Every error code renders, including one that is not an enumerator:
	 * a log line reading "(null)" is worse than one reading "unknown". */
	CHECK(strcmp(fzn_blob_err_str(FZN_BLOB_OK), "ok") == 0, "ok does not render");
	CHECK(strcmp(fzn_blob_err_str((fzn_blob_err_t)99), "unknown") == 0,
	      "a value that is not an enumerator does not render as unknown");
}

/* The suite must be able to fail, or a green run says only that it ran. */
static void test_the_suite_can_tell_pass_from_fail(void)
{
	int before = failures;

	check_at(0, __LINE__, "deliberate");
	CHECK(failures == before + 1, "a failing check did not count");
	failures = before;
	checks -= 1;
}

/*
 * EVERY OPERAND OF EVERY GUARD, not the first one of each.
 *
 * blob/ carries the most of these in the library -- 25 lines whose later
 * operands the suite never reached -- because almost every entry point here
 * takes two seams and four buffers. sec 88 measured what an unreached
 * operand is worth: the operand after the first is what stands between a
 * partially initialised caller and a null dereference.
 *
 * Three of the cases below are not null tests at all. A refusing hash has to
 * SURFACE from leaf_seal, leaf_open, tree_root and proof_build rather than
 * being swallowed; an out buffer too small for the plaintext is this side's
 * arithmetic being wrong rather than a stranger's bytes, so it is MALFORMED
 * and not SHAPE; and proof_build rechecks its capacity at every level of the
 * descent, so a buffer that runs out part way through is refused rather than
 * written past.
 */
static void test_the_operands_the_first_one_hides(void)
{
	fzn_hash_ops_t no_hash = { NULL, NULL };
	fzn_aead_ops_t no_seal = { NULL, stub_open, NULL };
	fzn_aead_ops_t no_open = { stub_seal, NULL, NULL };
	uint8_t ck[FZN_BLOB_KEY_LEN], key[FZN_AEAD_KEY_LEN], commit[FZN_COMMITMENT_LEN];
	uint8_t plain[FZN_BLOB_LEAF_SIZE], sealed[FZN_BLOB_SEALED_MAX];
	uint8_t h[FZN_BLOB_HASH_LEN], l[FZN_BLOB_HASH_LEN], r[FZN_BLOB_HASH_LEN];
	uint8_t leaves[4u * FZN_BLOB_HASH_LEN], sibs[4u * FZN_BLOB_HASH_LEN];
	size_t out_len = 0;
	unsigned n_sibs = 0;
	fzn_blob_tree_t tree;

	memset(ck, 0x81, sizeof(ck));
	memset(plain, 0x82, sizeof(plain));
	memset(sealed, 0x83, sizeof(sealed));
	memset(leaves, 0x84, sizeof(leaves));
	memset(sibs, 0x85, sizeof(sibs));
	memset(l, 0x86, sizeof(l));
	memset(r, 0x87, sizeof(r));

	/* ---- derive_leaf: five operands, and the hash seam is two of them. */
	CHECK(fzn_blob_derive_leaf(NULL, ck, 0u, key, commit) == FZN_BLOB_ERR_MALFORMED,
	      "derive_leaf accepted a null hash");
	CHECK(fzn_blob_derive_leaf(&no_hash, ck, 0u, key, commit) == FZN_BLOB_ERR_MALFORMED,
	      "derive_leaf accepted a hash struct whose member is null");
	CHECK(fzn_blob_derive_leaf(&HASH, NULL, 0u, key, commit) == FZN_BLOB_ERR_MALFORMED,
	      "derive_leaf accepted a null content key");
	CHECK(fzn_blob_derive_leaf(&HASH, ck, 0u, NULL, commit) == FZN_BLOB_ERR_MALFORMED,
	      "derive_leaf accepted a null key out");
	CHECK(fzn_blob_derive_leaf(&HASH, ck, 0u, key, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "derive_leaf accepted a null commitment out");

	/* ---- leaf_seal: seven operands, the aead seam among them. */
	CHECK(fzn_blob_leaf_seal(NULL, &AEAD, ck, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null hash");
	CHECK(fzn_blob_leaf_seal(&HASH, NULL, ck, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null aead");
	CHECK(fzn_blob_leaf_seal(&HASH, &no_seal, ck, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted an aead struct whose seal member is null");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, NULL, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null content key");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, ck, 0u, NULL, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null plaintext");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, ck, 0u, plain, sizeof(plain), NULL,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null out");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, ck, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), NULL) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_seal accepted a null out length");

	/* THE DERIVE REFUSAL PROPAGATES. A hash that refuses must surface as
	 * the seal's error rather than being swallowed into a sealed leaf
	 * whose key nobody derived. */
	CHECK(fzn_blob_leaf_seal(&REFUSER, &AEAD, ck, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &out_len) == FZN_BLOB_ERR_HASH,
	      "leaf_seal swallowed a refusing hash");

	/* ---- leaf_open: the same shape, plus its own capacity operand. */
	CHECK(fzn_blob_leaf_open(NULL, &AEAD, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null hash");
	CHECK(fzn_blob_leaf_open(&HASH, NULL, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null aead");
	CHECK(fzn_blob_leaf_open(&HASH, &no_open, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted an aead struct whose open member is null");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, NULL, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null content key");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, ck, 0u, NULL, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null sealed leaf");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         NULL, sizeof(plain), &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null out");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), NULL) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted a null out length");

	/* A BUFFER TOO SMALL IS MALFORMED, NOT SHAPE: the length came from the
	 * caller's own sealed leaf, so it is this side's arithmetic that is
	 * wrong, not a stranger's bytes. */
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, 4u, &out_len) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_open accepted an out buffer smaller than the plaintext");
	CHECK(fzn_blob_leaf_open(&REFUSER, &AEAD, ck, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD + 8u,
	                         plain, sizeof(plain), &out_len) == FZN_BLOB_ERR_HASH,
	      "leaf_open swallowed a refusing hash");

	/* ---- leaf_hash and node_hash. */
	CHECK(fzn_blob_leaf_hash(NULL, sealed, 8u, h) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_hash accepted a null hash");
	CHECK(fzn_blob_leaf_hash(&no_hash, sealed, 8u, h) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_hash accepted a hash struct whose member is null");
	CHECK(fzn_blob_leaf_hash(&HASH, NULL, 8u, h) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_hash accepted a null sealed leaf");
	CHECK(fzn_blob_leaf_hash(&HASH, sealed, 8u, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "leaf_hash accepted a null out");

	CHECK(fzn_blob_node_hash(NULL, l, r, h) == FZN_BLOB_ERR_MALFORMED,
	      "node_hash accepted a null hash");
	CHECK(fzn_blob_node_hash(&no_hash, l, r, h) == FZN_BLOB_ERR_MALFORMED,
	      "node_hash accepted a hash struct whose member is null");
	CHECK(fzn_blob_node_hash(&HASH, NULL, r, h) == FZN_BLOB_ERR_MALFORMED,
	      "node_hash accepted a null left child");
	CHECK(fzn_blob_node_hash(&HASH, l, NULL, h) == FZN_BLOB_ERR_MALFORMED,
	      "node_hash accepted a null right child");
	CHECK(fzn_blob_node_hash(&HASH, l, r, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "node_hash accepted a null out");

	/* ---- tree_init tolerates a null rather than crashing on one. */
	fzn_blob_tree_init(NULL);
	CHECK(1, "tree_init survived a null tree");

	/* ---- tree_root: four operands, then the refusal from below. */
	fzn_blob_tree_init(&tree);
	CHECK(fzn_blob_tree_push(&HASH, &tree, l) == FZN_BLOB_OK, "push refused");
	CHECK(fzn_blob_tree_root(NULL, &tree, h) == FZN_BLOB_ERR_MALFORMED,
	      "tree_root accepted a null hash");
	CHECK(fzn_blob_tree_root(&no_hash, &tree, h) == FZN_BLOB_ERR_MALFORMED,
	      "tree_root accepted a hash struct whose member is null");
	CHECK(fzn_blob_tree_root(&HASH, NULL, h) == FZN_BLOB_ERR_MALFORMED,
	      "tree_root accepted a null tree");
	CHECK(fzn_blob_tree_root(&HASH, &tree, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "tree_root accepted a null root out");
	CHECK(fzn_blob_tree_root(&REFUSER, &tree, h) == FZN_BLOB_ERR_HASH,
	      "tree_root swallowed a refusing hash");

	/* ---- proof_build: four operands, plus a capacity that runs out
	 * PART WAY THROUGH the descent rather than at the door. */
	CHECK(fzn_blob_proof_build(NULL, leaves, 4u, 0u, sibs, sizeof(sibs), &n_sibs)
	      == FZN_BLOB_ERR_MALFORMED, "proof_build accepted a null hash");
	CHECK(fzn_blob_proof_build(&HASH, NULL, 4u, 0u, sibs, sizeof(sibs), &n_sibs)
	      == FZN_BLOB_ERR_MALFORMED, "proof_build accepted null leaf hashes");
	CHECK(fzn_blob_proof_build(&HASH, leaves, 4u, 0u, NULL, sizeof(sibs), &n_sibs)
	      == FZN_BLOB_ERR_MALFORMED, "proof_build accepted a null out");
	CHECK(fzn_blob_proof_build(&HASH, leaves, 4u, 0u, sibs, sizeof(sibs), NULL)
	      == FZN_BLOB_ERR_MALFORMED, "proof_build accepted a null out count");
	CHECK(fzn_blob_proof_build(&HASH, leaves, 4u, 0u, sibs, FZN_BLOB_HASH_LEN, &n_sibs)
	      == FZN_BLOB_ERR_MALFORMED,
	      "proof_build accepted an out buffer with room for fewer siblings than the "
	      "descent needs -- the capacity is rechecked every level, not once");
	CHECK(fzn_blob_proof_build(&REFUSER, leaves, 4u, 0u, sibs, sizeof(sibs), &n_sibs)
	      == FZN_BLOB_ERR_HASH, "proof_build swallowed a refusing hash");

	/* ---- proof_verify: three operands, and the one that is not a null
	 * test -- siblings may be null only when the count says there are
	 * none, which is the single-leaf tree. */
	CHECK(fzn_blob_proof_verify(NULL, l, 0u, 4u, sibs, 2u, r) == FZN_BLOB_ERR_MALFORMED,
	      "proof_verify accepted a null hash");
	CHECK(fzn_blob_proof_verify(&HASH, NULL, 0u, 4u, sibs, 2u, r) == FZN_BLOB_ERR_MALFORMED,
	      "proof_verify accepted a null leaf hash");
	CHECK(fzn_blob_proof_verify(&HASH, l, 0u, 4u, sibs, 2u, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "proof_verify accepted a null root");
	CHECK(fzn_blob_proof_verify(&HASH, l, 0u, 4u, NULL, 2u, r) == FZN_BLOB_ERR_MALFORMED,
	      "proof_verify accepted null siblings with a nonzero count");
}

int main(void)
{
	test_the_streaming_tree_agrees_with_the_definition();
	test_a_tree_with_no_leaves_has_no_root();
	test_the_leaf_and_node_prefixes_stop_a_forgery();
	test_distinct_leaf_counts_give_distinct_roots();
	test_a_proof_reaches_the_root();
	test_a_proof_that_is_wrong_is_refused();
	test_sealing_is_deterministic_and_reversible();
	test_a_leaf_is_bound_to_its_index();
	test_the_commitment_is_checked_before_the_aead();
	test_a_refused_open_leaves_nothing_usable();
	test_an_empty_leaf_is_refused();
	test_a_strangers_lengths_are_refused_as_shape();
	test_a_refusing_hash_carries_its_refusal_out();
	test_the_tree_refuses_when_it_is_full();
	test_a_refused_seal_leaves_no_leaf_behind();
	test_the_deepest_legal_proof_is_walked();
	test_every_guard_refuses_its_own_argument();
	test_the_suite_can_tell_pass_from_fail();

	test_the_operands_the_first_one_hides();
	test_every_canonical_span_reaches_the_root();
	test_a_straddling_span_is_refused();
	test_a_span_proof_of_the_wrong_length_is_refused();
	test_the_largest_span_at_every_position_is_canonical();

	printf("blob_test: %d checks, %d failure(s)\n", checks, failures);
	return failures == 0 ? 0 : 1;
}
