/* Tests for blob/blob.c: leaf key derivation, sealing, the streaming tree
 * and inclusion proofs.
 *
 * THE TREE'S SHAPE IS CHECKED AGAINST A SECOND IMPLEMENTATION, not against
 * a frozen vector. A vector generated by running this library would be one
 * witness wearing two hats -- evidence.md's rule about corroboration -- and
 * there is no published vector to cite, because the tree is over this
 * library's own sealed leaves. So the reference below is written from RFC
 * 6962's recursive definition directly: split at the largest power of two
 * strictly less than n, hash the halves. The implementation is a streaming
 * binary counter and looks nothing like it, which is what makes agreement
 * mean something.
 *
 * THE STUB HASH IS NOT A HASH and does not need to be. What every case here
 * asks is whether the right bytes reached the right call in the right order,
 * and for that a mixing function that depends on every input byte and on the
 * requested length is enough. Two cases need more and say so where they are.
 */

#include "../blob.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

static int failures;
static int checks;

#if defined(__GNUC__)
#define FZN_CHECK_PRINTF __attribute__((format(printf, 3, 4)))
#else
#define FZN_CHECK_PRINTF
#endif

static void check_at(int ok, int line, const char *fmt, ...) FZN_CHECK_PRINTF;

static void check_at(int ok, int line, const char *fmt, ...)
{
	va_list ap;

	checks++;
	if (ok)
		return;

	failures++;
	fprintf(stderr, "  FAIL blob_test.c:%d: ", line);
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fprintf(stderr, "\n");
}

#define CHECK(cond, ...) check_at((cond) ? 1 : 0, __LINE__, __VA_ARGS__)

/* ---- the stubs -------------------------------------------------------- */

/* A mixing function over every input byte, the requested length and the
 * output position. Not a hash: it is trivially invertible and has no
 * collision resistance worth the name. What it must do is DEPEND ON
 * EVERYTHING -- a stub that ignored a byte would make "this field is in the
 * transcript" a question with no observable answer, which is the failure
 * these suites keep finding in each other. */
static int stub_hash(void *ctx, uint8_t *out, size_t out_len, const uint8_t *in, size_t in_len)
{
	uint64_t h = 0xcbf29ce484222325ull;
	size_t i;

	(void)ctx;
	if (!out || !in)
		return 0;

	h ^= (uint64_t)out_len;
	h *= 0x100000001b3ull;
	for (i = 0; i < in_len; i++) {
		h ^= in[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < out_len; i++) {
		h ^= (uint64_t)i + 0x9e3779b97f4a7c15ull;
		h *= 0x100000001b3ull;
		out[i] = (uint8_t)(h >> 32);
	}
	return 1;
}

/* A hash that refuses, for the paths that must carry a refusal out rather
 * than proceed with a buffer nobody filled. */
static int refusing_hash(void *ctx, uint8_t *out, size_t out_len, const uint8_t *in,
                         size_t in_len)
{
	(void)ctx;
	(void)out;
	(void)out_len;
	(void)in;
	(void)in_len;
	return 0;
}

/* A toy AEAD: a keystream from the key and nonce, and a tag over key, nonce,
 * aad and ciphertext. Real enough that a changed byte anywhere changes the
 * tag, which is all any case here asks of it. */
static void stream(const uint8_t *key, const uint8_t *nonce, uint8_t *text, size_t len)
{
	uint64_t h = 0x243f6a8885a308d3ull;
	size_t i;

	for (i = 0; i < FZN_AEAD_KEY_LEN; i++) {
		h ^= key[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_NONCE_LEN; i++) {
		h ^= nonce[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < len; i++) {
		h ^= (uint64_t)i;
		h *= 0x100000001b3ull;
		text[i] ^= (uint8_t)(h >> 24);
	}
}

static void tag_over(const uint8_t *key, const uint8_t *nonce, const uint8_t *aad,
                     size_t aad_len, const uint8_t *text, size_t text_len,
                     uint8_t tag[FZN_AEAD_TAG_LEN])
{
	uint64_t h = 0xff51afd7ed558ccdull;
	size_t i;

	for (i = 0; i < FZN_AEAD_KEY_LEN; i++) {
		h ^= key[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_NONCE_LEN; i++) {
		h ^= nonce[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < aad_len; i++) {
		h ^= aad[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < text_len; i++) {
		h ^= text[i];
		h *= 0x100000001b3ull;
	}
	for (i = 0; i < FZN_AEAD_TAG_LEN; i++) {
		h ^= (uint64_t)i + 0x2545f4914f6cdd1dull;
		h *= 0x100000001b3ull;
		tag[i] = (uint8_t)(h >> 40);
	}
}

static void stub_seal(void *ctx, const uint8_t key[FZN_AEAD_KEY_LEN],
                      const uint8_t nonce[FZN_AEAD_NONCE_LEN], const uint8_t *aad,
                      size_t aad_len, uint8_t *text, size_t text_len,
                      uint8_t tag[FZN_AEAD_TAG_LEN])
{
	(void)ctx;
	stream(key, nonce, text, text_len);
	tag_over(key, nonce, aad, aad_len, text, text_len, tag);
}

static int stub_open(void *ctx, const uint8_t key[FZN_AEAD_KEY_LEN],
                     const uint8_t nonce[FZN_AEAD_NONCE_LEN], const uint8_t *aad,
                     size_t aad_len, uint8_t *text, size_t text_len,
                     const uint8_t tag[FZN_AEAD_TAG_LEN])
{
	uint8_t want[FZN_AEAD_TAG_LEN];

	(void)ctx;
	tag_over(key, nonce, aad, aad_len, text, text_len, want);
	if (memcmp(want, tag, FZN_AEAD_TAG_LEN) != 0)
		return 0;
	stream(key, nonce, text, text_len);
	return 1;
}

static const fzn_hash_ops_t HASH = { stub_hash, NULL };
static const fzn_hash_ops_t REFUSER = { refusing_hash, NULL };
static const fzn_aead_ops_t AEAD = { stub_seal, stub_open, NULL };

/* ---- the reference tree ----------------------------------------------- */

/* RFC 6962's Merkle Tree Hash, written recursively and directly from the
 * definition, over an array of leaf hashes.
 *
 * IT IS NOT THE IMPLEMENTATION WITH THE NAMES CHANGED. blob.c pushes leaves
 * into a binary-counter stack and folds the remainder right-to-left at the
 * end; this splits at the largest power of two below n and recurses. The two
 * arrive at the same tree for every n or one of them is wrong, and that is
 * the assertion.
 *
 * Recursion is fine here and not in the library: this is a test over at most
 * a few hundred leaves, and the library's rule about bounded stacks exists
 * for bytes that arrive from strangers. */
static void reference_apex(const uint8_t *leaves, uint64_t n, uint8_t out[FZN_BLOB_HASH_LEN])
{
	uint8_t left[FZN_BLOB_HASH_LEN];
	uint8_t right[FZN_BLOB_HASH_LEN];
	uint64_t k = 1u;

	if (n == 1u) {
		memcpy(out, leaves, FZN_BLOB_HASH_LEN);
		return;
	}
	while ((k << 1) < n)
		k <<= 1;

	reference_apex(leaves, k, left);
	reference_apex(leaves + ((size_t)k * FZN_BLOB_HASH_LEN), n - k, right);
	(void)fzn_blob_node_hash(&HASH, left, right, out);
}

/* The finaliser, written out here rather than called, because the library's
 * is `static` and because a reference that called it would agree with it by
 * construction. The label is spelled again for the same reason -- if the two
 * copies ever disagree the tests fail, which is the point of having two. */
static void reference_root(const uint8_t *leaves, uint64_t n, uint8_t out[FZN_BLOB_HASH_LEN])
{
	uint8_t apex[FZN_BLOB_HASH_LEN];
	uint8_t input[16u + 8u + FZN_BLOB_HASH_LEN];
	static const char label[16] = "fuzznet-root-v1\0";
	size_t i;

	reference_apex(leaves, n, apex);
	memcpy(input, label, sizeof(label));
	for (i = 0; i < 8u; i++)
		input[16u + i] = (uint8_t)(n >> ((7u - i) * 8u));
	memcpy(input + 24u, apex, FZN_BLOB_HASH_LEN);
	(void)stub_hash(NULL, out, FZN_BLOB_HASH_LEN, input, sizeof(input));
}

/* Fills `out` with `n` distinct leaf hashes, derived so that no two agree
 * and none is a constant a bug could match by accident. */
static void make_leaves(uint8_t *out, uint64_t n)
{
	uint64_t i;
	size_t j;

	for (i = 0; i < n; i++)
		for (j = 0; j < FZN_BLOB_HASH_LEN; j++)
			out[((size_t)i * FZN_BLOB_HASH_LEN) + j] =
			        (uint8_t)((i * 131u) + (j * 7u) + 1u);
}

static fzn_blob_err_t streamed_root(const uint8_t *leaves, uint64_t n,
                                     uint8_t out[FZN_BLOB_HASH_LEN])
{
	fzn_blob_tree_t tree;
	uint64_t i;
	fzn_blob_err_t err;

	fzn_blob_tree_init(&tree);
	for (i = 0; i < n; i++) {
		err = fzn_blob_tree_push(&HASH, &tree,
		                         leaves + ((size_t)i * FZN_BLOB_HASH_LEN));
		if (err != FZN_BLOB_OK)
			return err;
	}
	return fzn_blob_tree_root(&HASH, &tree, out);
}

/* ---- the cases -------------------------------------------------------- */

#define MAX_TEST_LEAVES 130u

static void test_the_streaming_tree_agrees_with_the_definition(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t want[FZN_BLOB_HASH_LEN];
	uint8_t got[FZN_BLOB_HASH_LEN];
	uint64_t n;

	make_leaves(leaves, MAX_TEST_LEAVES);

	/* EVERY n UP TO 130, not a sample. The shapes that differ are the
	 * ones that are not powers of two, and the ones that catch a
	 * fold-direction error are the ones just past a power of two -- so a
	 * sample chosen by hand is a sample chosen to pass. 130 covers two
	 * powers of two, both their successors, and 129, where the stack has
	 * two entries whose heights differ by seven. */
	for (n = 1u; n <= MAX_TEST_LEAVES; n++) {
		reference_root(leaves, n, want);
		CHECK(streamed_root(leaves, n, got) == FZN_BLOB_OK,
		      "the streaming tree refused %llu leaves", (unsigned long long)n);
		CHECK(memcmp(want, got, FZN_BLOB_HASH_LEN) == 0,
		      "the streaming tree and the definition disagree at %llu leaves",
		      (unsigned long long)n);
	}
}

static void test_a_tree_with_no_leaves_has_no_root(void)
{
	fzn_blob_tree_t tree;
	uint8_t root[FZN_BLOB_HASH_LEN];

	fzn_blob_tree_init(&tree);
	CHECK(fzn_blob_tree_root(&HASH, &tree, root) == FZN_BLOB_ERR_MALFORMED,
	      "an empty tree produced a root, so every empty file shares an id");
}

static void test_the_leaf_and_node_prefixes_stop_a_forgery(void)
{
	uint8_t leaves[2u * FZN_BLOB_HASH_LEN];
	uint8_t node[FZN_BLOB_HASH_LEN];
	uint8_t as_leaf[FZN_BLOB_HASH_LEN];
	uint8_t forged[2u * FZN_BLOB_HASH_LEN];

	/* THE TEXTBOOK SECOND-PREIMAGE ATTACK, built rather than described.
	 * An interior node hashes 64 bytes of children. Those same 64 bytes
	 * are a perfectly good sealed leaf, so a tree whose leaf is "the
	 * concatenation of a and b" would have the same root as a tree whose
	 * two leaves are a and b -- and the KEYLESS verifier, which is what a
	 * relay uses, cannot tell them apart.
	 *
	 * The prefixes are what separates them, and this case is the only
	 * thing standing between them and being deleted as decoration.
	 * Measured: with FZN_BLOB_NODE_PREFIX set equal to
	 * FZN_BLOB_LEAF_PREFIX, the two hashes below are identical. */
	make_leaves(leaves, 2u);
	CHECK(fzn_blob_node_hash(&HASH, leaves, leaves + FZN_BLOB_HASH_LEN, node) == FZN_BLOB_OK,
	      "the node hash refused");

	memcpy(forged, leaves, sizeof(forged));
	CHECK(fzn_blob_leaf_hash(&HASH, forged, sizeof(forged), as_leaf) == FZN_BLOB_OK,
	      "hashing 64 bytes as a leaf refused");

	CHECK(memcmp(node, as_leaf, FZN_BLOB_HASH_LEN) != 0,
	      "an interior node and a leaf over the same bytes hash alike, so the tree "
	      "is second-preimage weak and a relay would serve the forgery");
}

static void test_distinct_leaf_counts_give_distinct_roots(void)
{
	static uint8_t leaves[16u * FZN_BLOB_HASH_LEN];
	uint8_t roots[9][FZN_BLOB_HASH_LEN];
	uint8_t dup[4u * FZN_BLOB_HASH_LEN];
	uint8_t dup_root[FZN_BLOB_HASH_LEN];
	uint64_t a;
	uint64_t b;

	/* ONE SHARED LEAF ARRAY, walked from 1 to 8, so every pair of trees
	 * AGREES ON A PREFIX and differs only in how far it runs -- the
	 * truncation shape exactly, and a construction that does not happen
	 * by accident. Taken from fuzzypickles'
	 * test_distinct_leaf_counts_give_distinct_roots.
	 *
	 * AND IT DOES NOT PROVE WHAT THEIRS PROVES, WHICH IS THE POINT OF
	 * SAYING SO. Measured, by removing the count from the finaliser AND
	 * from the reference together: this case still passes. It has to.
	 * This tree does not pad, so a tree over three leaves and one over
	 * four have different APEXES whatever the finaliser does, and no
	 * amount of shared prefix changes that. In fuzzypickles the same
	 * assertion is load-bearing because they DO pad, and padding is
	 * exactly what can make two counts fold to one apex.
	 *
	 * The case that discriminates here is the proof verified against a
	 * different leaf count, in test_a_proof_that_is_wrong_is_refused, and
	 * under that mutation it is the ONLY case in this file that fails.
	 * Kept anyway, because "we do not pad" is a property somebody can
	 * change and this is what would notice.
	 *
	 * The general form is worth more than the instance: adopting a
	 * sibling's test brings its rationale with it, and a rationale is
	 * true of the construction it was written for. */
	make_leaves(leaves, 16u);
	for (a = 1u; a <= 8u; a++)
		CHECK(streamed_root(leaves, a, roots[a]) == FZN_BLOB_OK,
		      "the tree over %llu leaves refused", (unsigned long long)a);

	for (a = 1u; a <= 8u; a++)
		for (b = a + 1u; b <= 8u; b++)
			CHECK(memcmp(roots[a], roots[b], FZN_BLOB_HASH_LEN) != 0,
			      "trees over %llu and %llu leaves share a root, so a blob id "
			      "does not commit to its length",
			      (unsigned long long)a, (unsigned long long)b);

	/* CVE-2012-2459, BY NAME. Bitcoin's Merkle tree duplicated a final
	 * odd leaf, so a tree over three leaves and one over four whose
	 * fourth repeats the third had the same root -- two different blocks
	 * with one id. This tree does not pad and so does not have that bug
	 * by construction; the case is here anyway, because "we do not pad"
	 * is a property somebody can change and this is what would notice. */
	memcpy(dup, leaves, 3u * FZN_BLOB_HASH_LEN);
	memcpy(dup + (3u * FZN_BLOB_HASH_LEN), leaves + (2u * FZN_BLOB_HASH_LEN),
	       FZN_BLOB_HASH_LEN);
	CHECK(streamed_root(dup, 4u, dup_root) == FZN_BLOB_OK, "the duplicate tree refused");
	CHECK(memcmp(roots[3], dup_root, FZN_BLOB_HASH_LEN) != 0,
	      "a three-leaf tree and a four-leaf tree repeating its last leaf share a "
	      "root -- CVE-2012-2459");
}

static void test_a_proof_reaches_the_root(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN];
	unsigned count;
	uint64_t n;
	uint64_t i;

	make_leaves(leaves, MAX_TEST_LEAVES);

	/* EVERY LEAF OF EVERY TREE up to 33, because a proof that works for
	 * the first leaf and the last is the one a hand-written case would
	 * check, and the interesting index is the one whose path crosses an
	 * incomplete subtree. */
	for (n = 1u; n <= 33u; n++) {
		reference_root(leaves, n, root);
		for (i = 0; i < n; i++) {
			CHECK(fzn_blob_proof_build(&HASH, leaves, n, i, siblings,
			                           sizeof(siblings), &count) == FZN_BLOB_OK,
			      "building a proof for leaf %llu of %llu refused",
			      (unsigned long long)i, (unsigned long long)n);
			CHECK(fzn_blob_proof_verify(&HASH,
			                            leaves + ((size_t)i * FZN_BLOB_HASH_LEN), i,
			                            n, siblings, count, root) == FZN_BLOB_OK,
			      "leaf %llu of %llu does not verify against its own root",
			      (unsigned long long)i, (unsigned long long)n);
		}
	}
}

static void test_a_proof_that_is_wrong_is_refused(void)
{
	static uint8_t leaves[MAX_TEST_LEAVES * FZN_BLOB_HASH_LEN];
	uint8_t siblings[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
	uint8_t root[FZN_BLOB_HASH_LEN];
	unsigned count;
	const uint64_t n = 11u;
	const uint64_t index = 4u;

	make_leaves(leaves, MAX_TEST_LEAVES);
	reference_root(leaves, n, root);
	CHECK(fzn_blob_proof_build(&HASH, leaves, n, index, siblings, sizeof(siblings),
	                           &count) == FZN_BLOB_OK,
	      "the positive control did not build, so every refusal below proves nothing");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count, root) == FZN_BLOB_OK,
	      "the positive control does not verify, so every refusal below proves nothing");

	/* A DIFFERENT LEAF, same proof. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves, index, n, siblings, count, root)
	              == FZN_BLOB_ERR_PROOF,
	      "another leaf verified at index %llu", (unsigned long long)index);

	/* THE SAME LEAF AT A DIFFERENT INDEX, which is the reordering a
	 * content-addressed store must refuse: index decides the shape of the
	 * climb, so a leaf that moved cannot reach the same root. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index + 1u, n,
	                            siblings, count, root) == FZN_BLOB_ERR_PROOF,
	      "a leaf verified at an index it does not occupy");

	/* A DIFFERENT LEAF COUNT, AND THE HISTORY IS WORTH THE PARAGRAPH.
	 *
	 * This case was written asserting flatly that a proof does not verify
	 * against a tree of another size. It FAILED, correctly: leaf 4 sits
	 * inside the complete left subtree of eight, identical in a tree of
	 * 11 and one of 12, so path, siblings and apex all matched and the
	 * proof was genuinely valid for both. The assertion was relaxed and
	 * the caveat written into blob.h -- whatever carries a blob id must
	 * carry its length under the same signature.
	 *
	 * fuzzypickles read that and answered with their finaliser, which
	 * binds the leaf count into the root. The caveat is gone and this
	 * assertion is true again, unconditionally and without a rule anybody
	 * has to remember. Kept in this shape as the case that discriminates:
	 * it passes only because the count is bound, and it is what fails if
	 * the finaliser ever stops binding it.
	 */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n + 1u,
	                            siblings, count, root) == FZN_BLOB_ERR_PROOF,
	      "a proof verified against a tree of a different size, so the root does not "
	      "commit to the leaf count and a receiver can be walked to a truncation");

	{
		uint8_t edge_sib[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];
		unsigned edge_count;
		const uint64_t edge = 10u;

		CHECK(fzn_blob_proof_build(&HASH, leaves, n, edge, edge_sib, sizeof(edge_sib),
		                           &edge_count) == FZN_BLOB_OK,
		      "building the edge proof refused");
		CHECK(fzn_blob_proof_verify(&HASH, leaves + (edge * FZN_BLOB_HASH_LEN), edge, n,
		                            edge_sib, edge_count, root) == FZN_BLOB_OK,
		      "the edge control does not verify against its own tree");
		CHECK(fzn_blob_proof_verify(&HASH, leaves + (edge * FZN_BLOB_HASH_LEN), edge,
		                            n + 1u, edge_sib, edge_count, root)
		              == FZN_BLOB_ERR_PROOF,
		      "a proof for the last leaf of an 11-leaf tree verified against a "
		      "12-leaf one");
	}

	/* ONE SIBLING CORRUPTED, at every position in turn: a verifier that
	 * only consulted the first or the last would pass most of these. */
	{
		unsigned i;

		for (i = 0; i < count; i++) {
			uint8_t bent[FZN_BLOB_MAX_DEPTH * FZN_BLOB_HASH_LEN];

			memcpy(bent, siblings, sizeof(bent));
			bent[i * FZN_BLOB_HASH_LEN] = (uint8_t)(bent[i * FZN_BLOB_HASH_LEN] ^ 1u);
			CHECK(fzn_blob_proof_verify(&HASH,
			                            leaves + (index * FZN_BLOB_HASH_LEN), index,
			                            n, bent, count, root) == FZN_BLOB_ERR_PROOF,
			      "a proof with sibling %u bent by one bit still verified", i);
		}
	}

	/* TOO FEW AND TOO MANY SIBLINGS. Short of the root and past it are
	 * different mistakes and both are refusals. */
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count - 1u, root) == FZN_BLOB_ERR_PROOF,
	      "a proof one sibling short verified");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, count + 1u, root) == FZN_BLOB_ERR_PROOF,
	      "a proof with a sibling too many verified");
	CHECK(fzn_blob_proof_verify(&HASH, leaves + (index * FZN_BLOB_HASH_LEN), index, n,
	                            siblings, FZN_BLOB_MAX_DEPTH + 1u, root)
	              == FZN_BLOB_ERR_SHAPE,
	      "a proof deeper than the bound was not refused as a shape");
}

static void test_sealing_is_deterministic_and_reversible(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[FZN_BLOB_LEAF_SIZE];
	uint8_t first[FZN_BLOB_SEALED_MAX];
	uint8_t second[FZN_BLOB_SEALED_MAX];
	uint8_t back[FZN_BLOB_LEAF_SIZE];
	size_t first_len = 0;
	size_t second_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 3u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i * 17u);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), first,
	                         sizeof(first), &first_len) == FZN_BLOB_OK,
	      "sealing a full leaf refused");
	CHECK(first_len == sizeof(plain) + FZN_BLOB_LEAF_OVERHEAD,
	      "a sealed leaf is %zu bytes, wanted %zu", first_len,
	      sizeof(plain) + FZN_BLOB_LEAF_OVERHEAD);

	/* DETERMINISTIC, which is the property dedup rests on: two people
	 * holding the same file must produce the same bytes and therefore the
	 * same id, or they seed two swarms. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), second,
	                         sizeof(second), &second_len) == FZN_BLOB_OK,
	      "sealing the same leaf twice refused the second time");
	CHECK(first_len == second_len && memcmp(first, second, first_len) == 0,
	      "sealing the same content under the same key twice gave different bytes");

	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 7u, first, first_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_OK,
	      "a leaf this library sealed does not open");
	CHECK(back_len == sizeof(plain) && memcmp(back, plain, sizeof(plain)) == 0,
	      "the opened leaf is not the plaintext");
}

static void test_a_leaf_is_bound_to_its_index(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[64];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t elsewhere[FZN_BLOB_SEALED_MAX];
	uint8_t back[64];
	size_t sealed_len = 0;
	size_t other_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 11u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i + 1u);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 3u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing at index 3 refused");

	/* THE INDEX IS INSIDE THE DERIVATION, not only in the nonce. So a
	 * leaf lifted from position 3 and replayed at 7 does not derive the
	 * same key at all, and is refused at the COMMITMENT -- before the
	 * AEAD, and without depending on the Merkle root having been checked,
	 * which a peer serving from a partial cache may not have done. */
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 7u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_COMMITMENT,
	      "a leaf lifted from index 3 opened at index 7");

	/* And the same content at two indices seals to different bytes, which
	 * is the same fact from the writing side. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 7u, plain, sizeof(plain), elsewhere,
	                         sizeof(elsewhere), &other_len) == FZN_BLOB_OK,
	      "sealing at index 7 refused");
	CHECK(sealed_len == other_len && memcmp(sealed, elsewhere, sealed_len) != 0,
	      "the same content sealed identically at two indices");
}

static void test_the_commitment_is_checked_before_the_aead(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[100];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t back[100];
	size_t sealed_len = 0;
	size_t back_len = 0;
	size_t i;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 5u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = (uint8_t)(i ^ 0x5au);

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing refused");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_OK,
	      "the positive control does not open, so the refusals below prove nothing");

	/* A BENT COMMITMENT IS ITS OWN ERROR, distinct from the AEAD's. The
	 * two codes are what says the check happened first: if the commitment
	 * were checked after -- or not at all -- this would come back as
	 * AUTH, because the commitment is also the AEAD's aad. */
	sealed[0] = (uint8_t)(sealed[0] ^ 0x80u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_COMMITMENT,
	      "a bent commitment did not come back as a commitment failure, so the "
	      "non-committing AEAD is not being fenced");
	sealed[0] = (uint8_t)(sealed[0] ^ 0x80u);

	/* A BENT CIPHERTEXT IS THE AEAD's, which is the other half of the
	 * same claim: the two errors are reachable independently, so neither
	 * is standing in for the other. */
	sealed[FZN_COMMITMENT_LEN] = (uint8_t)(sealed[FZN_COMMITMENT_LEN] ^ 1u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_AUTH,
	      "a bent ciphertext was not refused by the aead");
}

static void test_a_refused_open_leaves_nothing_usable(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t plain[48];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t back[48];
	size_t sealed_len = 0;
	size_t back_len = 0;
	size_t i;
	int all_zero = 1;

	for (i = 0; i < sizeof(key); i++)
		key[i] = (uint8_t)(i + 9u);
	for (i = 0; i < sizeof(plain); i++)
		plain[i] = 0xa5u;

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 2u, plain, sizeof(plain), sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_OK,
	      "sealing refused");

	memset(back, 0x11, sizeof(back));
	sealed[sealed_len - 1u] = (uint8_t)(sealed[sealed_len - 1u] ^ 1u);
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 2u, sealed, sealed_len, back, sizeof(back),
	                         &back_len) == FZN_BLOB_ERR_AUTH,
	      "a bent tag was accepted");

	/* THE CALLER'S BUFFER HELD CIPHERTEXT WHEN THE AEAD REFUSED, and a
	 * caller who ignores a return value must not find plausible bytes in
	 * it. Wiped rather than left, which is cheap and is the difference
	 * between a bug and a disclosure. */
	for (i = 0; i < sizeof(back); i++)
		if (back[i] != 0u)
			all_zero = 0;
	CHECK(all_zero, "a refused open left bytes in the caller's buffer");
}

static void test_an_empty_leaf_is_refused(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t sealed[FZN_BLOB_SEALED_MAX];
	uint8_t plain[1] = { 0 };
	size_t sealed_len = 0;

	memset(key, 0x22, sizeof(key));

	/* AN EMPTY FINAL LEAF WOULD GIVE ONE FILE TWO IDS -- with the empty
	 * leaf and without it -- and a content-addressed store may have
	 * exactly one. */
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, 0, sealed, sizeof(sealed),
	                         &sealed_len) == FZN_BLOB_ERR_MALFORMED,
	      "an empty leaf was sealed, so a file has two encodings");
	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0u, plain, FZN_BLOB_LEAF_SIZE + 1u, sealed,
	                         sizeof(sealed), &sealed_len) == FZN_BLOB_ERR_MALFORMED,
	      "a leaf larger than the canonical size was sealed");
}

static void test_a_strangers_lengths_are_refused_as_shape(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t sealed[FZN_BLOB_SEALED_MAX + 1u];
	uint8_t back[FZN_BLOB_LEAF_SIZE];
	size_t back_len = 0;

	memset(key, 0x33, sizeof(key));
	memset(sealed, 0x44, sizeof(sealed));

	/* SHAPE, NOT MALFORMED. These are a peer's bytes and arriving wrong
	 * is expected; MALFORMED is reserved for the caller's own bug, and a
	 * caller that logs one and drops the other needs them apart. */
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, FZN_BLOB_LEAF_OVERHEAD, back,
	                         sizeof(back), &back_len) == FZN_BLOB_ERR_SHAPE,
	      "a sealed leaf with no ciphertext at all was not refused as a shape");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0u, sealed, sizeof(sealed), back,
	                         sizeof(back), &back_len) == FZN_BLOB_ERR_SHAPE,
	      "a sealed leaf past the canonical size was not refused as a shape");
	CHECK(fzn_blob_leaf_hash(&HASH, sealed, sizeof(sealed), back) == FZN_BLOB_ERR_SHAPE,
	      "hashing an oversized leaf was not refused");
	CHECK(fzn_blob_leaf_hash(&HASH, sealed, 0, back) == FZN_BLOB_ERR_SHAPE,
	      "hashing an empty leaf was not refused");
}

static void test_a_refusing_hash_carries_its_refusal_out(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t aead_key[FZN_AEAD_KEY_LEN];
	uint8_t commitment[FZN_COMMITMENT_LEN];
	uint8_t out[FZN_BLOB_HASH_LEN];
	uint8_t leaves[2u * FZN_BLOB_HASH_LEN];
	fzn_blob_tree_t tree;

	memset(key, 0x55, sizeof(key));
	make_leaves(leaves, 2u);

	/* A vtable that refuses must not be mistaken for one that worked. The
	 * outputs are never written, so the caller cannot proceed with half a
	 * key -- which is the failure this shape exists to prevent. */
	CHECK(fzn_blob_derive_leaf(&REFUSER, key, 0u, aead_key, commitment)
	              == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the derivation");
	CHECK(fzn_blob_leaf_hash(&REFUSER, leaves, FZN_BLOB_HASH_LEN, out) == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the leaf hash");
	CHECK(fzn_blob_node_hash(&REFUSER, leaves, leaves + FZN_BLOB_HASH_LEN, out)
	              == FZN_BLOB_ERR_HASH,
	      "a refusing hash did not stop the node hash");

	fzn_blob_tree_init(&tree);
	CHECK(fzn_blob_tree_push(&REFUSER, &tree, leaves) == FZN_BLOB_OK,
	      "the first push does not hash, so it should not have refused");
	CHECK(fzn_blob_tree_push(&REFUSER, &tree, leaves + FZN_BLOB_HASH_LEN)
	              == FZN_BLOB_ERR_HASH,
	      "the fold did not carry the hash's refusal out");
}

/* THE STREAMING TREE'S TWO CAPACITY REFUSALS, WHICH NO TEST NAMED.
 *
 * `FZN_BLOB_ERR_FULL` is produced at two places in `fzn_blob_tree_push` and
 * was named by nothing in this tree -- the only one of 117 error constants in
 * that state. project.md sec 61 has the sweep.
 *
 * REACHED BY CONSTRUCTING THE STATE RATHER THAN BY ARRIVING AT IT, and the
 * header's sentence is what licenses that: the leaf bound "needs
 * FZN_BLOB_MAX_LEAVES leaves and therefore cannot happen to a caller who is
 * not trying". That is true and it is not a claim that the guard cannot be
 * tested -- 2^40 pushes is not a test, a tree is caller-owned memory whose
 * fields this header publishes, and a test is exactly the caller who is
 * trying.
 *
 * EACH BOUND WITH THE OTHER SLACK, or one of the two guards could be deleted
 * and this would still pass on the survivor. And each with its own just-under
 * case, so a `>=` quietly becoming a `>` is caught as well as a guard going
 * missing. */
static void test_the_tree_refuses_when_it_is_full(void)
{
	uint8_t leaf[FZN_BLOB_HASH_LEN];
	fzn_blob_tree_t tree;
	unsigned i;

	memset(leaf, 0x5c, sizeof(leaf));

	/* THE LEAF BOUND, with the stack empty so nothing else can refuse. */
	fzn_blob_tree_init(&tree);
	tree.leaves = FZN_BLOB_MAX_LEAVES - 1u;
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_OK,
	      "a tree one leaf below the bound refused, so the bound is off by one");
	CHECK(tree.leaves == FZN_BLOB_MAX_LEAVES,
	      "the accepted push did not count, so the refusal below is not about a "
	      "full tree");
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_ERR_FULL,
	      "a tree holding FZN_BLOB_MAX_LEAVES accepted another leaf");

	/* THE DEPTH BOUND, with the leaf count nowhere near its own. The levels
	 * are strictly decreasing, which is the invariant the header states for
	 * this stack, so no fold runs and the depth is what refuses rather than
	 * the binary counter unwinding it. */
	fzn_blob_tree_init(&tree);
	for (i = 0; i < FZN_BLOB_MAX_DEPTH; i++)
		tree.level[i] = (uint8_t)(FZN_BLOB_MAX_DEPTH - i);
	tree.depth = FZN_BLOB_MAX_DEPTH - 1u;
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_OK,
	      "a stack one level below the bound refused, so the bound is off by one");
	CHECK(tree.depth == FZN_BLOB_MAX_DEPTH,
	      "the accepted push folded instead of growing the stack, so the refusal "
	      "below is not about a full one");
	CHECK(fzn_blob_tree_push(&HASH, &tree, leaf) == FZN_BLOB_ERR_FULL,
	      "a stack at FZN_BLOB_MAX_DEPTH accepted another leaf, so the write "
	      "would land past the end of the array");

	/* And it renders, which is the half `fzn_blob_err_str` owes a log. */
	CHECK(strcmp(fzn_blob_err_str(FZN_BLOB_ERR_FULL), "unknown") != 0,
	      "the only error code no test named also has no string");
}

static void test_every_guard_refuses_its_own_argument(void)
{
	uint8_t key[FZN_BLOB_KEY_LEN];
	uint8_t buf[FZN_BLOB_SEALED_MAX];
	uint8_t hash_out[FZN_BLOB_HASH_LEN];
	uint8_t aead_key[FZN_AEAD_KEY_LEN];
	uint8_t commitment[FZN_COMMITMENT_LEN];
	fzn_blob_tree_t tree;
	size_t len = 0;
	unsigned count = 0;

	memset(key, 0x66, sizeof(key));
	memset(buf, 0x77, sizeof(buf));
	fzn_blob_tree_init(&tree);

	CHECK(fzn_blob_derive_leaf(NULL, key, 0, aead_key, commitment) == FZN_BLOB_ERR_MALFORMED,
	      "null hash ops");
	CHECK(fzn_blob_derive_leaf(&HASH, NULL, 0, aead_key, commitment)
	              == FZN_BLOB_ERR_MALFORMED, "null content key");
	CHECK(fzn_blob_derive_leaf(&HASH, key, 0, NULL, commitment) == FZN_BLOB_ERR_MALFORMED,
	      "null key out");
	CHECK(fzn_blob_derive_leaf(&HASH, key, 0, aead_key, NULL) == FZN_BLOB_ERR_MALFORMED,
	      "null commitment out");

	CHECK(fzn_blob_leaf_seal(&HASH, &AEAD, key, 0, buf, 8u, buf, 8u, &len)
	              == FZN_BLOB_ERR_MALFORMED, "a buffer too small for the overhead");
	CHECK(fzn_blob_leaf_seal(&HASH, NULL, key, 0, buf, 8u, buf, sizeof(buf), &len)
	              == FZN_BLOB_ERR_MALFORMED, "null aead ops");
	CHECK(fzn_blob_leaf_open(&HASH, &AEAD, key, 0, NULL, 64u, buf, sizeof(buf), &len)
	              == FZN_BLOB_ERR_MALFORMED, "null sealed");

	CHECK(fzn_blob_tree_push(&HASH, NULL, hash_out) == FZN_BLOB_ERR_MALFORMED, "null tree");
	CHECK(fzn_blob_tree_push(&HASH, &tree, NULL) == FZN_BLOB_ERR_MALFORMED, "null leaf");
	CHECK(fzn_blob_tree_root(&HASH, &tree, NULL) == FZN_BLOB_ERR_MALFORMED, "null root out");

	CHECK(fzn_blob_proof_build(&HASH, buf, 0, 0, buf, sizeof(buf), &count)
	              == FZN_BLOB_ERR_MALFORMED, "a proof in a tree with no leaves");
	CHECK(fzn_blob_proof_build(&HASH, buf, 4u, 4u, buf, sizeof(buf), &count)
	              == FZN_BLOB_ERR_MALFORMED, "a proof for a leaf past the end");
	CHECK(fzn_blob_proof_verify(&HASH, hash_out, 4u, 4u, buf, 2u, hash_out)
	              == FZN_BLOB_ERR_MALFORMED, "verifying a leaf past the end");

	/* Every error code renders, including one that is not an enumerator:
	 * a log line reading "(null)" is worse than one reading "unknown". */
	CHECK(strcmp(fzn_blob_err_str(FZN_BLOB_OK), "ok") == 0, "ok does not render");
	CHECK(strcmp(fzn_blob_err_str((fzn_blob_err_t)99), "unknown") == 0,
	      "a value that is not an enumerator does not render as unknown");
}

/* The suite must be able to fail, or a green run says only that it ran. */
static void test_the_suite_can_tell_pass_from_fail(void)
{
	int before = failures;

	check_at(0, __LINE__, "deliberate");
	CHECK(failures == before + 1, "a failing check did not count");
	failures = before;
	checks -= 1;
}

int main(void)
{
	test_the_streaming_tree_agrees_with_the_definition();
	test_a_tree_with_no_leaves_has_no_root();
	test_the_leaf_and_node_prefixes_stop_a_forgery();
	test_distinct_leaf_counts_give_distinct_roots();
	test_a_proof_reaches_the_root();
	test_a_proof_that_is_wrong_is_refused();
	test_sealing_is_deterministic_and_reversible();
	test_a_leaf_is_bound_to_its_index();
	test_the_commitment_is_checked_before_the_aead();
	test_a_refused_open_leaves_nothing_usable();
	test_an_empty_leaf_is_refused();
	test_a_strangers_lengths_are_refused_as_shape();
	test_a_refusing_hash_carries_its_refusal_out();
	test_the_tree_refuses_when_it_is_full();
	test_every_guard_refuses_its_own_argument();
	test_the_suite_can_tell_pass_from_fail();

	printf("blob_test: %d checks, %d failure(s)\n", checks, failures);
	return failures == 0 ? 0 : 1;
}
